from typing import Any

class SerialException(Exception): ...

class Serial:
    def __init__(self, port: str | None = ..., baudrate: int = ..., timeout: float | None = ..., **kwargs: Any) -> None: ...
    def read(self, size: int = ...) -> bytes: ...
    def write(self, data: bytes) -> int | None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    @property
    def in_waiting(self) -> int: ...
