"""Manual stub for COBS encoding."""
from typing import Any

def encode(in_bytes: bytes | memoryview) -> bytes: ...
def decode(in_bytes: bytes | memoryview) -> bytes: ...

class DecodeError(Exception): ...
