"""High-level manual stub for Construct (SIL-2).
Only includes types used by the MCU Bridge project.
"""

from __future__ import annotations
from typing import Any, Optional, TypeVar

T = TypeVar("T")

class Construct:
    def parse(self, data: bytes | bytearray | memoryview, **contextkw: Any) -> Any: ...
    def build(self, obj: Any, **contextkw: Any) -> bytes: ...
    def sizeof(self, **contextkw: Any) -> int: ...
    def __truediv__(self, name: str) -> Construct: ...
    def __rtruediv__(self, name: str) -> Construct: ...
    def compile(self) -> Construct: ...

class Struct(Construct):
    def __init__(self, *subcons: Any, **fields: Any) -> None: ...

class BitStruct(Construct):
    def __init__(self, *subcons: Any) -> None: ...

class Subconstruct(Construct):
    def __init__(self, subcon: Any) -> None: ...

class Adapter(Subconstruct): ...

class Checksum(Adapter):
    def __init__(self, subcon: Any, hashfunc: Any, path: Any) -> None: ...

class RawCopy(Adapter): ...

class ExprAdapter(Adapter):
    def __init__(self, subcon: Any, encoder: Any, decoder: Any) -> None: ...

class FormatField(Construct): ...

Flag: FormatField
Int8ub: FormatField
Int16ub: FormatField
Int32ub: FormatField
Int64ub: FormatField
Int16ul: FormatField
Byte: FormatField

class BitsInteger(Construct):
    def __init__(self, length: int) -> None: ...

class Bytes(Construct):
    def __init__(self, length: int) -> None: ...

class GreedyBytes(Construct): ...

class Padding(Construct):
    def __init__(self, length: int, pattern: bytes = ...) -> None: ...

class Computed(Construct):
    def __init__(self, func: Any) -> None: ...

class Check(Construct):
    def __init__(self, func: Any) -> None: ...

class GreedyRange(Construct):
    def __init__(self, subcon: Any) -> None: ...

class Enum(Adapter):
    def __init__(self, subcon: Any, *merge: Any, **mapping: Any) -> None: ...

class Const(Subconstruct):
    def __init__(self, value: Any, subcon: Optional[Any] = None) -> None: ...

class FocusedSeq(Construct):
    def __init__(self, focus_item: Any, *subcons: Any) -> None: ...

class Select(Construct):
    def __init__(self, *subcons: Any) -> None: ...

class Terminated(Construct): ...

def compile(filename: Optional[str] = None) -> Any: ...  # noqa: A001

class ConstructError(Exception): ...

this: Any = ...
