"""Minimal cryptography.hazmat.primitives.hmac stub for local tests."""
from typing import Any

class HMAC:
    def __init__(self, key: bytes, algorithm: Any, backend: Any = None) -> None: ...
    def update(self, data: bytes) -> None: ...
    def finalize(self) -> bytes:
        return b"\x00" * 32
    def copy(self) -> "HMAC": ...
    def verify(self, signature: bytes) -> None: ...
