"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def encode(in_bytes: bytes | memoryview) -> bytes:
    ...

def decode(in_bytes: bytes | memoryview) -> bytes:
    ...

class DecodeError(Exception):
    ...


