"""Auto-generated Client Protocol Bindings for MCU Bridge v2.
DO NOT EDIT MANUALLY. Generated by tools/protocol/generate.py.
"""
from __future__ import annotations

from enum import IntEnum
from typing import Final

# Protocol Constants
PROTOCOL_VERSION: Final[int] = 2
DEFAULT_BAUDRATE: Final[int] = 115200
MAX_PAYLOAD_SIZE: Final[int] = 64
MAX_FILEPATH_LENGTH: Final[int] = 64
MAX_DATASTORE_KEY_LENGTH: Final[int] = 32


# Capabilities
CAPABILITY_WATCHDOG: Final[int] = 1
CAPABILITY_RLE: Final[int] = 2
CAPABILITY_DEBUG_FRAMES: Final[int] = 4
CAPABILITY_DEBUG_IO: Final[int] = 8
CAPABILITY_EEPROM: Final[int] = 16
CAPABILITY_DAC: Final[int] = 32
CAPABILITY_HW_SERIAL1: Final[int] = 64
CAPABILITY_FPU: Final[int] = 128
CAPABILITY_LOGIC_3V3: Final[int] = 256
CAPABILITY_BIG_BUFFER: Final[int] = 512
CAPABILITY_I2C: Final[int] = 1024
CAPABILITY_SPI: Final[int] = 2048


# Status Codes
class Status(IntEnum):
    OK = 48  # Operation completed successfully.
    ERROR = 49  # Generic failure.
    CMD_UNKNOWN = 50  # Command not recognized.
    MALFORMED = 51  # Payload had invalid structure.
    OVERFLOW = 52  # Frame exceeded buffer size.
    CRC_MISMATCH = 53  # CRC check failed.
    TIMEOUT = 54  # Operation timed out.
    NOT_IMPLEMENTED = 55  # Command defined but not supported.
    ACK = 56  # Generic acknowledgement for fire-and-forget commands.

# Command Enums
class Command(IntEnum):
    CMD_GET_VERSION = 64  # None
    CMD_GET_VERSION_RESP = 65  # None
    CMD_GET_FREE_MEMORY = 66  # None
    CMD_GET_FREE_MEMORY_RESP = 67  # None
    CMD_LINK_SYNC = 68  # Synchronize link state with mutual authentication. Payload: [16-byte Nonce] +
    # [16-byte HMAC Tag (optional)].
    CMD_LINK_SYNC_RESP = 69  # None
    CMD_LINK_RESET = 70  # Reset link state. Accepts optional payload with 'config_format' to update timing
    # parameters.
    CMD_LINK_RESET_RESP = 71  # None
    CMD_GET_CAPABILITIES = 72  # None
    CMD_GET_CAPABILITIES_RESP = 73  # None
    CMD_SET_BAUDRATE = 74  # None
    CMD_SET_BAUDRATE_RESP = 75  # None
    CMD_XOFF = 78  # Pause transmission (Flow Control)
    CMD_XON = 79  # Resume transmission (Flow Control)
    CMD_SET_PIN_MODE = 80  # None
    CMD_DIGITAL_WRITE = 81  # None
    CMD_ANALOG_WRITE = 82  # None
    CMD_DIGITAL_READ = 83  # None
    CMD_ANALOG_READ = 84  # None
    CMD_DIGITAL_READ_RESP = 85  # None
    CMD_ANALOG_READ_RESP = 86  # None
    CMD_CONSOLE_WRITE = 96  # None
    CMD_DATASTORE_PUT = 112  # None
    CMD_DATASTORE_GET = 113  # None
    CMD_DATASTORE_GET_RESP = 114  # None
    CMD_MAILBOX_READ = 128  # None
    CMD_MAILBOX_PROCESSED = 129  # None
    CMD_MAILBOX_AVAILABLE = 130  # None
    CMD_MAILBOX_PUSH = 131  # None
    CMD_MAILBOX_READ_RESP = 132  # None
    CMD_MAILBOX_AVAILABLE_RESP = 133  # None
    CMD_FILE_WRITE = 144  # None
    CMD_FILE_READ = 145  # None
    CMD_FILE_REMOVE = 146  # None
    CMD_FILE_READ_RESP = 147  # None
    CMD_PROCESS_RUN_ASYNC = 161  # None
    CMD_PROCESS_POLL = 162  # None
    CMD_PROCESS_KILL = 163  # None
    CMD_PROCESS_RUN_ASYNC_RESP = 165  # None
    CMD_PROCESS_POLL_RESP = 166  # None
