from typing import Any

class ErrorReturnCode_1(Exception):
    def __init__(self, full_cmd: bytes, stdout: bytes, stderr: bytes, truncate: bool = ...) -> None: ...

class ErrorReturnCode(Exception):
    def __init__(self, full_cmd: bytes, stdout: bytes, stderr: bytes, truncate: bool = ...) -> None: ...

class TimeoutException(Exception): ...

def du(*args: Any, **kwargs: Any) -> Any: ...
def uci(*args: Any, **kwargs: Any) -> Any: ...
def mosquitto_pub(*args: Any, **kwargs: Any) -> Any: ...
def mosquitto_sub(*args: Any, **kwargs: Any) -> Any: ...
def logger(*args: Any, **kwargs: Any) -> Any: ...
def which(cmd: str) -> Any: ...

class Command:
    def __init__(self, path: str) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
