from typing import Any

class Error(Exception): ...
class NoSuchProcess(Error): ...
class TimeoutExpired(Error): ...

class Process:
    def __init__(self, pid: int | None = ...) -> None: ...
    def terminate(self) -> None: ...
    def kill(self) -> None: ...
    def wait(self, timeout: float | None = ...) -> int | None: ...
    def poll(self) -> int | None: ...
    def children(self, recursive: bool = ...) -> list[Process]: ...
    @property
    def pid(self) -> int: ...
