"""
This type stub file was generated by pyright.
"""

import abc
from typing import BinaryIO, Optional, Protocol, Union
from .diagrams import GraphMachine, HierarchicalGraphMachine
from ..core import ModelState

"""
This type stub file was generated by pyright.
"""
class GraphProtocol(Protocol):
    def draw(self, filename: Optional[Union[str, BinaryIO]], format: Optional[str] = ..., prog: Optional[str] = ..., args: str = ...) -> Optional[str]:
        ...
    


class GraphModelProtocol(Protocol):
    def get_graph(self, title: Optional[str] = ..., force_new: bool = ..., show_roi: bool = ...) -> GraphProtocol:
        ...
    


class BaseGraph(metaclass=abc.ABCMeta):
    machine: Union[GraphMachine, HierarchicalGraphMachine]
    fsm_graph: Optional[GraphProtocol]
    def __init__(self, machine: GraphMachine) -> None:
        ...
    
    @abc.abstractmethod
    def generate(self) -> None:
        ...
    
    @abc.abstractmethod
    def set_previous_transition(self, src: str, dst: str) -> None:
        ...
    
    @abc.abstractmethod
    def reset_styling(self) -> None:
        ...
    
    @abc.abstractmethod
    def set_node_style(self, state: ModelState, style: str) -> None:
        ...
    
    @abc.abstractmethod
    def get_graph(self, title: Optional[str] = ..., roi_state: Optional[str] = ...) -> GraphProtocol:
        ...
    


