"""
This type stub file was generated by pyright.
"""

from ..core import CallbackFunc, Machine
from .diagrams import GraphMachine, HierarchicalGraphMachine, NestedGraphTransition
from .locking import LockedMachine
from .nesting import HierarchicalMachine, NestedEvent
from typing import Dict, Tuple, Type, Union
from transitions.extensions.asyncio import AsyncMachine, AsyncTransition, HierarchicalAsyncMachine, NestedAsyncTransition

"""
This type stub file was generated by pyright.
"""
class MachineFactory:
    @staticmethod
    def get_predefined(graph: bool = ..., nested: bool = ..., locked: bool = ..., asyncio: bool = ...) -> Union[Type[Machine], Type[HierarchicalMachine], Type[AsyncMachine], Type[HierarchicalAsyncMachine], Type[GraphMachine], Type[HierarchicalGraphMachine], Type[AsyncGraphMachine], Type[HierarchicalAsyncGraphMachine], Type[LockedMachine], Type[LockedHierarchicalMachine], Type[LockedGraphMachine], Type[LockedHierarchicalGraphMachine]]:
        ...
    


class LockedHierarchicalMachine(LockedMachine, HierarchicalMachine):
    event_cls: Type[NestedEvent]
    ...


class LockedGraphMachine(GraphMachine, LockedMachine):
    @staticmethod
    def format_references(func: CallbackFunc) -> str:
        ...
    


class LockedHierarchicalGraphMachine(GraphMachine, LockedHierarchicalMachine):
    transition_cls: Type[NestedGraphTransition]
    event_cls: Type[NestedEvent]
    @staticmethod
    def format_references(func: CallbackFunc) -> str:
        ...
    


class AsyncGraphMachine(GraphMachine, AsyncMachine):
    transition_cls: Type[AsyncTransition]
    ...


class HierarchicalAsyncGraphMachine(GraphMachine, HierarchicalAsyncMachine):
    transition_cls: Type[NestedAsyncTransition]
    ...


_CLASS_MAP: Dict[Tuple[bool, bool, bool, bool], Type[Machine]]
