"""
This type stub file was generated by pyright.
"""

from ..core import Callback, CallbackFunc, CallbacksArg, Event, EventData, Machine, ModelParameter, State, Transition, TransitionConfig
from typing import Any, Collection, Dict, List, Optional, OrderedDict, Sequence, Tuple, Type, Union
from types import TracebackType
from logging import Logger
from enum import Enum

"""
This type stub file was generated by pyright.
"""
_LOGGER: Logger
class FunctionWrapper:
    _func: Optional[CallbackFunc]
    def __init__(self, func: CallbackFunc, path: List[str]) -> None:
        ...
    
    def add(self, func: CallbackFunc, path: List[str]) -> None:
        ...
    
    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        ...
    


class NestedEvent(Event):
    def trigger_nested(self, event_data: NestedEventData) -> bool:
        ...
    


class NestedEventData(EventData):
    state: NestedState
    event: NestedEvent
    machine: HierarchicalMachine
    transition: Optional[NestedTransition]
    source_name: Optional[str]
    source_path: Optional[List[str]]
    ...


class NestedState(State):
    separator: str
    initial: Optional[str]
    events: Dict[str, NestedEvent]
    states: OrderedDict[str, NestedState]
    _scope: List[str]
    def __init__(self, name: Union[str, Enum], on_enter: CallbacksArg = ..., on_exit: CallbacksArg = ..., ignore_invalid_triggers: bool = ..., final: bool = ..., initial: Optional[str] = ..., on_final: CallbacksArg = ...) -> None:
        ...
    
    def add_substate(self, state: NestedState) -> None:
        ...
    
    def add_substates(self, states: List[NestedState]) -> None:
        ...
    
    def scoped_enter(self, event_data: NestedEventData, scope: List[str] = ...) -> None:
        ...
    
    def scoped_exit(self, event_data: NestedEventData, scope: List[str] = ...) -> None:
        ...
    
    @property
    def name(self) -> str:
        ...
    


NestedStateIdentifier = Union[str, Enum, NestedState, Sequence[Union[str, Enum, NestedState, Sequence[Any]]]]
NestedStateConfig = Union[NestedStateIdentifier, Dict[str, Any], Collection[str], 'HierarchicalMachine']
StateTree = OrderedDict[str, Any]
def resolve_order(state_tree: Dict[str, str]) -> List[List[str]]:
    ...

class NestedTransition(Transition):
    def __deepcopy__(self, memo: Dict[str, Any]) -> NestedTransition:
        ...
    


ScopeTuple = Tuple[Union[NestedState, 'HierarchicalMachine'], OrderedDict[str, NestedState], Dict[str, NestedEvent], List[str]]
class HierarchicalMachine(Machine):
    state_cls: Type[NestedState]
    transition_cls: Type[NestedTransition]
    event_cls: Type[NestedEvent]
    states: OrderedDict[str, NestedState]
    events: Dict[str, NestedEvent]
    _stack: List[ScopeTuple]
    _initial: Optional[str]
    prefix_path: List[str]
    scoped: Union[NestedState, HierarchicalMachine]
    def __init__(self, model: Optional[ModelParameter] = ..., states: Optional[Union[Sequence[NestedStateConfig], Type[Enum]]] = ..., initial: Optional[NestedStateIdentifier] = ..., transitions: Optional[Union[TransitionConfig, Sequence[TransitionConfig]]] = ..., send_event: bool = ..., auto_transitions: bool = ..., ordered_transitions: bool = ..., ignore_invalid_triggers: Optional[bool] = ..., before_state_change: CallbacksArg = ..., after_state_change: CallbacksArg = ..., name: str = ..., queued: Union[bool, str] = ..., prepare_event: CallbacksArg = ..., finalize_event: CallbacksArg = ..., model_attribute: str = ..., on_exception: CallbacksArg = ..., **kwargs: Any) -> None:
        ...
    
    _next_scope: Optional[ScopeTuple]
    def __call__(self, to_scope: Optional[Union[ScopeTuple, str, Enum]] = ...) -> HierarchicalMachine:
        ...
    
    def __enter__(self) -> None:
        ...
    
    def __exit__(self, exc_type: Optional[Type[BaseException]], exc_val: Optional[BaseException], exc_tb: Optional[TracebackType]) -> None:
        ...
    
    def add_model(self, model: ModelParameter, initial: Optional[NestedStateIdentifier] = ...) -> None:
        ...
    
    @property
    def initial(self) -> Optional[str]:
        ...
    
    @initial.setter
    def initial(self, value: NestedStateIdentifier) -> None:
        ...
    
    def add_ordered_transitions(self, states: Optional[Sequence[NestedState]] = ..., trigger: str = ..., loop: bool = ..., loop_includes_initial: bool = ..., conditions: CallbacksArg = ..., unless: CallbacksArg = ..., before: CallbacksArg = ..., after: CallbacksArg = ..., prepare: CallbacksArg = ..., **kwargs: Any) -> None:
        ...
    
    def add_states(self, states: Union[List[NestedStateConfig], NestedStateConfig], on_enter: CallbacksArg = ..., on_exit: CallbacksArg = ..., ignore_invalid_triggers: Optional[bool] = ..., **kwargs: Any) -> None:
        ...
    
    def add_transition(self, trigger: str, source: Union[NestedStateIdentifier, List[NestedStateIdentifier]], dest: Optional[NestedStateIdentifier] = ..., conditions: CallbacksArg = ..., unless: CallbacksArg = ..., before: CallbacksArg = ..., after: CallbacksArg = ..., prepare: CallbacksArg = ..., **kwargs: Any) -> None:
        ...
    
    def get_global_name(self, state: NestedStateIdentifier = ..., join: bool = ...) -> Union[str, List[str]]:
        ...
    
    def get_nested_state_names(self) -> List[str]:
        ...
    
    def get_nested_transitions(self, trigger: str = ..., src_path: Optional[List[str]] = ..., dest_path: Optional[List[str]] = ...) -> List[NestedTransition]:
        ...
    
    def get_nested_triggers(self, src_path: Optional[List[str]] = ...) -> List[str]:
        ...
    
    def get_state(self, state: Union[str, Enum, List[str]], hint: Optional[List[str]] = ...) -> NestedState:
        ...
    
    def get_states(self, states: Union[str, Enum, List[Union[str, Enum]]]) -> List[NestedState]:
        ...
    
    def get_transitions(self, trigger: str = ..., source: NestedStateIdentifier = ..., dest: NestedStateIdentifier = ..., delegate: bool = ...) -> List[NestedTransition]:
        ...
    
    def get_triggers(self, *args: Union[str, Enum, State]) -> List[str]:
        ...
    
    def has_trigger(self, trigger: str, state: Optional[NestedState] = ...) -> bool:
        ...
    
    def is_state(self, state: Union[str, Enum], model: object, allow_substates: bool = ...) -> bool:
        ...
    
    def on_enter(self, state_name: str, callback: Callback) -> None:
        ...
    
    def on_exit(self, state_name: str, callback: Callback) -> None:
        ...
    
    def set_state(self, state: Union[NestedStateIdentifier, List[NestedStateIdentifier]], model: Optional[object] = ...) -> None:
        ...
    
    def to_state(self, model: object, state_name: str, *args: Any, **kwargs: Any) -> None:
        ...
    
    def trigger_event(self, model: object, trigger: str, *args: Any, **kwargs: Any) -> bool:
        ...
    
    def build_state_tree(self, model_states: Union[str, Enum, Sequence[Union[str, Enum, Sequence[Any]]]], separator: str, tree: Optional[StateTree] = ...) -> StateTree:
        ...
    


