/*
 * This file is part of Arduino MCU Ecosystem v2.
 * Copyright (C) 2025-2026 Ignacio Santolin and contributors
 *
 * Auto-generated by tools/protocol/generate.py via Jinja2. DO NOT EDIT.
 */
#ifndef RPC_PROTOCOL_H
#define RPC_PROTOCOL_H

#include <stddef.h>
#include <stdint.h>
#include <etl/array.h>
#include <etl/type_traits.h>
#include <etl/algorithm.h>
#include <etl/iterator.h>

namespace rpc {

inline constexpr uint8_t PROTOCOL_VERSION = 2U;
inline constexpr uint8_t FIRMWARE_VERSION_MAJOR = 2U;
inline constexpr uint8_t FIRMWARE_VERSION_MINOR = 8U;
inline constexpr uint8_t FIRMWARE_VERSION_PATCH = 5U;
inline constexpr unsigned long RPC_DEFAULT_BAUDRATE = 115'200UL;
inline constexpr size_t MAX_PAYLOAD_SIZE = 64;
inline constexpr unsigned long RPC_DEFAULT_SAFE_BAUDRATE = 115'200UL;
inline constexpr uint32_t RPC_SERIAL_TIMEOUT_MS = 50U;
inline constexpr uint32_t RPC_SPI_TIMEOUT_MS = 50U;
inline constexpr size_t RPC_MAX_FILEPATH_LENGTH = 64;
inline constexpr size_t RPC_MAX_DATASTORE_KEY_LENGTH = 32;
inline constexpr unsigned int RPC_DEFAULT_ACK_TIMEOUT_MS = 200U;
inline constexpr uint8_t RPC_DEFAULT_RETRY_LIMIT = 5U;
inline constexpr uint8_t RPC_MAX_PENDING_TX_FRAMES = 2U;
inline constexpr uint16_t RPC_INVALID_ID_SENTINEL = 65'535U;
inline constexpr char RPC_NULL_TERMINATOR = 0;
inline constexpr uint8_t RPC_COMMAND_STRIDE = 2U;
inline constexpr uint8_t RPC_COMMAND_GROUP_SHIFT = 4U;
inline constexpr uint8_t RPC_COMMAND_GROUP_OFFSET = 3U;
inline constexpr uint32_t RPC_TIMER_OVERFLOW_THRESHOLD = 2'147'483'648U;
inline constexpr uint16_t RPC_CMD_FLAG_COMPRESSED = 32'768U;
inline constexpr uint8_t RPC_CMD_FLAG_COMPRESSED_BIT = 15U;
inline constexpr uint8_t RPC_UINT8_MASK = 255U;
inline constexpr uint16_t RPC_UINT16_MAX = 65'535U;
inline constexpr uint32_t RPC_BOOTLOADER_MAGIC = 3'735'929'054U;
inline constexpr uint8_t RPC_PROCESS_DEFAULT_EXIT_CODE = 255U;
inline constexpr uint32_t RPC_CRC32_MASK = 4'294'967'295U;
inline constexpr uint32_t RPC_CRC_INITIAL = 4'294'967'295U;
inline constexpr uint32_t RPC_CRC_POLYNOMIAL = 3'988'292'384U;
inline constexpr uint8_t RPC_FRAME_DELIMITER = 0U;
inline constexpr uint8_t RPC_DIGITAL_LOW = 0U;
inline constexpr uint8_t RPC_DIGITAL_HIGH = 1U;
inline constexpr uint8_t RPC_RLE_ESCAPE_BYTE = 255U;
inline constexpr uint8_t RPC_RLE_MIN_RUN_LENGTH = 4U;
inline constexpr uint16_t RPC_RLE_MAX_RUN_LENGTH = 256U;
inline constexpr uint8_t RPC_RLE_SINGLE_ESCAPE_MARKER = 255U;
inline constexpr uint8_t RPC_RLE_EXPANSION_FACTOR = 3U;
inline constexpr uint8_t RPC_RLE_OFFSET = 2U;
inline constexpr size_t RPC_RLE_MIN_COMPRESS_INPUT_SIZE = 8;
inline constexpr size_t RPC_RLE_MIN_COMPRESS_SAVINGS = 4;
inline constexpr uint8_t RPC_SHA256_DIGEST_SIZE = 32U;
inline constexpr uint8_t RPC_SHA256_KAT_BUFFER_SIZE = 64U;
inline constexpr uint8_t RPC_STATUS_CODE_MIN = 48U;
inline constexpr uint8_t RPC_STATUS_CODE_MAX = 63U;
inline constexpr uint16_t RPC_SYSTEM_COMMAND_MIN = 64U;
inline constexpr uint16_t RPC_SYSTEM_COMMAND_MAX = 79U;
inline constexpr uint16_t RPC_GPIO_COMMAND_MIN = 80U;
inline constexpr uint16_t RPC_GPIO_COMMAND_MAX = 95U;
inline constexpr uint16_t RPC_CONSOLE_COMMAND_MIN = 96U;
inline constexpr uint16_t RPC_CONSOLE_COMMAND_MAX = 111U;
inline constexpr uint16_t RPC_DATASTORE_COMMAND_MIN = 112U;
inline constexpr uint16_t RPC_DATASTORE_COMMAND_MAX = 127U;
inline constexpr uint16_t RPC_MAILBOX_COMMAND_MIN = 128U;
inline constexpr uint16_t RPC_MAILBOX_COMMAND_MAX = 143U;
inline constexpr uint16_t RPC_FILESYSTEM_COMMAND_MIN = 144U;
inline constexpr uint16_t RPC_FILESYSTEM_COMMAND_MAX = 159U;
inline constexpr uint16_t RPC_PROCESS_COMMAND_MIN = 160U;
inline constexpr uint16_t RPC_PROCESS_COMMAND_MAX = 175U;
inline constexpr uint16_t RPC_SPI_COMMAND_MIN = 176U;
inline constexpr uint16_t RPC_SPI_COMMAND_MAX = 191U;
inline constexpr uint8_t MSGPACK_FIXARRAY_MASK = 144U;
inline constexpr uint8_t MSGPACK_FIXSTR_MASK = 160U;
inline constexpr uint8_t MSGPACK_BIN8 = 196U;
inline constexpr uint8_t MSGPACK_BIN16 = 197U;
inline constexpr uint8_t MSGPACK_BIN32 = 198U;
inline constexpr uint8_t MSGPACK_UINT8_FMT = 204U;
inline constexpr uint8_t MSGPACK_UINT16_FMT = 205U;
inline constexpr uint8_t MSGPACK_UINT32_FMT = 206U;
inline constexpr uint8_t MSGPACK_STR8 = 217U;
inline constexpr uint8_t MSGPACK_STR16 = 218U;
inline constexpr uint8_t MSGPACK_STR32 = 219U;
inline constexpr uint8_t MSGPACK_ARRAY16 = 220U;
inline constexpr uint8_t MSGPACK_ARRAY32 = 221U;
inline constexpr uint8_t MSGPACK_POSITIVE_FIXINT_MAX = 127U;
inline constexpr uint8_t MSGPACK_FIXARRAY_TYPE_MASK = 240U;
inline constexpr uint8_t MSGPACK_FIXARRAY_VALUE_MASK = 15U;
inline constexpr uint8_t MSGPACK_FIXSTR_TYPE_MASK = 224U;
inline constexpr uint8_t MSGPACK_FIXSTR_VALUE_MASK = 31U;
inline constexpr uint8_t MSGPACK_UINT8_MAX_VAL = 255U;
inline constexpr uint16_t MSGPACK_UINT16_MAX_VAL = 65'535U;

inline constexpr unsigned int RPC_HANDSHAKE_NONCE_LENGTH = 16U;
inline constexpr unsigned int RPC_HANDSHAKE_TAG_LENGTH = 16U;
inline constexpr uint32_t RPC_HANDSHAKE_ACK_TIMEOUT_MIN_MS = 25U;
inline constexpr uint32_t RPC_HANDSHAKE_ACK_TIMEOUT_MAX_MS = 60'000U;
inline constexpr uint32_t RPC_HANDSHAKE_RESPONSE_TIMEOUT_MIN_MS = 100U;
inline constexpr uint32_t RPC_HANDSHAKE_RESPONSE_TIMEOUT_MAX_MS = 180'000U;
inline constexpr unsigned int RPC_HANDSHAKE_RETRY_LIMIT_MIN = 1U;
inline constexpr unsigned int RPC_HANDSHAKE_RETRY_LIMIT_MAX = 8U;
inline constexpr unsigned int RPC_HANDSHAKE_HKDF_OUTPUT_LENGTH = 32U;
inline constexpr unsigned int RPC_HANDSHAKE_NONCE_RANDOM_BYTES = 8U;
inline constexpr unsigned int RPC_HANDSHAKE_NONCE_COUNTER_BYTES = 8U;

inline constexpr unsigned int RPC_HANDSHAKE_CONFIG_SIZE = 7U;

inline constexpr etl::array<uint8_t, 12U> RPC_HANDSHAKE_HKDF_SALT = { 0x6D, 0x63, 0x75, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2D, 0x76, 0x32 };

inline constexpr etl::array<uint8_t, 14U> RPC_HANDSHAKE_HKDF_INFO_AUTH = { 0x68, 0x61, 0x6E, 0x64, 0x73, 0x68, 0x61, 0x6B, 0x65, 0x2D, 0x61, 0x75, 0x74, 0x68 };

inline constexpr uint32_t RPC_CAPABILITY_WATCHDOG = 1U;
inline constexpr uint32_t RPC_CAPABILITY_RLE = 2U;
inline constexpr uint32_t RPC_CAPABILITY_DEBUG_FRAMES = 4U;
inline constexpr uint32_t RPC_CAPABILITY_DEBUG_IO = 8U;
inline constexpr uint32_t RPC_CAPABILITY_EEPROM = 16U;
inline constexpr uint32_t RPC_CAPABILITY_DAC = 32U;
inline constexpr uint32_t RPC_CAPABILITY_HW_SERIAL1 = 64U;
inline constexpr uint32_t RPC_CAPABILITY_FPU = 128U;
inline constexpr uint32_t RPC_CAPABILITY_LOGIC_3V3 = 256U;
inline constexpr uint32_t RPC_CAPABILITY_BIG_BUFFER = 512U;
inline constexpr uint32_t RPC_CAPABILITY_I2C = 1024U;
inline constexpr uint32_t RPC_CAPABILITY_SPI = 2048U;
inline constexpr uint32_t RPC_CAPABILITY_SD = 4096U;

inline constexpr uint8_t RPC_ARCH_AVR = 1U;
inline constexpr uint8_t RPC_ARCH_ESP32 = 2U;
inline constexpr uint8_t RPC_ARCH_ESP8266 = 3U;
inline constexpr uint8_t RPC_ARCH_SAMD = 4U;
inline constexpr uint8_t RPC_ARCH_SAM = 5U;
inline constexpr uint8_t RPC_ARCH_RP2040 = 6U;

enum class CompressionType : uint8_t {
    COMPRESSION_NONE = 0,
    COMPRESSION_RLE = 1,
};

enum class StatusCode : uint8_t {
    STATUS_OK = 48,
    STATUS_ERROR = 49,
    STATUS_CMD_UNKNOWN = 50,
    STATUS_MALFORMED = 51,
    STATUS_OVERFLOW = 52,
    STATUS_CRC_MISMATCH = 53,
    STATUS_TIMEOUT = 54,
    STATUS_NOT_IMPLEMENTED = 55,
    STATUS_ACK = 56,
};

enum class CommandId : uint16_t {
    CMD_GET_VERSION = 64,
    CMD_GET_VERSION_RESP = 65,
    CMD_GET_FREE_MEMORY = 66,
    CMD_GET_FREE_MEMORY_RESP = 67,
    CMD_LINK_SYNC = 68,
    CMD_LINK_SYNC_RESP = 69,
    CMD_LINK_RESET = 70,
    CMD_LINK_RESET_RESP = 71,
    CMD_GET_CAPABILITIES = 72,
    CMD_GET_CAPABILITIES_RESP = 73,
    CMD_SET_BAUDRATE = 74,
    CMD_SET_BAUDRATE_RESP = 75,
    CMD_ENTER_BOOTLOADER = 76,
    CMD_XOFF = 78,
    CMD_XON = 79,
    CMD_SET_PIN_MODE = 80,
    CMD_DIGITAL_WRITE = 81,
    CMD_ANALOG_WRITE = 82,
    CMD_DIGITAL_READ = 83,
    CMD_ANALOG_READ = 84,
    CMD_DIGITAL_READ_RESP = 85,
    CMD_ANALOG_READ_RESP = 86,
    CMD_CONSOLE_WRITE = 96,
    CMD_DATASTORE_PUT = 112,
    CMD_DATASTORE_GET = 113,
    CMD_DATASTORE_GET_RESP = 114,
    CMD_MAILBOX_READ = 128,
    CMD_MAILBOX_PROCESSED = 129,
    CMD_MAILBOX_AVAILABLE = 130,
    CMD_MAILBOX_PUSH = 131,
    CMD_MAILBOX_READ_RESP = 132,
    CMD_MAILBOX_AVAILABLE_RESP = 133,
    CMD_FILE_WRITE = 144,
    CMD_FILE_READ = 145,
    CMD_FILE_REMOVE = 146,
    CMD_FILE_READ_RESP = 147,
    CMD_PROCESS_RUN_ASYNC = 161,
    CMD_PROCESS_POLL = 162,
    CMD_PROCESS_KILL = 163,
    CMD_PROCESS_RUN_ASYNC_RESP = 165,
    CMD_PROCESS_POLL_RESP = 166,
    CMD_SPI_BEGIN = 176,
    CMD_SPI_TRANSFER = 177,
    CMD_SPI_TRANSFER_RESP = 178,
    CMD_SPI_END = 179,
    CMD_SPI_SET_CONFIG = 180,
};

template <typename E>
constexpr etl::underlying_type_t<E> to_underlying(E value) {
    return static_cast<etl::underlying_type_t<E>>(value);
}

constexpr bool requires_ack(CommandId command_id) {
    constexpr uint16_t MAX_CMD_ID = 256U;
    struct AckBitset {
        uint32_t bits[MAX_CMD_ID / 32U] = {0};
        constexpr AckBitset() {
            bits[static_cast<uint16_t>(CommandId::CMD_ENTER_BOOTLOADER) / 32U] |= (1UL << (static_cast<uint16_t>(CommandId::CMD_ENTER_BOOTLOADER) % 32U));
            bits[static_cast<uint16_t>(CommandId::CMD_SET_PIN_MODE) / 32U] |= (1UL << (static_cast<uint16_t>(CommandId::CMD_SET_PIN_MODE) % 32U));
            bits[static_cast<uint16_t>(CommandId::CMD_DIGITAL_WRITE) / 32U] |= (1UL << (static_cast<uint16_t>(CommandId::CMD_DIGITAL_WRITE) % 32U));
            bits[static_cast<uint16_t>(CommandId::CMD_ANALOG_WRITE) / 32U] |= (1UL << (static_cast<uint16_t>(CommandId::CMD_ANALOG_WRITE) % 32U));
            bits[static_cast<uint16_t>(CommandId::CMD_CONSOLE_WRITE) / 32U] |= (1UL << (static_cast<uint16_t>(CommandId::CMD_CONSOLE_WRITE) % 32U));
            bits[static_cast<uint16_t>(CommandId::CMD_DATASTORE_PUT) / 32U] |= (1UL << (static_cast<uint16_t>(CommandId::CMD_DATASTORE_PUT) % 32U));
            bits[static_cast<uint16_t>(CommandId::CMD_MAILBOX_PUSH) / 32U] |= (1UL << (static_cast<uint16_t>(CommandId::CMD_MAILBOX_PUSH) % 32U));
            bits[static_cast<uint16_t>(CommandId::CMD_FILE_WRITE) / 32U] |= (1UL << (static_cast<uint16_t>(CommandId::CMD_FILE_WRITE) % 32U));
            bits[static_cast<uint16_t>(CommandId::CMD_SPI_BEGIN) / 32U] |= (1UL << (static_cast<uint16_t>(CommandId::CMD_SPI_BEGIN) % 32U));
            bits[static_cast<uint16_t>(CommandId::CMD_SPI_END) / 32U] |= (1UL << (static_cast<uint16_t>(CommandId::CMD_SPI_END) % 32U));
            bits[static_cast<uint16_t>(CommandId::CMD_SPI_SET_CONFIG) / 32U] |= (1UL << (static_cast<uint16_t>(CommandId::CMD_SPI_SET_CONFIG) % 32U));
        }
        constexpr bool test(uint16_t id) const {
            if (id >= MAX_CMD_ID) return false;
            return (bits[id / 32U] & (1UL << (id % 32U))) != 0;
        }
    };
    constexpr AckBitset ACK_MAP;
    return ACK_MAP.test(to_underlying(command_id));
}

constexpr bool requires_ack(uint16_t command_id) {
    return requires_ack(static_cast<CommandId>(command_id));
}

} // namespace rpc

#endif // RPC_PROTOCOL_H
