from typing import Any, Dict, Generic, TypeVar, Union, Optional

_ParsedType = TypeVar("_ParsedType")

class Container(Dict[str, Any]):
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...

class Construct(Generic[_ParsedType]):
    def parse(self, data: bytes, **contextkw: Any) -> _ParsedType: ...
    def build(self, obj: Any, **contextkw: Any) -> bytes: ...
    def sizeof(self, **contextkw: Any) -> int: ...
    def __rtruediv__(self, other: str) -> "Renamed[_ParsedType]": ...
    def __add__(self, other: "Construct[Any]") -> "Construct[Any]": ...

class Renamed(Construct[_ParsedType]):
    subcon: Construct[_ParsedType]
    name: str

class FormatField(Construct[int]):
    def __init__(self, endianness: str, format: str) -> None: ...

Int8ub: FormatField
Int16ub: FormatField
Int32ub: FormatField
Int64ub: FormatField
Int8sb: FormatField
Int16sb: FormatField
Int32sb: FormatField
Int64sb: FormatField

class Bytes(Construct[bytes]):
    def __init__(self, length: Any) -> None: ...

class GreedyBytes(Construct[bytes]): ...

class PaddedString(Construct[str]):
    def __init__(self, length: Any, encoding: str) -> None: ...

class PascalString(Construct[str]):
    def __init__(self, lengthfield: Construct[int], encoding: str) -> None: ...

class Struct(Construct[Container]):
    def __init__(self, *subcons: Any) -> None: ...

class Array(Construct[Any]):
    def __init__(self, count: Any, subcon: Construct[Any]) -> None: ...

class PrefixedArray(Construct[Any]):
    def __init__(self, lengthfield: Construct[int], subcon: Construct[Any]) -> None: ...

class Const(Construct[Any]):
    def __init__(self, value: Any, subcon: Optional[Construct[Any]] = None) -> None: ...

class Path:
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

this: Path

def len_(obj: Any) -> int: ...
