"""Shared constants for MCU Bridge daemon components.

This file is the central registry for **application defaults** (paths, limits,
intervals) used when the OpenWrt UCI configuration is missing or incomplete.

[SIL-2 COMPLIANCE - IEC 61508]
Default values are chosen with safety margins:
- Timeouts prevent indefinite blocking
- Queue limits prevent memory exhaustion
- File paths default to /tmp (RAM) to protect flash storage
- All limits are validated in config/settings.py before use

Architecture Layers:
- `mcubridge.protocol.protocol`: Generated byte-level contract (source of truth).
- `mcubridge.const`: Application defaults (this file).
- `mcubridge.config.settings`: Runtime configuration loaded from UCI/defaults.

Configuration Flow:
    mcubridge.proto -> generate.py -> protocol.py (constants)
    UCI/defaults -> settings.py -> RuntimeConfig (validated)
"""

from __future__ import annotations

from ssl import TLSVersion
from typing import Final

# ==============================================================================
# SECTION 1: APPLICATION DEFAULTS
# ==============================================================================
# These values define the default behavior of the Python daemon.
# They can usually be overridden by UCI configuration or Environment Variables.

from ..protocol import protocol

# -- Serial Port Defaults --
DEFAULT_SERIAL_PORT: Final[str] = "/dev/ttyATH0"

# Timeout for general serial operations (not strict RPC)
DEFAULT_SERIAL_RETRY_TIMEOUT: Final[float] = 10.0
DEFAULT_SERIAL_RESPONSE_TIMEOUT: Final[float] = 20.0
SERIAL_BAUDRATE_NEGOTIATION_TIMEOUT: Final[float] = 2.0
DEFAULT_SERIAL_HANDSHAKE_MIN_INTERVAL: Final[float] = 0.0

# Backoff strategy for handshake retries
SERIAL_HANDSHAKE_BACKOFF_BASE: Final[float] = 1.0
SERIAL_HANDSHAKE_BACKOFF_MAX: Final[float] = 60.0
SERIAL_MIN_ACK_TIMEOUT: Final[float] = float(protocol.DEFAULT_ACK_TIMEOUT_MS) / 1000.0

# -- Cloud Defaults --
DEFAULT_CLOUD_HOST: Final[str] = "127.0.0.1"
DEFAULT_CLOUD_PORT: Final[int] = 8443
DEFAULT_CLOUD_CAFILE: Final[str] = "/etc/ssl/certs/ca-certificates.crt"
DEFAULT_CLOUD_QUEUE_LIMIT: Final[int] = 256
CLOUD_TLS_MIN_VERSION: Final[TLSVersion] = TLSVersion.TLSv1_2
# [CRITICAL] Spool directory in RAM to prevent Flash wear
DEFAULT_CLOUD_SPOOL_DIR: Final[str] = "/tmp/mcubridge/spool"

# -- Cloud Spool Backoff Strategy --
SPOOL_BACKOFF_MULTIPLIER: Final[float] = 5.0
SPOOL_BACKOFF_MIN_SECONDS: Final[float] = 5.0
SPOOL_BACKOFF_MAX_SECONDS: Final[float] = 60.0

# -- File System Defaults --
DEFAULT_FILE_SYSTEM_ROOT: str = "/tmp/yun_files"
MCU_FS_PREFIX: Final[str] = "mcu/"
DEFAULT_FILE_WRITE_MAX_BYTES: Final[int] = 262144
DEFAULT_FILE_STORAGE_QUOTA_BYTES: Final[int] = 8388608

# Paths considered safe (volatile/RAM) for writing to avoid flash wear
VOLATILE_STORAGE_PATHS: frozenset[str] = frozenset({"/tmp", "/var/run", "/run", "/dev/shm"})
SYSTEMD_PRIVATE_PREFIX: Final[str] = "systemd-private-"

# -- Component Limits --
DEFAULT_PROCESS_TIMEOUT: Final[int] = 10
DEFAULT_PROCESS_MAX_CONCURRENT: Final[int] = 4

DEFAULT_MAILBOX_QUEUE_LIMIT: Final[int] = 64
DEFAULT_MAILBOX_QUEUE_BYTES_LIMIT: Final[int] = 65536
DEFAULT_PENDING_PIN_REQUESTS: Final[int] = 32

# -- Telemetry & Status --
STATUS_FILE_PATH: Final[str] = "/tmp/mcubridge_status.json"
DEFAULT_STATUS_INTERVAL: Final[int] = 5
DEFAULT_BRIDGE_SUMMARY_INTERVAL: Final[int] = 60
DEFAULT_BRIDGE_HANDSHAKE_INTERVAL: Final[int] = 300
DEFAULT_METRICS_HOST: Final[str] = "127.0.0.1"
BRIDGE_SNAPSHOT_EXPIRY_SECONDS: Final[int] = 30

DEFAULT_METRICS_ENABLED: Final[bool] = False

# -- Logging --
DEFAULT_DEBUG: Final[bool] = False

# -- Security --
MIN_SERIAL_SHARED_SECRET_LEN: Final[int] = 8
# SECURITY WARNING: This default secret is for initial setup only.
# It MUST be rotated using 'mcubridge-rotate-credentials' before production use.
DEFAULT_SERIAL_SHARED_SECRET: Final[bytes] = b"failsafe_secret_mode"
ALLOWED_COMMAND_WILDCARD: Final[str] = "*"
TOPIC_FORBIDDEN_REASON: Final[str] = "topic-action-forbidden"

# -- Watchdog --
WATCHDOG_TRIGGER_TOKEN: Final[bytes] = b"WATCHDOG=trigger\n"
DEFAULT_WATCHDOG_ENABLED: Final[bool] = False
DEFAULT_WATCHDOG_INTERVAL: Final[float] = 10.0
WATCHDOG_MIN_INTERVAL: Final[float] = 0.5

# -- Task Supervisor --
SUPERVISOR_DEFAULT_RESTART_INTERVAL: Final[float] = 60.0
SUPERVISOR_DEFAULT_MIN_BACKOFF: Final[float] = 1.0
SUPERVISOR_DEFAULT_MAX_BACKOFF: Final[float] = 30.0
# Specific intervals for non-critical tasks (status-writer, metrics, snapshots)
SUPERVISOR_STATUS_RESTART_INTERVAL: Final[float] = 120.0
SUPERVISOR_PROMETHEUS_RESTART_INTERVAL: Final[float] = 300.0
SUPERVISOR_STATUS_MAX_BACKOFF: Final[float] = 10.0
SUPERVISOR_MIN_RESTART_WINDOW: Final[float] = 1.0

# -- Feature Flags --
DEFAULT_CLOUD_TLS_INSECURE: Final[bool] = False
DEFAULT_ALLOW_NON_TMP_PATHS: Final[bool] = False

# -- Cloud HTTP/3 Defaults --
DEFAULT_CLOUD_HTTP3_PORT: Final[int] = 8443
DEFAULT_CLOUD_HTTP3_CONGESTION_CONTROL: Final[str] = "bbr"

# -- Telemetry and Metadata Constants --
PROP_KEY_BRIDGE_SPOOL: Final[str] = "bridge-spool"
PROP_KEY_BRIDGE_FILES: Final[str] = "bridge-files"
PROP_KEY_WATCHDOG_ENABLED: Final[str] = "bridge-watchdog-enabled"
PROP_KEY_WATCHDOG_INTERVAL: Final[str] = "bridge-watchdog-interval"
PROP_KEY_BRIDGE_ERROR: Final[str] = "bridge-error"
PROP_KEY_BRIDGE_PIN: Final[str] = "bridge-pin"
PROP_KEY_BRIDGE_STATUS: Final[str] = "bridge-status"
PROP_KEY_BRIDGE_DATASTORE_KEY: Final[str] = "bridge-datastore-key"
PROP_KEY_BRIDGE_EVENT: Final[str] = "bridge-event"
PROP_KEY_BRIDGE_SNAPSHOT: Final[str] = "bridge-snapshot"
PROP_KEY_BRIDGE_REQUEST_TOPIC: Final[str] = "bridge-request-topic"
PROP_KEY_BRIDGE_SNAPSHOTS: Final[str] = "bridge-snapshots"

PROP_VAL_UNKNOWN: Final[str] = "unknown"
PROP_VAL_QUOTA_BLOCKED: Final[str] = "quota-blocked"
PROP_VAL_WRITE_LIMIT: Final[str] = "write-limit"
PROP_VAL_ENABLED_TRUE: Final[str] = "1"
PROP_VAL_ENABLED_FALSE: Final[str] = "0"


# -- Async Control and Process Timeouts (Seconds) --
DEFAULT_SYNC_TIMEOUT_SECONDS: Final[float] = float(protocol.SYNC_TIMEOUT_MS) / 1000.0
STREAM_POLL_TIMEOUT_SECONDS: Final[float] = 0.01
PROCESS_TERM_GRACE_PERIOD_SECONDS: Final[float] = 0.5
FLOW_CONTROL_WAIT_TIMEOUT_SECONDS: Final[float] = 30.0

# ==============================================================================
# STATUS CODES (Application Logic)
# ==============================================================================

SERIAL_FAILURE_STATUS_CODES: Final[frozenset[int]] = frozenset(
    {
        protocol.Status.ERROR.value,
        protocol.Status.CMD_UNKNOWN.value,
        protocol.Status.MALFORMED.value,
        protocol.Status.CRC_MISMATCH.value,
        protocol.Status.TIMEOUT.value,
        protocol.Status.NOT_IMPLEMENTED.value,
    }
)
SERIAL_SUCCESS_STATUS_CODES: Final[frozenset[int]] = frozenset({protocol.Status.OK.value})
