"""Auto-generated protocol bindings. Do not edit manually.

Generated by tools/protocol/generate.py from tools/protocol/spec.toml.
"""

from __future__ import annotations

import struct
from enum import IntEnum
from typing import Final

# This file is part of Arduino Yun Ecosystem v2.
#
# Copyright (C) 2025 Ignacio Santolin and contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

PROTOCOL_VERSION: Final[int] = 0x02
MAX_PAYLOAD_SIZE: Final[int] = 256
RPC_BUFFER_SIZE: Final[int] = 256

CRC_COVERED_HEADER_FORMAT: str = ">BHH"
CRC_COVERED_HEADER_SIZE: int = struct.calcsize(
    CRC_COVERED_HEADER_FORMAT
)

CRC_FORMAT: str = ">I"
CRC_SIZE: int = struct.calcsize(CRC_FORMAT)

MIN_FRAME_SIZE: int = CRC_COVERED_HEADER_SIZE + CRC_SIZE

DATASTORE_KEY_LEN_FORMAT: str = ">B"
DATASTORE_KEY_LEN_SIZE: int = struct.calcsize(
    DATASTORE_KEY_LEN_FORMAT
)

DATASTORE_VALUE_LEN_FORMAT: str = ">B"
DATASTORE_VALUE_LEN_SIZE: int = struct.calcsize(
    DATASTORE_VALUE_LEN_FORMAT
)


class Status(IntEnum):
    """Status codes shared between MCU and MPU."""
    OK = 0x00  # Operation completed successfully.
    ERROR = 0x01  # Generic failure.
    CMD_UNKNOWN = 0x02  # Command not recognized.
    MALFORMED = 0x03  # Payload had invalid structure.
    CRC_MISMATCH = 0x04  # CRC check failed.
    TIMEOUT = 0x05  # Operation timed out.
    NOT_IMPLEMENTED = 0x06  # Command defined but not supported.
    ACK = 0x07  # Generic acknowledgement for fire-and-forget commands.


class Command(IntEnum):
    """Command identifiers shared between MCU and MPU."""
    CMD_GET_VERSION = 0x00
    CMD_GET_VERSION_RESP = 0x80
    CMD_GET_FREE_MEMORY = 0x01
    CMD_GET_FREE_MEMORY_RESP = 0x82
    CMD_LINK_SYNC = 0x02
    CMD_LINK_SYNC_RESP = 0x83
    CMD_LINK_RESET = 0x03
    CMD_LINK_RESET_RESP = 0x84
    CMD_XOFF = 0x08
    CMD_XON = 0x09
    CMD_SET_PIN_MODE = 0x10
    CMD_DIGITAL_WRITE = 0x11
    CMD_ANALOG_WRITE = 0x12
    CMD_DIGITAL_READ = 0x13
    CMD_ANALOG_READ = 0x14
    CMD_DIGITAL_READ_RESP = 0x15
    CMD_ANALOG_READ_RESP = 0x16
    CMD_CONSOLE_WRITE = 0x20
    CMD_DATASTORE_PUT = 0x30
    CMD_DATASTORE_GET = 0x31
    CMD_DATASTORE_GET_RESP = 0x81
    CMD_MAILBOX_READ = 0x40
    CMD_MAILBOX_PROCESSED = 0x41
    CMD_MAILBOX_AVAILABLE = 0x42
    CMD_MAILBOX_PUSH = 0x43
    CMD_MAILBOX_READ_RESP = 0x90
    CMD_MAILBOX_AVAILABLE_RESP = 0x92
    CMD_FILE_WRITE = 0x50
    CMD_FILE_READ = 0x51
    CMD_FILE_REMOVE = 0x52
    CMD_FILE_READ_RESP = 0xA1
    CMD_PROCESS_RUN = 0x60
    CMD_PROCESS_RUN_ASYNC = 0x61
    CMD_PROCESS_POLL = 0x62
    CMD_PROCESS_KILL = 0x63
    CMD_PROCESS_RUN_RESP = 0xB0
    CMD_PROCESS_RUN_ASYNC_RESP = 0xB1
    CMD_PROCESS_POLL_RESP = 0xB2
