from typing import Any, Tuple, Optional, Protocol
import asyncio

class SerialException(Exception): ...

class Serial:
    def read(self, size: int = ...) -> bytes: ...
    def write(self, data: bytes) -> int: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    @property
    def baudrate(self) -> int: ...
    @baudrate.setter
    def baudrate(self, value: int) -> None: ...

def serial_for_url(
    url: str, baudrate: int = ..., timeout: Optional[float] = ..., **kwargs: Any
) -> Serial: ...

class BaseSerialTransport(Protocol):
    def close(self) -> None: ...
    @property
    def serial(self) -> Any: ...

async def open_serial_connection(
    url: str, baudrate: int, xonxoff: bool = ...
) -> Tuple[asyncio.StreamReader, asyncio.StreamWriter]: ...

def async_serial_for_url(
    url: str, baudrate: int, xonxoff: bool = ...
) -> Any: ...
