from typing import Any, Tuple, Optional, Protocol
import asyncio

class SerialException(Exception): ...

class BaseSerialTransport(Protocol):
    def close(self) -> None: ...
    @property
    def serial(self) -> Any: ...

async def open_serial_connection(
    url: str, baudrate: int, xonxoff: bool = ...
) -> Tuple[asyncio.StreamReader, asyncio.StreamWriter]: ...

def async_serial_for_url(
    url: str, baudrate: int, xonxoff: bool = ...
) -> Any: ...
