"""
This type stub file was generated by pyright.
"""

import asyncio
from collections.abc import Callable, Iterable
from typing import Any, Generic, TypeVar
from typing_extensions import Self
from .common import BaseSerialTransport, ModemPins, Parity, PinState, StopBits

"""Asynchronous serial port support."""
LOGGER = ...
_T = TypeVar("_T", bound=asyncio.WriteTransport)
class SerialStreamWriter(asyncio.StreamWriter, Generic[_T]):
    """StreamWriter with properly typed transport."""
    @property
    def transport(self) -> _T:
        """Return the underlying transport."""
        ...
    


class AsyncSerial:
    """Async serial port with a sync-style API."""
    def __init__(self, url: str | None, *, transport_cls: type[BaseSerialTransport] | None = ..., **kwargs: Any) -> None:
        """Initialize an unopened serial port.

        Directly creating this class is not recommended; use `async_serial_for_url`
        instead.
        """
        ...
    
    async def open(self) -> None:
        """Open the serial port connection."""
        ...
    
    async def close(self) -> None:
        """Close the connection and wait until the port is fully closed."""
        ...
    
    def schedule_close(self) -> None:
        """Signal a graceful close without waiting for it to finish."""
        ...
    
    def abort(self) -> None:
        """Drop pending writes and close immediately, without waiting."""
        ...
    
    async def wait_closed(self) -> None:
        """Wait until a previously-scheduled close or abort has finished."""
        ...
    
    @property
    def is_open(self) -> bool:
        """Whether the connection is currently open."""
        ...
    
    async def __aenter__(self) -> Self:
        """Open the connection and return self."""
        ...
    
    async def __aexit__(self, *exc: object) -> None:
        """Close the connection and wait until it's fully closed."""
        ...
    
    def __repr__(self) -> str:
        """Return a debug representation."""
        ...
    
    async def read(self, n: int = ...) -> bytes:
        """Read up to `n` bytes (or until EOF if `n` is -1)."""
        ...
    
    async def readexactly(self, n: int) -> bytes:
        """Read exactly `n` bytes."""
        ...
    
    async def readuntil(self, separator: bytes = ...) -> bytes:
        """Read up to and including `separator`."""
        ...
    
    async def readline(self) -> bytes:
        """Read until the next newline."""
        ...
    
    async def write(self, data: bytes | bytearray | memoryview) -> None:
        """Queue data for writing and wait for the application buffer to drain."""
        ...
    
    async def writelines(self, data: Iterable[bytes | bytearray | memoryview]) -> None:
        """Queue buffers for writing and wait for the application buffer to drain."""
        ...
    
    def write_nowait(self, data: bytes | bytearray | memoryview) -> None:
        """Queue data for writing without waiting; pair with `drain()` to batch."""
        ...
    
    def writelines_nowait(self, data: Iterable[bytes | bytearray | memoryview]) -> None:
        """Queue buffers for writing without waiting; pair with `drain()` to batch."""
        ...
    
    async def drain(self) -> None:
        """Wait until the application-level write buffer can accept more data."""
        ...
    
    async def flush(self) -> None:
        """Drain app-level buffer, then wait for the OS-level buffer to flush."""
        ...
    
    @property
    def transport(self) -> BaseSerialTransport:
        """Return the underlying serial transport."""
        ...
    
    async def get_modem_pins(self) -> ModemPins:
        """Get modem control pins."""
        ...
    
    async def set_modem_pins(self, modem_pins: ModemPins | None = ..., *, le: PinState | bool | None = ..., dtr: PinState | bool | None = ..., rts: PinState | bool | None = ..., st: PinState | bool | None = ..., sr: PinState | bool | None = ..., cts: PinState | bool | None = ..., car: PinState | bool | None = ..., rng: PinState | bool | None = ..., dsr: PinState | bool | None = ...) -> None:
        """Set modem control pins."""
        ...
    
    @property
    def baudrate(self) -> int:
        """Get the baud rate."""
        ...
    
    @property
    def parity(self) -> Parity:
        """Get the parity."""
        ...
    
    @property
    def stopbits(self) -> StopBits:
        """Get the number of stop bits."""
        ...
    
    @property
    def byte_size(self) -> int:
        """Get the byte size."""
        ...
    
    @property
    def exclusive(self) -> bool:
        """Get the exclusive setting."""
        ...
    


async def create_serial_connection(loop: asyncio.AbstractEventLoop, protocol_factory: Callable[[], asyncio.Protocol], url: str | None, baudrate: int, parity: Parity = ..., stopbits: StopBits = ..., xonxoff: bool = ..., rtscts: bool = ..., exclusive: bool = ..., *, transport_cls: type[BaseSerialTransport] | None = ..., **kwargs: Any) -> tuple[BaseSerialTransport, asyncio.Protocol]:
    """Create a serial port connection with asyncio."""
    ...

async def open_serial_connection(*args: Any, **kwargs: Any) -> tuple[asyncio.StreamReader, SerialStreamWriter[BaseSerialTransport]]:
    """Open a serial port connection using StreamReader and StreamWriter."""
    ...

def async_serial_for_url(url: str | None, *, transport_cls: type[BaseSerialTransport] | None = ..., **kwargs: Any) -> AsyncSerial:
    """Build an unopened AsyncSerial. Use `async with` or `await serial.open()`."""
    ...

