"""
This type stub file was generated by pyright.
"""

import asyncio
import dataclasses
import io
from abc import abstractmethod
from collections import defaultdict
from collections.abc import Awaitable, Callable, Iterator
from contextlib import contextmanager
from enum import Enum
from pathlib import Path
from types import TracebackType
from typing import Any, Concatenate, NamedTuple, ParamSpec, TypeVar
from typing_extensions import Buffer, Self, TypedDict, Unpack

"""Serial port communication utilities."""
class Platform(str, Enum):
    """Built-in platform name."""
    DEVICE = ...
    POSIX = ...
    EXTENDED_POSIX = ...
    FREEBSD = ...
    LINUX = ...
    DARWIN = ...
    WIN32 = ...
    SOCKET = ...
    RFC2217 = ...
    ESPHOME = ...


@dataclasses.dataclass(frozen=True)
class RegisteredUriHandler:
    """A URI handler registration entry."""
    scheme: str
    unique_scheme: str
    weight: int
    sync_cls: type[BaseSerial]
    async_transport_cls: type[BaseSerialTransport]
    list_serial_ports_func: Callable[..., list[SerialPortInfo]]
    async_list_serial_ports_func: Callable[..., Awaitable[list[SerialPortInfo]]]
    strip_uri_scheme: bool
    ...


class _RegistryEntry(NamedTuple):
    """Entry in `_REGISTERED_URI_HANDLERS`, ordered by (weight, insertion_time)."""
    weight: int
    insertion_time: float
    handler: RegisteredUriHandler
    ...


_REGISTERED_URI_HANDLERS: defaultdict[str, list[_RegistryEntry]] = ...
def empty_port_list(*args: Any, **kwargs: Any) -> list[SerialPortInfo]:
    """Return an empty list of serial ports."""
    ...

async def async_empty_port_list(*args: Any, **kwargs: Any) -> list[SerialPortInfo]:
    """Return an empty list of serial ports, async."""
    ...

def register_uri_handler(*, scheme: str, unique_scheme: str, sync_cls: type[BaseSerial], async_transport_cls: type[BaseSerialTransport], list_serial_ports_func: Callable[..., list[SerialPortInfo]] = ..., async_list_serial_ports_func: Callable[..., Awaitable[list[SerialPortInfo]]] = ..., weight: int = ..., strip_uri_scheme: bool = ...) -> Callable[[], None]:
    """Register a URI handler.

    Expose a new backend to ``serial_for_url`` / ``create_serial_connection`` /
    ``open_serial_connection``.

    Args:
        scheme: Shared dispatch scheme. URLs with this scheme resolve to the
            highest-weight handler registered under it.
        unique_scheme: A scheme that uniquely identifies this handler. Must end
            with ``://`` and must not collide with an existing registration.
            Use this to address the handler directly.
        sync_cls: Synchronous serial class, typically a subclass of
            :class:`BaseSerial`.
        async_transport_cls: Async transport class, typically a subclass of
            :class:`BaseSerialTransport`.
        list_serial_ports_func: Callable returning a list of :class:`SerialPortInfo`.
        async_list_serial_ports_func: Async callable returning a list of
            :class:`SerialPortInfo`.
        weight: Dispatch priority under ``scheme``. Higher wins.
        strip_uri_scheme: If ``True``, the leading ``scheme`` / ``unique_scheme``
            is removed before the URL is passed to the sync class. Set this when
            the underlying class expects a bare device path rather than a URL.

    Returns:
        A callable that unregisters the handler.

    Raises:
        ValueError: if either scheme doesn't end with ``://`` or ``unique_scheme``
            is already registered.

    """
    ...

def get_uri_handler(uri: str) -> RegisteredUriHandler:
    """Look up the registered handler for the given URI."""
    ...

class SerialException(Exception):
    """Base serial exception."""
    ...


class UnsupportedSetting(SerialException):
    """Raised when an unsupported serial port setting is used."""
    ...


class UnknownUriScheme(SerialException):
    """Raised when a URI scheme has no registered handler."""
    ...


class StopBits(float, Enum):
    """Stop bits configuration."""
    ONE = ...
    ONE_POINT_FIVE = ...
    TWO = ...


class Parity(str, Enum):
    """Parity configuration."""
    NONE = ...
    ODD = ...
    EVEN = ...
    MARK = ...
    SPACE = ...


class ConnectKwargs(TypedDict, total=False, extra_items=Any):
    """Kwargs forwarded to BaseSerialTransport.connect / _connect."""
    baudrate: int
    parity: Parity
    stopbits: StopBits
    xonxoff: bool
    rtscts: bool
    exclusive: bool
    byte_size: int
    ...


class PinState(Enum):
    """Pin state."""
    UNDEFINED = ...
    LOW = ...
    HIGH = ...
    @classmethod
    def convert(cls, value: PinState | bool | None) -> PinState:
        """Create PinState from boolean."""
        ...
    
    def to_bool(self) -> bool | None:
        """Convert PinState to boolean."""
        ...
    


@dataclasses.dataclass(frozen=True)
class ModemPins:
    """Modem control bits."""
    le: PinState = ...
    dtr: PinState = ...
    rts: PinState = ...
    st: PinState = ...
    sr: PinState = ...
    cts: PinState = ...
    car: PinState = ...
    rng: PinState = ...
    dsr: PinState = ...
    def __repr__(self) -> str:
        """Return string representation of modem pins."""
        ...
    


@contextmanager
def measure_time() -> Iterator[Callable[[], float]]:
    """Measure elapsed time in a context."""
    ...

_P = ParamSpec("_P")
_R = TypeVar("_R")
def maybe_wrap_exceptions(func: Callable[Concatenate[BaseSerial, _P], _R]) -> Callable[Concatenate[BaseSerial, _P], _R]:
    """Re-raise all exceptions as `SerialException` when the flag is set."""
    ...

class BaseSerial(io.RawIOBase):
    """Base class for serial port communication."""
    def __init__(self, path: str | Path | None = ..., baudrate: int = ..., *, parity: Parity | str | None = ..., stopbits: StopBits | int | float = ..., xonxoff: bool = ..., rtscts: bool = ..., dsrdtr: bool = ..., byte_size: int = ..., read_timeout: float | None = ..., write_timeout: float | None = ..., rtsdtr_on_open: PinState = ..., rtsdtr_on_close: PinState = ..., exclusive: bool = ..., port: str | None = ..., timeout: float | None = ..., bytesize: int | None = ..., do_not_open: bool | None = ..., writeTimeout: float | None = ..., inter_byte_timeout: int | None = ..., _wrap_exceptions: bool = ...) -> None:
        """Initialize serial port configuration."""
        ...
    
    @classmethod
    def from_url(cls, url: str, *args: Any, **kwargs: Any) -> BaseSerial:
        """Create the appropriate serial port subclass for the given URL."""
        ...
    
    @maybe_wrap_exceptions
    def open(self) -> None:
        """Open the serial port."""
        ...
    
    @maybe_wrap_exceptions
    def configure_port(self) -> None:
        """Configure the serial port settings."""
        ...
    
    @maybe_wrap_exceptions
    def close(self) -> None:
        """Close the serial port."""
        ...
    
    @property
    def read_timeout(self) -> float | None:
        """Get the read timeout in seconds."""
        ...
    
    @property
    def write_timeout(self) -> float | None:
        """Get the write timeout in seconds."""
        ...
    
    @maybe_wrap_exceptions
    def get_modem_pins(self) -> ModemPins:
        """Get modem control bits."""
        ...
    
    @maybe_wrap_exceptions
    def set_modem_pins(self, modem_pins: ModemPins | None = ..., *, le: PinState | bool | None = ..., dtr: PinState | bool | None = ..., rts: PinState | bool | None = ..., st: PinState | bool | None = ..., sr: PinState | bool | None = ..., cts: PinState | bool | None = ..., car: PinState | bool | None = ..., rng: PinState | bool | None = ..., dsr: PinState | bool | None = ...) -> None:
        """Set modem control bits."""
        ...
    
    @maybe_wrap_exceptions
    def readinto(self, b: Buffer, *, timeout: float | None = ...) -> int:
        """Read bytes from serial port into buffer."""
        ...
    
    @maybe_wrap_exceptions
    def write(self, data: Buffer, *, timeout: float | None = ...) -> int:
        """Write bytes to serial port."""
        ...
    
    def flush(self) -> None:
        """Flush write buffers."""
        ...
    
    @property
    def path(self) -> str | Path | None:
        """Get the serial port path."""
        ...
    
    @property
    def baudrate(self) -> int:
        """Get the baud rate."""
        ...
    
    @baudrate.setter
    def baudrate(self, value: int) -> None:
        """Set baud rate (deprecated)."""
        ...
    
    @property
    def parity(self) -> Parity:
        """Get the parity."""
        ...
    
    @property
    def byte_size(self) -> int:
        """Get the byte size."""
        ...
    
    @property
    def stopbits(self) -> StopBits:
        """Get the number of stop bits."""
        ...
    
    @property
    def rtsdtr_on_open(self) -> PinState:
        """Get the RTS/DTR pin state (on open) setting."""
        ...
    
    @property
    def rtsdtr_on_close(self) -> PinState:
        """Get the RTS/DTR pin state (on close) setting."""
        ...
    
    @property
    def exclusive(self) -> bool:
        """Get the exclusive setting."""
        ...
    
    def readexactly(self, n: int, *, timeout: float | None = ...) -> bytes:
        """Read exactly n bytes."""
        ...
    
    def read_until(self, expected: bytes = ..., size: int | None = ..., *, timeout: float | None = ...) -> bytes:
        """Read until the expected sequence is found."""
        ...
    
    def __enter__(self) -> Self:
        """Enter context manager."""
        ...
    
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None:
        """Exit context manager."""
        ...
    
    def __del__(self) -> None:
        """Cleanup on deletion."""
        ...
    
    @abstractmethod
    def num_unread_bytes(self) -> int:
        """Return the number of bytes waiting to be read."""
        ...
    
    @abstractmethod
    def num_unwritten_bytes(self) -> int:
        """Return the number of bytes waiting to be written."""
        ...
    
    @maybe_wrap_exceptions
    def reset_read_buffer(self) -> None:
        """Reset the read buffer."""
        ...
    
    @maybe_wrap_exceptions
    def reset_write_buffer(self) -> None:
        """Reset the write buffer."""
        ...
    
    @property
    @abstractmethod
    def is_open(self) -> bool:
        """Return whether the serial port is open."""
        ...
    
    @property
    def port(self) -> str | None:
        """Deprecated alias for `path`.

        Warning:
            Deprecated, use `path` instead.

        """
        ...
    
    @property
    def portstr(self) -> str | None:
        """Deprecated alias for `path`.

        Warning:
            Deprecated, use `path` instead.

        """
        ...
    
    @property
    def timeout(self) -> float | None:
        """Deprecated alias for `read_timeout`.

        Warning:
            Deprecated, use `read_timeout` instead.

        """
        ...
    
    @timeout.setter
    def timeout(self, value: float) -> None:
        ...
    
    @property
    def bytesize(self) -> int:
        """Deprecated alias for `byte_size`.

        Warning:
            Deprecated, use `byte_size` instead.

        """
        ...
    
    @property
    def data_bits(self) -> int:
        """Deprecated alias for `byte_size`.

        Warning:
            Deprecated, use `byte_size` instead.

        """
        ...
    
    @data_bits.setter
    def data_bits(self, value: int) -> None:
        """Set the byte size (deprecated)."""
        ...
    
    @property
    def stop_bits(self) -> int | float:
        """Deprecated alias for `stopbits`.

        Warning:
            Deprecated, use `stopbits` instead.

        """
        ...
    
    @stop_bits.setter
    def stop_bits(self, value: int | float) -> None:
        """Set the number of stop bits (deprecated)."""
        ...
    
    @property
    def writeTimeout(self) -> float | None:
        """Deprecated alias for `write_timeout`.

        Warning:
            Deprecated, use `write_timeout` instead.

        """
        ...
    
    def reset_input_buffer(self) -> None:
        """Reset the read buffer.

        Warning:
            Deprecated, use `reset_read_buffer` instead.

        """
        ...
    
    def reset_output_buffer(self) -> None:
        """Reset the write buffer.

        Warning:
            Deprecated, use `reset_write_buffer` instead.

        """
        ...
    
    def flushInput(self) -> None:
        """Reset the read buffer.

        Warning:
            Deprecated, use `reset_read_buffer` instead.

        """
        ...
    
    def flushOutput(self) -> None:
        """Reset the write buffer.

        Warning:
            Deprecated, use `reset_write_buffer` instead.

        """
        ...
    
    @property
    def in_waiting(self) -> int:
        """Deprecated alias for `num_unread_bytes`.

        Warning:
            Deprecated, use `num_unread_bytes` instead.

        """
        ...
    
    @property
    def out_waiting(self) -> int:
        """Deprecated alias for `num_unwritten_bytes`.

        Warning:
            Deprecated, use `num_unwritten_bytes` instead.

        """
        ...
    
    @property
    def inWaiting(self) -> int:
        """Deprecated alias for `num_unread_bytes`.

        Warning:
            Deprecated, use `num_unread_bytes` instead.

        """
        ...
    
    def isOpen(self) -> bool:
        """Return whether the serial port is open.

        Warning:
            Deprecated, use `is_open` instead.

        """
        ...
    
    @property
    def dtr(self) -> bool | None:
        """Get DTR modem bit."""
        ...
    
    @dtr.setter
    def dtr(self, value: bool) -> None:
        """Set DTR modem bit."""
        ...
    
    @property
    def rts(self) -> bool | None:
        """Get RTS modem bit."""
        ...
    
    @rts.setter
    def rts(self, value: bool) -> None:
        """Set RTS modem bit."""
        ...
    
    @property
    def cts(self) -> bool | None:
        """Get CTS modem bit."""
        ...
    
    @cts.setter
    def cts(self, value: bool) -> None:
        """Set CTS modem bit."""
        ...
    


class BaseSerialTransport(asyncio.Transport):
    """Base class for serial port asyncio transport."""
    transport_name = ...
    def __init__(self, loop: asyncio.AbstractEventLoop, protocol: asyncio.Protocol) -> None:
        """Initialize serial transport."""
        ...
    
    def is_closing(self) -> bool:
        """Return whether the transport is closing."""
        ...
    
    def get_protocol(self) -> asyncio.Protocol:
        """Get the protocol used by this transport."""
        ...
    
    def set_protocol(self, protocol: asyncio.Protocol) -> None:
        """Set the protocol to use with this transport."""
        ...
    
    @property
    def serial(self) -> BaseSerial:
        """Get the serial port instance."""
        ...
    
    @property
    def baudrate(self) -> int:
        """Get the baud rate."""
        ...
    
    @property
    def parity(self) -> Parity:
        """Get the parity."""
        ...
    
    @property
    def stopbits(self) -> StopBits:
        """Get the number of stop bits."""
        ...
    
    @property
    def byte_size(self) -> int:
        """Get the byte size."""
        ...
    
    @property
    def exclusive(self) -> bool:
        """Get the exclusive setting."""
        ...
    
    async def connect(self, *, path: str | None, **kwargs: Unpack[ConnectKwargs]) -> None:
        """Connect to serial port."""
        ...
    
    async def get_modem_pins(self) -> ModemPins:
        """Get modem control bits."""
        ...
    
    async def set_modem_pins(self, modem_pins: ModemPins | None = ..., *, le: PinState | bool | None = ..., dtr: PinState | bool | None = ..., rts: PinState | bool | None = ..., st: PinState | bool | None = ..., sr: PinState | bool | None = ..., cts: PinState | bool | None = ..., car: PinState | bool | None = ..., rng: PinState | bool | None = ..., dsr: PinState | bool | None = ...) -> None:
        """Set modem control bits."""
        ...
    
    async def flush(self) -> None:
        """Flush write buffers, waiting until all data is written."""
        ...
    
    async def wait_closed(self) -> None:
        """Wait until transport is fully closed."""
        ...
    


def get_serial_classes(url: str) -> tuple[type[BaseSerial], type[BaseSerialTransport]]:
    """Get the appropriate serial and transport classes based on the URL scheme."""
    ...

@dataclasses.dataclass
class SerialPortInfo:
    """A serial port."""
    device: str
    resolved_device: str
    vid: int | None
    pid: int | None
    serial_number: str | None
    manufacturer: str | None
    product: str | None
    bcd_device: int | None
    interface_description: str | None
    interface_num: int | None
    def __getitem__(self, key: int | slice) -> str | None:
        """Compatibility shim for `serial.tools.list_ports_common.ListPortInfo`."""
        ...
    
    @property
    def description(self) -> str:
        """Description of the device.

        Warning:
            Deprecated, this description is unstable and will change in the future.

        """
        ...
    


def list_serial_ports(platform: Platform | str = ..., **kwargs: Any) -> list[SerialPortInfo]:
    """List serial ports, defaulting to the system platform."""
    ...

async def async_list_serial_ports(platform: Platform | str = ..., **kwargs: Any) -> list[SerialPortInfo]:
    """List serial ports (async), defaulting to the system platform."""
    ...

def serial_for_url(url: str, *args: Any, **kwargs: Any) -> BaseSerial:
    """Create the appropriate serial port subclass for the given URL."""
    ...

