"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import Any
from .common import BaseSerialTransport

"""File descriptor-based asyncio transport."""
LOGGER = ...
LOG_THRESHOLD_FOR_CONNLOST_WRITES = ...
_BACKGROUND_TASKS: set[asyncio.Task[None]] = ...
class DescriptorTransport(BaseSerialTransport):
    """File descriptor transport using asyncio."""
    max_size = ...
    transport_name = ...
    def __init__(self, loop: asyncio.AbstractEventLoop, protocol: asyncio.Protocol, extra: dict[str, Any] | None = ...) -> None:
        """Initialize the descriptor transport."""
        ...
    
    def pause_reading(self) -> None:
        """Pause reading from the file descriptor."""
        ...
    
    def resume_reading(self) -> None:
        """Resume reading from the file descriptor."""
        ...
    
    def get_write_buffer_limits(self) -> tuple[int, int]:
        """Get the write buffer low and high water limits."""
        ...
    
    def set_write_buffer_limits(self, high: int | None = ..., low: int | None = ...) -> None:
        """Set the write buffer low and high water limits."""
        ...
    
    def get_write_buffer_size(self) -> int:
        """Get the number of bytes currently in the write buffer."""
        ...
    
    def write(self, data: bytes | bytearray | memoryview) -> None:
        """Write data to the file descriptor."""
        ...
    
    def can_write_eof(self) -> bool:
        """Check if EOF can be written."""
        ...
    
    def write_eof(self) -> None:
        """Write EOF to the file descriptor."""
        ...
    
    def close(self) -> None:
        """Close the transport."""
        ...
    
    def __del__(self) -> None:
        """Clean up transport on deletion."""
        ...
    
    def abort(self) -> None:
        """Abort the transport immediately."""
        ...
    


