"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

"""Centralized access to optional Rust extensions."""
if TYPE_CHECKING:
    ...
LOGGER = ...
__all__ = ["list_serial_ports_impl"]
