"""Manual stub for OpenWrt UCI."""

from __future__ import annotations
from types import TracebackType
from typing import Any, overload

class Uci:
    def __init__(self) -> None: ...
    def __enter__(self) -> Uci: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> bool: ...
    @overload
    def get_all(self, package: str) -> dict[str, dict[str, Any]]: ...
    @overload
    def get_all(self, package: str, section: str) -> dict[str, Any]: ...
    def get(self, package: str, section: str, option: str) -> str: ...
    def set(self, package: str, section: str, option: str, value: str) -> None: ...
    def commit(self, package: str) -> None: ...

class UciException(Exception): ...
