"""
This type stub file was generated by pyright.
"""

import asyncio
import errno
import logging
import sys
from collections.abc import Generator
from contextlib import suppress
from enum import IntEnum
from asyncio import timeout as asyncio_timeout
from typing import Any, overload
from typing_extensions import Buffer, Unpack
from ...common import BaseSerialTransport, ConnectKwargs, ModemPins, Parity, PinState, SerialException, StopBits, UnsupportedSetting, measure_time, register_uri_handler
from ..serial_socket import SocketSerial
from .types import CMD_ID_TO_CLASS, ControlCmdId, DoCmd, DontCmd, LineStateFlag, ModemStateFlag, NotifyLinestateCmd, NotifyModemstateCmd, PurgeDataCmd, PurgeDataValue, Rfc2217CmdId, Rfc2217Command, Rfc2217Parity, Rfc2217StopSize, SetBaudrateCmd, SetControlCmd, SetDatasizeCmd, SetLinestateMaskCmd, SetModemstateMaskCmd, SetParityCmd, SetStopsizeCmd, TelnetCmdId, TelnetCommand, TelnetOption, WillCmd, WontCmd, encode_command, iac_escape

"""RFC 2217 (Telnet Com Port Control) implementation."""
if sys.version_info >= (3, 11):
    ...
else:
    ...
LOGGER = ...
RFC2217_PARITY_MAP = ...
RFC2217_STOPBITS_MAP = ...
OPTION_CMD_TO_TYPE: dict[int, type[WillCmd | WontCmd | DoCmd | DontCmd]] = ...
class TelnetParserState(IntEnum):
    """States for the telnet protocol parser state machine."""
    NORMAL = ...
    IAC_SEEN = ...
    OPTION_CMD = ...
    SUBNEG_OPTION = ...
    SUBNEG_DATA = ...
    SUBNEG_IAC = ...


class TelnetParser:
    """State machine that separates a telnet byte stream into data and commands."""
    def __init__(self) -> None:
        """Initialize the telnet parser."""
        ...
    
    def feed(self, data: bytes) -> list[bytes | TelnetCommand | Rfc2217Command]:
        """Process raw bytes and return data chunks and commands."""
        ...
    


class Rfc2217:
    """IO-free RFC2217 protocol engine shared by sync and async wrappers."""
    _ACCEPTED_OPTIONS = ...
    def __init__(self) -> None:
        """Initialize parser state and protocol bookkeeping."""
        ...
    
    @property
    def negotiated(self) -> bool:
        """Return whether COM-PORT-OPTION negotiation has completed."""
        ...
    
    def mark_negotiated(self) -> None:
        """Mark COM-PORT-OPTION negotiation as complete."""
        ...
    
    def reset(self) -> None:
        """Reset parser state and all protocol bookkeeping."""
        ...
    
    def feed(self, data: bytes) -> tuple[bytes, list[TelnetCommand]]:
        """Parse raw bytes, update protocol state, and return data/responses."""
        ...
    
    def pop_matching_telnet(self, expected: list[TelnetCommand]) -> TelnetCommand | None:
        """Pop a pending telnet command matching one of the expected responses."""
        ...
    
    def pop_pending_rfc2217(self, cmd_id: Rfc2217CmdId) -> Rfc2217Command | None:
        """Pop a pending RFC2217 command of the given type, if present."""
        ...
    
    def build_port_config_commands(self, *, baudrate: int, byte_size: int, parity: Parity, stopbits: StopBits, rtscts: bool, xonxoff: bool) -> tuple[Rfc2217Command, ...]:
        """Build the RFC2217 commands needed to configure the remote port."""
        ...
    
    def build_modem_pin_commands(self, modem_pins: ModemPins) -> Generator[SetControlCmd]:
        """Build SET_CONTROL commands needed to apply modem pin changes."""
        ...
    
    def get_modem_pins(self) -> ModemPins:
        """Return modem pin state from the last NOTIFY-MODEMSTATE."""
        ...
    


class RFC2217Serial(SocketSerial):
    """RFC 2217 serial port implementation (Synchronous)."""
    def __init__(self, *args: Any, receive_buffer_size: int = ..., connect_timeout: float = ..., **kwargs: Any) -> None:
        """Initialize the RFC 2217 serial port."""
        ...
    
    def num_unread_bytes(self) -> int:
        """Return the number of buffered serial data bytes waiting to be read."""
        ...
    


class _RFC2217ProxyProtocol(asyncio.Protocol):
    """Bridge protocol between asyncio TCP transport and RFC2217SerialTransport."""
    def __init__(self, serial_transport: RFC2217SerialTransport) -> None:
        """Initialize the proxy protocol."""
        ...
    
    def data_received(self, data: bytes) -> None:
        """Forward received data to the serial transport for parsing."""
        ...
    
    def pause_writing(self) -> None:
        """Propagate backpressure from TCP transport to serial protocol."""
        ...
    
    def resume_writing(self) -> None:
        """Propagate resume signal from TCP transport to serial protocol."""
        ...
    
    def connection_lost(self, exc: Exception | None) -> None:
        """Handle TCP connection loss."""
        ...
    


class RFC2217SerialTransport(BaseSerialTransport):
    """Async RFC 2217 serial transport over TCP."""
    transport_name = ...
    _serial: RFC2217Serial | None
    def __init__(self, loop: asyncio.AbstractEventLoop, protocol: asyncio.Protocol) -> None:
        """Initialize the RFC 2217 serial transport."""
        ...
    
    def write(self, data: bytes | bytearray | memoryview) -> None:
        """Write data to the serial port, escaping IAC bytes."""
        ...
    
    def pause_reading(self) -> None:
        """Pause reading from the TCP transport."""
        ...
    
    def resume_reading(self) -> None:
        """Resume reading from the TCP transport."""
        ...
    
    def close(self) -> None:
        """Close the transport, draining buffered writes to the server first."""
        ...
    
    def abort(self) -> None:
        """Abort the transport immediately."""
        ...
    
    def get_write_buffer_size(self) -> int:
        """Get the number of bytes currently in the write buffer."""
        ...
    
    def get_write_buffer_limits(self) -> tuple[int, int]:
        """Get the write buffer low and high water marks."""
        ...
    
    def set_write_buffer_limits(self, high: int | None = ..., low: int | None = ...) -> None:
        """Set the write buffer low and high water marks."""
        ...
    
    def can_write_eof(self) -> bool:
        """Return whether the underlying TCP transport supports EOF."""
        ...
    


