#!/bin/sh
#
# Copyright (C) 2025 Ignacio Santolin
#
# This script sets up the default configuration for the mcubridge daemon
# on first boot or package install.
#

uci -q batch <<EOF
delete mcubridge
set mcubridge.daemon=service
set mcubridge.daemon.enabled='1'
set mcubridge.daemon.serial_port='/dev/ttyATH0'
set mcubridge.daemon.serial_baud='115200'
set mcubridge.daemon.mqtt_host='127.0.0.1'
set mcubridge.daemon.mqtt_port='1883'
set mcubridge.daemon.debug_logging='0'
set mcubridge.daemon.status_interval='5.0'

# Security defaults
set mcubridge.security=security
set mcubridge.security.enforce_handshake='1'
set mcubridge.security.shared_secret='CHANGE_ME_IMMEDIATELY'

# Commit
commit mcubridge
EOF

# Ensure the service is enabled in init.d
/etc/init.d/mcubridge enable
