"""
This type stub file was generated by pyright.
"""

from contextlib import suppress
from typing import TYPE_CHECKING
from ..common import BaseSerial as Serial, BaseSerialTransport as SerialTransport, get_uri_handler
from . import serial_rfc2217, serial_socket

"""Individual platform implementations."""
if TYPE_CHECKING:
    ...
else:
    ...
__all__ = ["Serial", "SerialTransport"]
