"""
This type stub file was generated by pyright.
"""

import asyncio
from collections.abc import Callable, Coroutine
from enum import IntFlag
from typing import Any, ParamSpec, TypeVar
from aioesphomeapi.client import APIClient
from serialx import SerialException
from serialx.common import BaseSerial, BaseSerialTransport, SerialPortInfo

"""ESPHome serial proxy transport.

The `ESPHome serial proxy component <https://esphome.io/components/serial_proxy/>`_
exposes any ESPHome serial instance through the ESPHome API. This is used by serialx to
create a fully functional remote serial port, similar to RFC2217 but with many quality
of life, performance, and security improvements.

This platform requires the `aioesphomeapi <https://github.com/esphome/aioesphomeapi>`_
package to be installed, provided by the ``esphome`` dependency group:

.. code-block:: bash

    pip install 'serialx[esphome]'

.. note::
    The aioesphomeapi package does not provide a synchronous interface so the sync
    serial transport relies on spawning an asyncio event loop in a secondary thread in
    order to proxy the async methods. This interface is far from ideal. If you'd like to
    make use of this transport, please migrate your application to the async APIs for
    better compatibility.
"""
_T = TypeVar("_T")
_P = ParamSpec("_P")
LOGGER = ...
ESPHOME_DEFAULT_PORT = ...
PARITY_MAP = ...
STOP_BITS_MAP = ...
class InvalidSettingsError(SerialException):
    """Raised when the provided settings are invalid."""
    ...


def translate_esphome_errors(func: Callable[_P, Coroutine[Any, Any, _T]]) -> Callable[_P, Coroutine[Any, Any, _T]]:
    """Translate aioesphomeapi errors into standard serialx exceptions."""
    ...

class LineStateFlag(IntFlag):
    """Bitmap of serial line states."""
    RTS = ...
    DTR = ...


class ESPHomeSerial(BaseSerial):
    """Synchronous serial interface over ESPHome serial proxy API.

    Warning:
        ESPHome does not have a native synchronous API, using this interface is
        heavily discouraged. Please use the async API.

    """
    def __init__(self, *args: Any, connect_timeout: float = ..., loop: asyncio.AbstractEventLoop | None = ..., api: APIClient | None = ..., port_name: str | None = ..., port_instance: int | None = ..., key: str | None = ..., password: str | None = ..., noise_psk: str | None = ..., **kwargs: Any) -> None:
        """Initialize ESPHome serial port.

        Args:
            connect_timeout: Total timeout for connecting to the ESPHome device and
                subscribing to events.
            loop: Event loop to offload async operations to, optional. This is mostly
                intended for internal use from the async transport. If an event loop is
                not provided, the default for the synchronous API, a new one will be
                created at runtime.
            api: An instance of `aioesphomeapi.APIClient` to use. Authentication will
                be skipped and the API will not be disconnected once the serial object
                is closed.
            port_name: The `name` attribute of the ESPHome serial proxy to connect to.
            port_instance: The numerical instance ID of the ESPHome serial proxy
                instance to connect to.

                .. deprecated:: 1.2.0
            key: The Noise PSK to use when creating an `aioesphomeapi.APIClient`
                instance.
            password: The API password to use when creating an `aioesphomeapi.APIClient`
                instance.
            noise_psk: An alias for `key`. Both cannot be passed at once.
            *args: Passed through to `BaseSerial`.
            **kwargs: Passed through to `BaseSerial`.

        """
        ...
    
    @property
    def is_open(self) -> bool:
        """Return whether the serial port is open."""
        ...
    
    def num_unread_bytes(self) -> int:
        """Return the number of bytes waiting to be read."""
        ...
    
    def num_unwritten_bytes(self) -> int:
        """Return the number of bytes waiting to be written."""
        ...
    


class ESPHomeSerialTransport(BaseSerialTransport):
    """Serial transport over ESPHome serial proxy API."""
    transport_name = ...
    _serial_cls: type[ESPHomeSerial] = ...
    _serial: ESPHomeSerial | None
    def __init__(self, loop: asyncio.AbstractEventLoop, protocol: asyncio.Protocol) -> None:
        """Initialize the ESPHome serial transport."""
        ...
    
    def write(self, data: bytes | bytearray | memoryview) -> None:
        """Write data to the serial proxy."""
        ...
    
    def is_closing(self) -> bool:
        """Return whether the transport is closing."""
        ...
    
    def close(self) -> None:
        """Close the transport."""
        ...
    
    def abort(self) -> None:
        """Abort the transport immediately."""
        ...
    
    def get_write_buffer_size(self) -> int:
        """Get the number of bytes currently in the write buffer."""
        ...
    


def esphome_list_serial_ports(*args: Any, **kwargs: Any) -> list[SerialPortInfo]:
    """List serial ports for ESPhome."""
    ...

async def async_esphome_list_serial_ports(*args: Any, **kwargs: Any) -> list[SerialPortInfo]:
    """List serial ports for ESPhome."""
    ...

