"""
This type stub file was generated by pyright.
"""

import sys
from serialx.common import SerialPortInfo
from .serial_extended_posix import ExtendedPosixSerial, ExtendedPosixSerialTransport

"""Darwin serial port implementation."""
LOGGER = ...
IOSSIOSPEED = ...
NON_POSIX_FALLBACK_BAUDRATE_CONST = ...
class DarwinSerial(ExtendedPosixSerial):
    """Darwin serial port implementation."""
    ...


class DarwinSerialTransport(ExtendedPosixSerialTransport):
    """Darwin asyncio serial port transport."""
    _serial_cls = DarwinSerial


def darwin_list_serial_ports() -> list[SerialPortInfo]:
    """List available serial ports on macOS."""
    ...

async def async_darwin_list_serial_ports() -> list[SerialPortInfo]:
    """List available serial ports on macOS, async."""
    ...

if sys.platform == "darwin":
    ...
