"""
This type stub file was generated by pyright.
"""

import sys
from typing import NamedTuple
from ..common import SerialPortInfo
from .serial_extended_posix import ExtendedPosixSerial, ExtendedPosixSerialTransport

"""FreeBSD serial port implementation."""
LOGGER = ...
class _UsbKey(NamedTuple):
    ugen: str
    interface_num: int | None
    ...


class _UsbStrings(NamedTuple):
    manufacturer: str | None
    product: str | None
    interface_description: str | None
    ...


_PNPINFO_RE = ...
_LOCATION_RE = ...
_MANUFACTURER_RE = ...
_PRODUCT_RE = ...
_INTERFACE_HEADER_RE = ...
_IINTERFACE_RE = ...
class FreeBSDSerial(ExtendedPosixSerial):
    """FreeBSD serial port implementation."""
    ...


class FreeBSDSerialTransport(ExtendedPosixSerialTransport):
    """FreeBSD serial port transport."""
    _serial_cls = FreeBSDSerial


def freebsd_list_serial_ports() -> list[SerialPortInfo]:
    """List available serial ports on FreeBSD."""
    ...

async def async_freebsd_list_serial_ports() -> list[SerialPortInfo]:
    """List serial ports on FreeBSD, async."""
    ...

if sys.platform.startswith("freebsd"):
    ...
