"""
This type stub file was generated by pyright.
"""

import sys
from typing import Any, NamedTuple
from ..common import BaseSerial, ModemPins, PinState
from ..descriptor_transport import DescriptorTransport

"""POSIX serial port implementation."""
if sys.version_info >= (3, 11):
    ...
else:
    ...
LOGGER = ...
FLUSH_TIMEOUT = ...
AFTER_OPEN_DELAY = ...
MODEM_BIT_MAPPING = ...
class TcsetattrFlags(NamedTuple):
    """Flags for `termios.tcsetattr`."""
    iflag: int
    oflag: int
    cflag: int
    lflag: int
    ispeed: int
    ospeed: int
    cc_vmin: int
    cc_vtime: int
    ...


def modem_pins_mask_of_value(modem_pins: ModemPins, mask: PinState) -> int:
    """Get modem bit mask for bits matching the specified value."""
    ...

def modem_pins_as_int(modem_pins: ModemPins) -> int:
    """Convert modem pins to integer."""
    ...

class PosixSerial(BaseSerial):
    """POSIX serial port implementation."""
    def __init__(self, *args: Any, fileno: int | None = ..., inter_byte_timeout: float = ..., min_read_size: int = ..., **kwargs: Any) -> None:
        """Initialize POSIX serial port."""
        ...
    
    @property
    def is_open(self) -> bool:
        """Check if the serial port is open."""
        ...
    
    def fileno(self) -> int:
        """Get the file descriptor number."""
        ...
    
    if sys.version_info >= (3, 14):
        ...
    else:
        ...
    def num_unread_bytes(self) -> int:
        """Return the number of bytes waiting to be read."""
        ...
    
    def num_unwritten_bytes(self) -> int:
        """Return the number of bytes waiting to be written."""
        ...
    


class PosixSerialTransport(DescriptorTransport):
    """POSIX serial port transport using asyncio."""
    _serial_cls: type[PosixSerial] = ...


