"""
This type stub file was generated by pyright.
"""

import asyncio
import sys
from typing import Any
from serialx.common import BaseSerial, BaseSerialTransport

"""Socket serial transport."""
if sys.version_info >= (3, 11):
    ...
else:
    ...
LOGGER = ...
DEFAULT_CONNECT_TIMEOUT = ...
class SocketSerial(BaseSerial):
    """Synchronous serial interface over a TCP socket."""
    def __init__(self, *args: Any, connect_timeout: float | None = ..., **kwargs: Any) -> None:
        """Initialize socket serial port."""
        ...
    
    @property
    def is_open(self) -> bool:
        """Check if the serial port is open."""
        ...
    
    @property
    def connect_timeout(self) -> float | None:
        """Get the connection timeout in seconds."""
        ...
    
    def num_unread_bytes(self) -> int:
        """Return the number of bytes waiting to be read."""
        ...
    
    def num_unwritten_bytes(self) -> int:
        """Return the number of bytes waiting to be written."""
        ...
    


class _SocketProxyProtocol(asyncio.Protocol):
    """Bridge protocol between asyncio TCP transport and SocketSerialTransport."""
    def __init__(self, serial_transport: SocketSerialTransport) -> None:
        ...
    
    def data_received(self, data: bytes) -> None:
        ...
    
    def pause_writing(self) -> None:
        ...
    
    def resume_writing(self) -> None:
        ...
    
    def connection_lost(self, exc: Exception | None) -> None:
        ...
    


class SocketSerialTransport(BaseSerialTransport):
    """Serial transport over a TCP socket."""
    transport_name = ...
    def __init__(self, loop: asyncio.AbstractEventLoop, protocol: asyncio.Protocol) -> None:
        """Initialize the socket serial transport."""
        ...
    
    def write(self, data: bytes | bytearray | memoryview) -> None:
        """Write data to the socket."""
        ...
    
    def pause_reading(self) -> None:
        """Pause reading from the socket transport."""
        ...
    
    def resume_reading(self) -> None:
        """Resume reading from the socket transport."""
        ...
    
    def is_closing(self) -> bool:
        """Return whether the transport is closing."""
        ...
    
    def abort(self) -> None:
        """Abort the transport immediately."""
        ...
    
    def close(self) -> None:
        """Close the transport."""
        ...
    
    def get_write_buffer_size(self) -> int:
        """Get the number of bytes currently in the write buffer."""
        ...
    
    def get_write_buffer_limits(self) -> tuple[int, int]:
        """Get the write buffer low and high water marks."""
        ...
    
    def set_write_buffer_limits(self, high: int | None = ..., low: int | None = ...) -> None:
        """Set the write buffer low and high water marks."""
        ...
    
    def can_write_eof(self) -> bool:
        """Return whether the underlying TCP transport supports EOF."""
        ...
    


