"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import Any, TYPE_CHECKING
from serialx.common import SerialPortInfo
from ..common import BaseSerial, BaseSerialTransport

"""Windows serial port implementation using Win32 API."""
if TYPE_CHECKING:
    ...
MS_CTS_ON = ...
MS_DSR_ON = ...
MS_RING_ON = ...
MS_RLSD_ON = ...
SETXOFF = ...
SETXON = ...
SETRTS = ...
CLRRTS = ...
SETDTR = ...
CLRDTR = ...
LOGGER = ...
WIN32_PARITY_MAP = ...
WIN32_STOPBITS_MAP = ...
def CreateFile_detached(*, file_name: str, desired_access: int, share_mode: int, creation_disposition: int, flags_and_attributes: int) -> int:
    """`CreateFile` returning a raw `int` HANDLE that the caller owns."""
    ...

class Win32Serial(BaseSerial):
    """Windows serial port implementation using Win32 API."""
    def __init__(self, *args: Any, handle: int | None = ..., inter_byte_timeout: float = ..., read_buffer_size: int = ..., write_buffer_size: int = ..., **kwargs: Any) -> None:
        """Initialize the Windows serial port."""
        ...
    
    @property
    def is_open(self) -> bool:
        """Check if the serial port is open."""
        ...
    
    def fileno(self) -> int:
        """Return the file descriptor."""
        ...
    
    def num_unread_bytes(self) -> int:
        """Return the number of bytes waiting to be read."""
        ...
    
    def num_unwritten_bytes(self) -> int:
        """Return the number of bytes waiting to be written."""
        ...
    


class _MethodProxy:
    """Proxy object that forwards attribute access to a mapping."""
    def __init__(self, name: str, mapping: dict[str, Any]) -> None:
        """Initialize the method proxy."""
        ...
    
    def eof_received(self) -> bool:
        """Handle EOF by signalling the transport to close."""
        ...
    
    def __getattr__(self, name: str) -> Any:
        """Forward attribute access to the mapping."""
        ...
    


class Win32SerialTransport(BaseSerialTransport):
    """Windows serial transport using ProactorEventLoop."""
    def __init__(self, loop: asyncio.AbstractEventLoop, protocol: asyncio.Protocol) -> None:
        """Initialize the Windows serial transport."""
        ...
    
    def serial_close(self) -> None:
        """Release the handle off the event loop, then report connection lost."""
        ...
    
    def serial_shutdown(self, how: int) -> None:
        """Shutdown the serial connection."""
        ...
    
    def serial_fileno(self) -> int:
        """Return the file descriptor."""
        ...
    
    def protocol_data_received(self, data: bytes) -> None:
        """Forward data_received to the protocol."""
        ...
    
    def protocol_connection_made(self, transport: asyncio.Transport) -> None:
        """Forward connection_made to the protocol."""
        ...
    
    def protocol_connection_lost(self, exc: Exception | None) -> None:
        """Stash the connection-lost reason, `serial_close` dispatches it."""
        ...
    
    def protocol_pause_writing(self) -> None:
        """Forward pause_writing to the protocol."""
        ...
    
    def protocol_resume_writing(self) -> None:
        """Forward resume_writing to the protocol."""
        ...
    
    def get_write_buffer_size(self) -> int:
        """Return the current size of the write buffer."""
        ...
    
    def get_write_buffer_limits(self) -> tuple[int, int]:
        """Return the write buffer limits."""
        ...
    
    def set_write_buffer_limits(self, high: int | None = ..., low: int | None = ...) -> None:
        """Set the write buffer limits."""
        ...
    
    def write(self, data: bytes | bytearray | memoryview) -> None:
        """Write data to the transport."""
        ...
    
    def close(self) -> None:
        """Close the transport."""
        ...
    
    def abort(self) -> None:
        """Abort the transport immediately."""
        ...
    
    def pause_reading(self) -> None:
        """Pause reading from the transport."""
        ...
    
    def resume_reading(self) -> None:
        """Resume reading from the transport."""
        ...
    
    def set_protocol(self, protocol: asyncio.Protocol) -> None:
        """Set the protocol."""
        ...
    


def win32_list_serial_ports() -> list[SerialPortInfo]:
    """List available serial ports on Windows."""
    ...

async def async_win32_list_serial_ports() -> list[SerialPortInfo]:
    """List available serial ports on Windows, async."""
    ...

