"""
This type stub file was generated by pyright.
"""

from .serial_posix import PosixSerial, PosixSerialTransport

"""Extended POSIX serial port implementation.

Adds non-POSIX features that are available on all major UNIX-like platforms.
"""
CRTSCTS = ...
def is_extended_posix() -> bool:
    """Check if the platform supports extended POSIX serial features."""
    ...

class ExtendedPosixSerial(PosixSerial):
    """Extended POSIX serial port with CRTSCTS support."""
    ...


class ExtendedPosixSerialTransport(PosixSerialTransport):
    """Extended POSIX serial port transport with CRTSCTS support."""
    _serial_cls = ExtendedPosixSerial


if is_extended_posix():
    ...
