"""
This type stub file was generated by pyright.
"""

import sys
from paho.mqtt.properties import Properties
from typing import Self
from .topic import TopicLike
from .types import PayloadType

if sys.version_info >= (3, 11): ...
else: ...

class Message:
    """Wraps the paho-mqtt message class to allow using our own matching logic.

    This class is not meant to be instantiated by the user. Instead, it is yielded by
    the async generator ``Client.messages``.

    Args:
        topic: The topic the message was published to.
        payload: The message payload.
        qos: The quality of service level of the subscription that matched the message.
        retain: Whether the message is a retained message.
        mid: The message ID.
        properties: (MQTT v5.0 only) The properties associated with the message.

    Attributes:
        topic (aiomqtt.client.Topic):
            The topic the message was published to.
        payload (str | bytes | bytearray | int | float | None):
            The message payload.
        qos (int):
            The quality of service level of the subscription that matched the message.
        retain (bool):
            Whether the message is a retained message.
        mid (int):
            The message ID.
        properties (paho.mqtt.properties.Properties | None):
            (MQTT v5.0 only) The properties associated with the message.
    """
    def __init__(
        self, topic: TopicLike, payload: PayloadType, qos: int, retain: bool, mid: int, properties: Properties | None
    ) -> None: ...

    topic: TopicLike
    payload: PayloadType
    qos: int
    retain: bool
    mid: int
    properties: Properties | None

    def __lt__(self, other: Self) -> bool: ...
