# Composite action for Python + tox setup with caching
# Eliminates ~30 lines of duplicated setup across CI jobs

name: Setup Python + Tox
description: 'Install Python, pip, tox and configure caching'

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.13'
  install-system-deps:
    description: 'Install system dependencies (libreadline-dev)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Cache tox environments
      uses: actions/cache@v4
      with:
        path: .tox
        key: tox-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('tox.ini', 'pyproject.toml', 'requirements/runtime.txt') }}
        restore-keys: |
          tox-${{ runner.os }}-py${{ inputs.python-version }}-

    - name: Install System Dependencies
      if: inputs.install-system-deps == 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libreadline-dev

    - name: Install pip + tox
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
