/*
 * This file is part of Arduino MCU Ecosystem v2.
 * Copyright (C) 2025 Ignacio Santolin and contributors
 *
 * Auto-generated by tools/protocol/generate.py. DO NOT EDIT.
 */
#ifndef RPC_STRUCTS_H
#define RPC_STRUCTS_H

#include <stdint.h>
#include "rpc_protocol.h"
#include "rpc_frame.h"

namespace rpc {
namespace payload {

struct HandshakeConfig {
    uint16_t ack_timeout_ms;
    uint8_t ack_retry_limit;
    uint32_t response_timeout_ms;

    static constexpr size_t SIZE = 7;

    static HandshakeConfig parse(const uint8_t* data) {
        HandshakeConfig msg;
        msg.ack_timeout_ms = rpc::read_u16_be(data + 0);
        msg.ack_retry_limit = data[2];
        msg.response_timeout_ms = rpc::read_u32_be(data + 3);
        return msg;
    }
};

} // namespace payload
} // namespace rpc
#endif
