/*
 * This file is part of Arduino Yun Ecosystem v2.
 * Copyright (C) 2025 Ignacio Santolin and contributors
 *
 * Auto-generated by tools/protocol/generate.py. DO NOT EDIT.
 */
#ifndef RPC_PROTOCOL_H
#define RPC_PROTOCOL_H

#include <stdint.h>
#include "rpc_frame.h"

static_assert(rpc::PROTOCOL_VERSION == 2, "Version mismatch");
constexpr unsigned long RPC_DEFAULT_BAUDRATE = 115200;
constexpr unsigned int RPC_BUFFER_SIZE = 128;

constexpr unsigned int RPC_HANDSHAKE_NONCE_LENGTH = 16;
constexpr unsigned int RPC_HANDSHAKE_TAG_LENGTH = 16;
constexpr unsigned int RPC_HANDSHAKE_CONFIG_SIZE = 7;
constexpr uint32_t RPC_HANDSHAKE_ACK_TIMEOUT_MIN_MS = 25;
constexpr uint32_t RPC_HANDSHAKE_ACK_TIMEOUT_MAX_MS = 60000;
constexpr uint32_t RPC_HANDSHAKE_RESPONSE_TIMEOUT_MIN_MS = 100;
constexpr uint32_t RPC_HANDSHAKE_RESPONSE_TIMEOUT_MAX_MS = 180000;
constexpr unsigned int RPC_HANDSHAKE_RETRY_LIMIT_MIN = 1;
constexpr unsigned int RPC_HANDSHAKE_RETRY_LIMIT_MAX = 8;

namespace rpc {

enum class StatusCode : uint8_t {
    STATUS_OK = 0,
    STATUS_ERROR = 1,
    STATUS_CMD_UNKNOWN = 2,
    STATUS_MALFORMED = 3,
    STATUS_CRC_MISMATCH = 4,
    STATUS_TIMEOUT = 5,
    STATUS_NOT_IMPLEMENTED = 6,
    STATUS_ACK = 7,
};

enum class CommandId : uint16_t {
    CMD_GET_VERSION = 0,
    CMD_GET_VERSION_RESP = 128,
    CMD_GET_FREE_MEMORY = 1,
    CMD_GET_FREE_MEMORY_RESP = 130,
    CMD_GET_TX_DEBUG_SNAPSHOT = 4,
    CMD_GET_TX_DEBUG_SNAPSHOT_RESP = 133,
    CMD_LINK_SYNC = 2,
    CMD_LINK_SYNC_RESP = 131,
    CMD_LINK_RESET = 3,
    CMD_LINK_RESET_RESP = 132,
    CMD_XOFF = 8,
    CMD_XON = 9,
    CMD_SET_PIN_MODE = 16,
    CMD_DIGITAL_WRITE = 17,
    CMD_ANALOG_WRITE = 18,
    CMD_DIGITAL_READ = 19,
    CMD_ANALOG_READ = 20,
    CMD_DIGITAL_READ_RESP = 21,
    CMD_ANALOG_READ_RESP = 22,
    CMD_CONSOLE_WRITE = 32,
    CMD_DATASTORE_PUT = 48,
    CMD_DATASTORE_GET = 49,
    CMD_DATASTORE_GET_RESP = 129,
    CMD_MAILBOX_READ = 64,
    CMD_MAILBOX_PROCESSED = 65,
    CMD_MAILBOX_AVAILABLE = 66,
    CMD_MAILBOX_PUSH = 67,
    CMD_MAILBOX_READ_RESP = 144,
    CMD_MAILBOX_AVAILABLE_RESP = 146,
    CMD_FILE_WRITE = 80,
    CMD_FILE_READ = 81,
    CMD_FILE_REMOVE = 82,
    CMD_FILE_READ_RESP = 161,
    CMD_PROCESS_RUN = 96,
    CMD_PROCESS_RUN_ASYNC = 97,
    CMD_PROCESS_POLL = 98,
    CMD_PROCESS_KILL = 99,
    CMD_PROCESS_RUN_RESP = 176,
    CMD_PROCESS_RUN_ASYNC_RESP = 177,
    CMD_PROCESS_POLL_RESP = 178,
};


constexpr uint8_t to_underlying(StatusCode value) {
    return static_cast<uint8_t>(value);
}

constexpr uint16_t to_underlying(CommandId value) {
    return static_cast<uint16_t>(value);
}
} // namespace rpc
#endif
