/*
 * This file is part of Arduino MCU Ecosystem v2.
 * Copyright (C) 2025 Ignacio Santolin and contributors
 *
 * Auto-generated by tools/protocol/generate.py. DO NOT EDIT.
 */
#ifndef RPC_PROTOCOL_H
#define RPC_PROTOCOL_H

#include <stddef.h>
#include <stdint.h>

namespace rpc {

constexpr uint8_t PROTOCOL_VERSION = 2;
constexpr unsigned long RPC_DEFAULT_BAUDRATE = 115200;
constexpr unsigned long RPC_DEFAULT_SAFE_BAUDRATE = 115200;
constexpr size_t MAX_PAYLOAD_SIZE = 64;
constexpr size_t RPC_MAX_FILEPATH_LENGTH = 64;
constexpr size_t RPC_MAX_DATASTORE_KEY_LENGTH = 32;
constexpr unsigned int RPC_DEFAULT_ACK_TIMEOUT_MS = 200;
constexpr uint8_t RPC_DEFAULT_RETRY_LIMIT = 5;
constexpr uint8_t RPC_MAX_PENDING_TX_FRAMES = 2;
constexpr uint16_t RPC_INVALID_ID_SENTINEL = 65535;
constexpr uint16_t RPC_CMD_FLAG_COMPRESSED = 32768;
constexpr uint8_t RPC_UINT8_MASK = 255;
constexpr uint16_t RPC_UINT16_MAX = 65535;
constexpr uint32_t RPC_CRC32_MASK = 4294967295;
constexpr uint32_t RPC_CRC_INITIAL = 4294967295;
constexpr uint32_t RPC_CRC_POLYNOMIAL = 3988292384;
constexpr uint8_t RPC_FRAME_DELIMITER = 0;
constexpr uint8_t RPC_DIGITAL_LOW = 0;
constexpr uint8_t RPC_DIGITAL_HIGH = 1;
constexpr uint8_t RPC_STATUS_CODE_MIN = 48;
constexpr uint8_t RPC_STATUS_CODE_MAX = 63;
constexpr uint16_t RPC_SYSTEM_COMMAND_MIN = 64;
constexpr uint16_t RPC_SYSTEM_COMMAND_MAX = 79;
constexpr uint16_t RPC_GPIO_COMMAND_MIN = 80;

constexpr unsigned int RPC_HANDSHAKE_NONCE_LENGTH = 16;
constexpr unsigned int RPC_HANDSHAKE_TAG_LENGTH = 16;
constexpr unsigned int RPC_HANDSHAKE_CONFIG_SIZE = 7;
constexpr uint32_t RPC_HANDSHAKE_ACK_TIMEOUT_MIN_MS = 25;
constexpr uint32_t RPC_HANDSHAKE_ACK_TIMEOUT_MAX_MS = 60000;
constexpr uint32_t RPC_HANDSHAKE_RESPONSE_TIMEOUT_MIN_MS = 100;
constexpr uint32_t RPC_HANDSHAKE_RESPONSE_TIMEOUT_MAX_MS = 180000;
constexpr unsigned int RPC_HANDSHAKE_RETRY_LIMIT_MIN = 1;
constexpr unsigned int RPC_HANDSHAKE_RETRY_LIMIT_MAX = 8;
constexpr uint8_t RPC_HANDSHAKE_HKDF_SALT[] = {0x6D, 0x63, 0x75, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2D, 0x76, 0x32};
constexpr size_t RPC_HANDSHAKE_HKDF_SALT_LEN = 12;
constexpr uint8_t RPC_HANDSHAKE_HKDF_INFO_AUTH[] = {0x68, 0x61, 0x6E, 0x64, 0x73, 0x68, 0x61, 0x6B, 0x65, 0x2D, 0x61, 0x75, 0x74, 0x68};
constexpr size_t RPC_HANDSHAKE_HKDF_INFO_AUTH_LEN = 14;
constexpr unsigned int RPC_HANDSHAKE_HKDF_OUTPUT_LENGTH = 32;
constexpr unsigned int RPC_HANDSHAKE_NONCE_RANDOM_BYTES = 8;
constexpr unsigned int RPC_HANDSHAKE_NONCE_COUNTER_BYTES = 8;

constexpr uint32_t RPC_CAPABILITY_WATCHDOG = 1;
constexpr uint32_t RPC_CAPABILITY_RLE = 2;
constexpr uint32_t RPC_CAPABILITY_DEBUG_FRAMES = 4;
constexpr uint32_t RPC_CAPABILITY_DEBUG_IO = 8;
constexpr uint32_t RPC_CAPABILITY_EEPROM = 16;
constexpr uint32_t RPC_CAPABILITY_DAC = 32;
constexpr uint32_t RPC_CAPABILITY_HW_SERIAL1 = 64;
constexpr uint32_t RPC_CAPABILITY_FPU = 128;
constexpr uint32_t RPC_CAPABILITY_LOGIC_3V3 = 256;
constexpr uint32_t RPC_CAPABILITY_BIG_BUFFER = 512;
constexpr uint32_t RPC_CAPABILITY_I2C = 1024;

enum class StatusCode : uint8_t {
    STATUS_OK = 48,
    STATUS_ERROR = 49,
    STATUS_CMD_UNKNOWN = 50,
    STATUS_MALFORMED = 51,
    STATUS_OVERFLOW = 52,
    STATUS_CRC_MISMATCH = 53,
    STATUS_TIMEOUT = 54,
    STATUS_NOT_IMPLEMENTED = 55,
    STATUS_ACK = 56,
};

enum class CommandId : uint16_t {
    CMD_GET_VERSION = 64,
    CMD_GET_VERSION_RESP = 65,
    CMD_GET_FREE_MEMORY = 66,
    CMD_GET_FREE_MEMORY_RESP = 67,
    CMD_LINK_SYNC = 68,
    CMD_LINK_SYNC_RESP = 69,
    CMD_LINK_RESET = 70,
    CMD_LINK_RESET_RESP = 71,
    CMD_GET_CAPABILITIES = 72,
    CMD_GET_CAPABILITIES_RESP = 73,
    CMD_SET_BAUDRATE = 74,
    CMD_SET_BAUDRATE_RESP = 75,
    CMD_XOFF = 78,
    CMD_XON = 79,
    CMD_SET_PIN_MODE = 80,
    CMD_DIGITAL_WRITE = 81,
    CMD_ANALOG_WRITE = 82,
    CMD_DIGITAL_READ = 83,
    CMD_ANALOG_READ = 84,
    CMD_DIGITAL_READ_RESP = 85,
    CMD_ANALOG_READ_RESP = 86,
    CMD_CONSOLE_WRITE = 96,
    CMD_DATASTORE_PUT = 112,
    CMD_DATASTORE_GET = 113,
    CMD_DATASTORE_GET_RESP = 114,
    CMD_MAILBOX_READ = 128,
    CMD_MAILBOX_PROCESSED = 129,
    CMD_MAILBOX_AVAILABLE = 130,
    CMD_MAILBOX_PUSH = 131,
    CMD_MAILBOX_READ_RESP = 132,
    CMD_MAILBOX_AVAILABLE_RESP = 133,
    CMD_FILE_WRITE = 144,
    CMD_FILE_READ = 145,
    CMD_FILE_REMOVE = 146,
    CMD_FILE_READ_RESP = 147,
};


constexpr uint8_t to_underlying(StatusCode value) {
    return static_cast<uint8_t>(value);
}

constexpr uint16_t to_underlying(CommandId value) {
    return static_cast<uint16_t>(value);
}
} // namespace rpc
#endif
