/*
 * This file is part of Arduino MCU Ecosystem v2.
 * Copyright (C) 2025 Ignacio Santolin and contributors
 *
 * Auto-generated by tools/protocol/generate.py. DO NOT EDIT.
 */
#include "rpc_protocol.h"

namespace rpc {
    uint8_t to_underlying(StatusCode value) { return static_cast<uint8_t>(value); }
    uint16_t to_underlying(CommandId value) { return static_cast<uint16_t>(value); }

    bool requires_ack(CommandId command_id) {
        return (command_id == CommandId::CMD_SET_PIN_MODE) || (command_id == CommandId::CMD_DIGITAL_WRITE) || (command_id == CommandId::CMD_ANALOG_WRITE) || (command_id == CommandId::CMD_CONSOLE_WRITE) || (command_id == CommandId::CMD_DATASTORE_PUT) || (command_id == CommandId::CMD_MAILBOX_PUSH) || (command_id == CommandId::CMD_FILE_WRITE);
    }

    bool requires_ack(uint16_t command_id) { return requires_ack(static_cast<CommandId>(command_id)); }
} // namespace rpc
