/*
 * This file is part of Arduino MCU Ecosystem v2.
 * Copyright (C) 2025 Ignacio Santolin and contributors
 *
 * Auto-generated by tools/protocol/generate.py. DO NOT EDIT.
 */
#include "rpc_structs.h"

namespace rpc {
    namespace payload {
        VersionResponse VersionResponse::parse(const uint8_t* data) {
            return {data[0], data[1]};
        }

        void VersionResponse::encode(uint8_t* data) const {
            data[0] = major;
            data[1] = minor;
        }

        FreeMemoryResponse FreeMemoryResponse::parse(const uint8_t* data) {
            return {rpc::read_u16_be(data)};
        }

        void FreeMemoryResponse::encode(uint8_t* data) const {
            rpc::write_u16_be(data + 0, value);
        }

        Capabilities Capabilities::parse(const uint8_t* data) {
            Capabilities msg;
            msg.ver = data[0];
            msg.arch = data[1];
            msg.dig = data[2];
            msg.ana = data[3];
            msg.feat = rpc::read_u32_be(data + 4);
            return msg;
        }

        void Capabilities::encode(uint8_t* data) const {
            data[0] = ver;
            data[1] = arch;
            data[2] = dig;
            data[3] = ana;
            rpc::write_u32_be(data + 4, feat);
        }

        PinMode PinMode::parse(const uint8_t* data) {
            return {data[0], data[1]};
        }

        void PinMode::encode(uint8_t* data) const {
            data[0] = pin;
            data[1] = mode;
        }

        DigitalWrite DigitalWrite::parse(const uint8_t* data) {
            return {data[0], data[1]};
        }

        void DigitalWrite::encode(uint8_t* data) const {
            data[0] = pin;
            data[1] = value;
        }

        AnalogWrite AnalogWrite::parse(const uint8_t* data) {
            return {data[0], data[1]};
        }

        void AnalogWrite::encode(uint8_t* data) const {
            data[0] = pin;
            data[1] = value;
        }

        PinRead PinRead::parse(const uint8_t* data) {
            return {data[0]};
        }

        void PinRead::encode(uint8_t* data) const {
            data[0] = pin;
        }

        DigitalReadResponse DigitalReadResponse::parse(const uint8_t* data) {
            return {data[0]};
        }

        void DigitalReadResponse::encode(uint8_t* data) const {
            data[0] = value;
        }

        AnalogReadResponse AnalogReadResponse::parse(const uint8_t* data) {
            return {rpc::read_u16_be(data)};
        }

        void AnalogReadResponse::encode(uint8_t* data) const {
            rpc::write_u16_be(data + 0, value);
        }

        MailboxProcessed MailboxProcessed::parse(const uint8_t* data) {
            return {rpc::read_u16_be(data)};
        }

        void MailboxProcessed::encode(uint8_t* data) const {
            rpc::write_u16_be(data + 0, message_id);
        }

        MailboxAvailableResponse MailboxAvailableResponse::parse(const uint8_t* data) {
            return {rpc::read_u16_be(data)};
        }

        void MailboxAvailableResponse::encode(uint8_t* data) const {
            rpc::write_u16_be(data + 0, count);
        }

        ProcessKill ProcessKill::parse(const uint8_t* data) {
            return {rpc::read_u16_be(data)};
        }

        void ProcessKill::encode(uint8_t* data) const {
            rpc::write_u16_be(data + 0, pid);
        }

        ProcessPoll ProcessPoll::parse(const uint8_t* data) {
            return {rpc::read_u16_be(data)};
        }

        void ProcessPoll::encode(uint8_t* data) const {
            rpc::write_u16_be(data + 0, pid);
        }

        ProcessRunAsyncResponse ProcessRunAsyncResponse::parse(const uint8_t* data) {
            return {rpc::read_u16_be(data)};
        }

        void ProcessRunAsyncResponse::encode(uint8_t* data) const {
            rpc::write_u16_be(data + 0, pid);
        }

        AckPacket AckPacket::parse(const uint8_t* data) {
            return {rpc::read_u16_be(data)};
        }

        void AckPacket::encode(uint8_t* data) const {
            rpc::write_u16_be(data + 0, command_id);
        }

        HandshakeConfig HandshakeConfig::parse(const uint8_t* data) {
            HandshakeConfig msg;
            msg.ack_timeout_ms = rpc::read_u16_be(data + 0);
            msg.ack_retry_limit = data[2];
            msg.response_timeout_ms = rpc::read_u32_be(data + 3);
            return msg;
        }

        void HandshakeConfig::encode(uint8_t* data) const {
            rpc::write_u16_be(data + 0, ack_timeout_ms);
            data[2] = ack_retry_limit;
            rpc::write_u32_be(data + 3, response_timeout_ms);
        }

        SetBaudratePacket SetBaudratePacket::parse(const uint8_t* data) {
            return {rpc::read_u32_be(data)};
        }

        void SetBaudratePacket::encode(uint8_t* data) const {
            rpc::write_u32_be(data + 0, baudrate);
        }

        ConsoleWrite ConsoleWrite::parse(const uint8_t* d, size_t l) { return {d, l}; }
        void ConsoleWrite::encode(uint8_t*) const { /* Not implemented */ }

        DatastoreGet DatastoreGet::parse(const uint8_t* d) { return {etl::string_view(reinterpret_cast<const char*>(d + 1), d[0])}; }
        void DatastoreGet::encode(uint8_t*) const { /* Not implemented */ }

        DatastoreGetResponse DatastoreGetResponse::parse(const uint8_t* d) { return {d + 1, d[0]}; }
        void DatastoreGetResponse::encode(uint8_t*) const { /* Not implemented */ }

        DatastorePut DatastorePut::parse(const uint8_t* d) { uint8_t k = d[0]; return {etl::string_view(reinterpret_cast<const char*>(d + 1), k), d + 1 + k + 1, d[1 + k]}; }
        void DatastorePut::encode(uint8_t*) const { /* Not implemented */ }

        MailboxPush MailboxPush::parse(const uint8_t* d) { return {d + 2, rpc::read_u16_be(d)}; }
        void MailboxPush::encode(uint8_t*) const { /* Not implemented */ }

        MailboxReadResponse MailboxReadResponse::parse(const uint8_t* d) { return {d + 2, rpc::read_u16_be(d)}; }
        void MailboxReadResponse::encode(uint8_t*) const { /* Not implemented */ }

        FileWrite FileWrite::parse(const uint8_t* d) { uint8_t p = d[0]; return {etl::string_view(reinterpret_cast<const char*>(d + 1), p), d + 1 + p + 2, rpc::read_u16_be(d + 1 + p)}; }
        void FileWrite::encode(uint8_t*) const { /* Not implemented */ }

        FileRead FileRead::parse(const uint8_t* d) { return {etl::string_view(reinterpret_cast<const char*>(d + 1), d[0])}; }
        void FileRead::encode(uint8_t*) const { /* Not implemented */ }

        FileReadResponse FileReadResponse::parse(const uint8_t* d) { return {d + 2, rpc::read_u16_be(d)}; }
        void FileReadResponse::encode(uint8_t*) const { /* Not implemented */ }

        FileRemove FileRemove::parse(const uint8_t* d) { return {etl::string_view(reinterpret_cast<const char*>(d + 1), d[0])}; }
        void FileRemove::encode(uint8_t*) const { /* Not implemented */ }

        ProcessRun ProcessRun::parse(const uint8_t* d, size_t l) { return {etl::string_view(reinterpret_cast<const char*>(d), l)}; }
        void ProcessRun::encode(uint8_t*) const { /* Not implemented */ }

        ProcessRunAsync ProcessRunAsync::parse(const uint8_t* d, size_t l) { return {etl::string_view(reinterpret_cast<const char*>(d), l)}; }
        void ProcessRunAsync::encode(uint8_t*) const { /* Not implemented */ }

        ProcessRunResponse ProcessRunResponse::parse(const uint8_t* d) { ProcessRunResponse m; m.status = d[0]; m.stdout_len = rpc::read_u16_be(d + 1); m.stdout_data = d + 3; m.stderr_len = rpc::read_u16_be(d + 3 + m.stdout_len); m.stderr_data = d + 3 + m.stdout_len + 2; m.exit_code = d[3 + m.stdout_len + 2 + m.stderr_len]; return m; }
        void ProcessRunResponse::encode(uint8_t*) const { /* Not implemented */ }

        ProcessPollResponse ProcessPollResponse::parse(const uint8_t* d) { ProcessPollResponse m; m.status = d[0]; m.exit_code = d[1]; m.stdout_len = rpc::read_u16_be(d + 2); m.stdout_data = d + 4; m.stderr_len = rpc::read_u16_be(d + 4 + m.stdout_len); m.stderr_data = d + 4 + m.stdout_len + 2; return m; }
        void ProcessPollResponse::encode(uint8_t*) const { /* Not implemented */ }

    } // namespace payload

    namespace Payload {
        template <> etl::expected<payload::ConsoleWrite, rpc::FrameError> parse<payload::ConsoleWrite>(const rpc::Frame& frame) {
            return etl::expected<payload::ConsoleWrite, rpc::FrameError>(payload::ConsoleWrite::parse(frame.payload.data(), frame.header.payload_length));
        }
        template <> etl::expected<payload::ProcessRun, rpc::FrameError> parse<payload::ProcessRun>(const rpc::Frame& frame) {
            return etl::expected<payload::ProcessRun, rpc::FrameError>(payload::ProcessRun::parse(frame.payload.data(), frame.header.payload_length));
        }
        template <> etl::expected<payload::ProcessRunAsync, rpc::FrameError> parse<payload::ProcessRunAsync>(const rpc::Frame& frame) {
            return etl::expected<payload::ProcessRunAsync, rpc::FrameError>(payload::ProcessRunAsync::parse(frame.payload.data(), frame.header.payload_length));
        }
        template <> etl::expected<payload::DatastoreGet, rpc::FrameError> parse<payload::DatastoreGet>(const rpc::Frame& frame) {
            if (frame.header.payload_length < 1 || frame.header.payload_length < (size_t)(frame.payload[0] + 1)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::DatastoreGet, rpc::FrameError>(payload::DatastoreGet::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::DatastoreGetResponse, rpc::FrameError> parse<payload::DatastoreGetResponse>(const rpc::Frame& frame) {
            if (frame.header.payload_length < 1 || frame.header.payload_length < (size_t)(frame.payload[0] + 1)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::DatastoreGetResponse, rpc::FrameError>(payload::DatastoreGetResponse::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::DatastorePut, rpc::FrameError> parse<payload::DatastorePut>(const rpc::Frame& frame) {
            if (frame.header.payload_length < 2) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            uint8_t k = frame.payload[0];
            if (frame.header.payload_length < (size_t)(k + 2)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            uint8_t v = frame.payload[k + 1];
            if (frame.header.payload_length < (size_t)(k + v + 2)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::DatastorePut, rpc::FrameError>(payload::DatastorePut::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::MailboxPush, rpc::FrameError> parse<payload::MailboxPush>(const rpc::Frame& frame) {
            if (frame.header.payload_length < 2) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            uint16_t l = rpc::read_u16_be(frame.payload.data());
            if (frame.header.payload_length < (size_t)(l + 2)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::MailboxPush, rpc::FrameError>(payload::MailboxPush::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::MailboxReadResponse, rpc::FrameError> parse<payload::MailboxReadResponse>(const rpc::Frame& frame) {
            if (frame.header.payload_length < 2) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            uint16_t l = rpc::read_u16_be(frame.payload.data());
            if (frame.header.payload_length < (size_t)(l + 2)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::MailboxReadResponse, rpc::FrameError>(payload::MailboxReadResponse::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::FileWrite, rpc::FrameError> parse<payload::FileWrite>(const rpc::Frame& frame) {
            if (frame.header.payload_length < 3) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            uint8_t p = frame.payload[0];
            if (frame.header.payload_length < (size_t)(p + 3)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            uint16_t d = rpc::read_u16_be(frame.payload.data() + 1 + p);
            if (frame.header.payload_length < (size_t)(p + d + 3)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::FileWrite, rpc::FrameError>(payload::FileWrite::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::FileRead, rpc::FrameError> parse<payload::FileRead>(const rpc::Frame& frame) {
            if (frame.header.payload_length < 1 || frame.header.payload_length < (size_t)(frame.payload[0] + 1)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::FileRead, rpc::FrameError>(payload::FileRead::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::FileReadResponse, rpc::FrameError> parse<payload::FileReadResponse>(const rpc::Frame& frame) {
            if (frame.header.payload_length < 2) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            uint16_t l = rpc::read_u16_be(frame.payload.data());
            if (frame.header.payload_length < (size_t)(l + 2)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::FileReadResponse, rpc::FrameError>(payload::FileReadResponse::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::FileRemove, rpc::FrameError> parse<payload::FileRemove>(const rpc::Frame& frame) {
            if (frame.header.payload_length < 1 || frame.header.payload_length < (size_t)(frame.payload[0] + 1)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::FileRemove, rpc::FrameError>(payload::FileRemove::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::ProcessRunResponse, rpc::FrameError> parse<payload::ProcessRunResponse>(const rpc::Frame& frame) {
            if (frame.header.payload_length < 6) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            uint16_t o = rpc::read_u16_be(frame.payload.data() + 1);
            if (frame.header.payload_length < (size_t)(o + 5)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            uint16_t e = rpc::read_u16_be(frame.payload.data() + 3 + o);
            if (frame.header.payload_length < (size_t)(o + e + 6)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::ProcessRunResponse, rpc::FrameError>(payload::ProcessRunResponse::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::ProcessPollResponse, rpc::FrameError> parse<payload::ProcessPollResponse>(const rpc::Frame& frame) {
            if (frame.header.payload_length < 6) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            uint16_t o = rpc::read_u16_be(frame.payload.data() + 2);
            if (frame.header.payload_length < (size_t)(o + 6)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            uint16_t e = rpc::read_u16_be(frame.payload.data() + 4 + o);
            if (frame.header.payload_length < (size_t)(o + e + 6)) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::ProcessPollResponse, rpc::FrameError>(payload::ProcessPollResponse::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::VersionResponse, rpc::FrameError> parse<payload::VersionResponse>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::VersionResponse::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::VersionResponse, rpc::FrameError>(payload::VersionResponse::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::FreeMemoryResponse, rpc::FrameError> parse<payload::FreeMemoryResponse>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::FreeMemoryResponse::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::FreeMemoryResponse, rpc::FrameError>(payload::FreeMemoryResponse::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::Capabilities, rpc::FrameError> parse<payload::Capabilities>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::Capabilities::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::Capabilities, rpc::FrameError>(payload::Capabilities::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::PinMode, rpc::FrameError> parse<payload::PinMode>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::PinMode::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::PinMode, rpc::FrameError>(payload::PinMode::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::DigitalWrite, rpc::FrameError> parse<payload::DigitalWrite>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::DigitalWrite::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::DigitalWrite, rpc::FrameError>(payload::DigitalWrite::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::AnalogWrite, rpc::FrameError> parse<payload::AnalogWrite>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::AnalogWrite::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::AnalogWrite, rpc::FrameError>(payload::AnalogWrite::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::PinRead, rpc::FrameError> parse<payload::PinRead>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::PinRead::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::PinRead, rpc::FrameError>(payload::PinRead::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::DigitalReadResponse, rpc::FrameError> parse<payload::DigitalReadResponse>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::DigitalReadResponse::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::DigitalReadResponse, rpc::FrameError>(payload::DigitalReadResponse::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::AnalogReadResponse, rpc::FrameError> parse<payload::AnalogReadResponse>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::AnalogReadResponse::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::AnalogReadResponse, rpc::FrameError>(payload::AnalogReadResponse::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::MailboxProcessed, rpc::FrameError> parse<payload::MailboxProcessed>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::MailboxProcessed::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::MailboxProcessed, rpc::FrameError>(payload::MailboxProcessed::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::MailboxAvailableResponse, rpc::FrameError> parse<payload::MailboxAvailableResponse>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::MailboxAvailableResponse::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::MailboxAvailableResponse, rpc::FrameError>(payload::MailboxAvailableResponse::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::ProcessKill, rpc::FrameError> parse<payload::ProcessKill>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::ProcessKill::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::ProcessKill, rpc::FrameError>(payload::ProcessKill::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::ProcessPoll, rpc::FrameError> parse<payload::ProcessPoll>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::ProcessPoll::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::ProcessPoll, rpc::FrameError>(payload::ProcessPoll::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::ProcessRunAsyncResponse, rpc::FrameError> parse<payload::ProcessRunAsyncResponse>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::ProcessRunAsyncResponse::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::ProcessRunAsyncResponse, rpc::FrameError>(payload::ProcessRunAsyncResponse::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::AckPacket, rpc::FrameError> parse<payload::AckPacket>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::AckPacket::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::AckPacket, rpc::FrameError>(payload::AckPacket::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::HandshakeConfig, rpc::FrameError> parse<payload::HandshakeConfig>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::HandshakeConfig::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::HandshakeConfig, rpc::FrameError>(payload::HandshakeConfig::parse(frame.payload.data()));
        }
        template <> etl::expected<payload::SetBaudratePacket, rpc::FrameError> parse<payload::SetBaudratePacket>(const rpc::Frame& frame) {
            if (frame.header.payload_length < payload::SetBaudratePacket::SIZE) return etl::unexpected<rpc::FrameError>(rpc::FrameError::MALFORMED);
            return etl::expected<payload::SetBaudratePacket, rpc::FrameError>(payload::SetBaudratePacket::parse(frame.payload.data()));
        }
    } // namespace Payload
} // namespace rpc
