/*
 * This file is part of Arduino Yun Ecosystem v2.
 * Copyright (C) 2025 Ignacio Santolin and contributors
 *
 * Auto-generated by tools/protocol/generate.py. DO NOT EDIT.
 */
#ifndef RPC_PROTOCOL_H
#define RPC_PROTOCOL_H

#include <stdint.h>

namespace rpc {

constexpr uint8_t PROTOCOL_VERSION = 2;
constexpr unsigned long RPC_DEFAULT_BAUDRATE = 115200;
constexpr unsigned long RPC_DEFAULT_SAFE_BAUDRATE = 115200;
constexpr unsigned int RPC_BUFFER_SIZE = 128;

constexpr size_t RPC_MAX_FILEPATH_LENGTH = 64;
constexpr size_t RPC_MAX_DATASTORE_KEY_LENGTH = 32;
constexpr unsigned int RPC_DEFAULT_ACK_TIMEOUT_MS = 200;
constexpr uint8_t RPC_DEFAULT_RETRY_LIMIT = 5;
constexpr uint8_t RPC_MAX_PENDING_TX_FRAMES = 2;
constexpr uint16_t RPC_INVALID_ID_SENTINEL = 65535;
constexpr uint8_t RPC_RESPONSE_OFFSET = 128;
constexpr uint8_t RPC_UINT8_MASK = 255;
constexpr uint16_t RPC_UINT16_MAX = 65535;
constexpr uint8_t RPC_PROCESS_DEFAULT_EXIT_CODE = 255;
constexpr uint32_t RPC_CRC32_MASK = 4294967295;
constexpr uint32_t RPC_CRC_INITIAL = 4294967295;
constexpr uint32_t RPC_CRC_POLYNOMIAL = 3988292384;
constexpr uint8_t RPC_FRAME_DELIMITER = 0;
constexpr uint8_t RPC_DIGITAL_LOW = 0;
constexpr uint8_t RPC_DIGITAL_HIGH = 1;
constexpr uint8_t RPC_TEST_PAYLOAD_BYTE = 170;
constexpr uint8_t RPC_TEST_MARKER_BYTE = 85;
constexpr uint8_t RPC_TEST_EXIT_CODE = 127;
constexpr uint16_t RPC_SYSTEM_COMMAND_MAX = 79;

constexpr unsigned int RPC_HANDSHAKE_NONCE_LENGTH = 16;
constexpr unsigned int RPC_HANDSHAKE_TAG_LENGTH = 16;
constexpr unsigned int RPC_HANDSHAKE_CONFIG_SIZE = 7;
constexpr uint32_t RPC_HANDSHAKE_ACK_TIMEOUT_MIN_MS = 25;
constexpr uint32_t RPC_HANDSHAKE_ACK_TIMEOUT_MAX_MS = 60000;
constexpr uint32_t RPC_HANDSHAKE_RESPONSE_TIMEOUT_MIN_MS = 100;
constexpr uint32_t RPC_HANDSHAKE_RESPONSE_TIMEOUT_MAX_MS = 180000;
constexpr unsigned int RPC_HANDSHAKE_RETRY_LIMIT_MIN = 1;
constexpr unsigned int RPC_HANDSHAKE_RETRY_LIMIT_MAX = 8;

enum class StatusCode : uint8_t {
    STATUS_OK = 48,
    STATUS_ERROR = 49,
    STATUS_CMD_UNKNOWN = 50,
    STATUS_MALFORMED = 51,
    STATUS_OVERFLOW = 52,
    STATUS_CRC_MISMATCH = 53,
    STATUS_TIMEOUT = 54,
    STATUS_NOT_IMPLEMENTED = 55,
    STATUS_ACK = 56,
};

enum class CommandId : uint16_t {
    CMD_GET_VERSION = 64,
    CMD_GET_VERSION_RESP = 65,
    CMD_GET_FREE_MEMORY = 66,
    CMD_GET_FREE_MEMORY_RESP = 67,
    CMD_LINK_SYNC = 68,
    CMD_LINK_SYNC_RESP = 69,
    CMD_LINK_RESET = 70,
    CMD_LINK_RESET_RESP = 71,
    CMD_GET_TX_DEBUG_SNAPSHOT = 72,
    CMD_GET_TX_DEBUG_SNAPSHOT_RESP = 73,
    CMD_SET_BAUDRATE = 74,
    CMD_SET_BAUDRATE_RESP = 75,
    CMD_XOFF = 78,
    CMD_XON = 79,
    CMD_SET_PIN_MODE = 80,
    CMD_DIGITAL_WRITE = 81,
    CMD_ANALOG_WRITE = 82,
    CMD_DIGITAL_READ = 83,
    CMD_ANALOG_READ = 84,
    CMD_DIGITAL_READ_RESP = 85,
    CMD_ANALOG_READ_RESP = 86,
    CMD_CONSOLE_WRITE = 96,
    CMD_DATASTORE_PUT = 112,
    CMD_DATASTORE_GET = 113,
    CMD_DATASTORE_GET_RESP = 114,
    CMD_MAILBOX_READ = 128,
    CMD_MAILBOX_PROCESSED = 129,
    CMD_MAILBOX_AVAILABLE = 130,
    CMD_MAILBOX_PUSH = 131,
    CMD_MAILBOX_READ_RESP = 132,
    CMD_MAILBOX_AVAILABLE_RESP = 133,
    CMD_FILE_WRITE = 144,
    CMD_FILE_READ = 145,
    CMD_FILE_REMOVE = 146,
    CMD_FILE_READ_RESP = 147,
    CMD_PROCESS_RUN = 160,
    CMD_PROCESS_RUN_ASYNC = 161,
    CMD_PROCESS_POLL = 162,
    CMD_PROCESS_KILL = 163,
    CMD_PROCESS_RUN_RESP = 164,
    CMD_PROCESS_RUN_ASYNC_RESP = 165,
    CMD_PROCESS_POLL_RESP = 166,
};


constexpr uint8_t to_underlying(StatusCode value) {
    return static_cast<uint8_t>(value);
}

constexpr uint16_t to_underlying(CommandId value) {
    return static_cast<uint16_t>(value);
}
} // namespace rpc
#endif
