"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _Command:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CommandEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Command.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CMD_INVALID: _Command.ValueType  # 0
    CMD_GET_VERSION: _Command.ValueType  # 64
    """System Commands (0x40-0x4F)"""
    CMD_GET_VERSION_RESP: _Command.ValueType  # 65
    CMD_GET_FREE_MEMORY: _Command.ValueType  # 66
    CMD_GET_FREE_MEMORY_RESP: _Command.ValueType  # 67
    CMD_LINK_SYNC: _Command.ValueType  # 68
    CMD_LINK_SYNC_RESP: _Command.ValueType  # 69
    CMD_LINK_RESET: _Command.ValueType  # 70
    CMD_LINK_RESET_RESP: _Command.ValueType  # 71
    CMD_GET_CAPABILITIES: _Command.ValueType  # 72
    CMD_GET_CAPABILITIES_RESP: _Command.ValueType  # 73
    CMD_SET_BAUDRATE: _Command.ValueType  # 74
    CMD_SET_BAUDRATE_RESP: _Command.ValueType  # 75
    CMD_ENTER_BOOTLOADER: _Command.ValueType  # 76
    CMD_XOFF: _Command.ValueType  # 78
    CMD_XON: _Command.ValueType  # 79
    CMD_SET_PIN_MODE: _Command.ValueType  # 80
    """GPIO Commands (0x50-0x5F)"""
    CMD_DIGITAL_WRITE: _Command.ValueType  # 81
    CMD_ANALOG_WRITE: _Command.ValueType  # 82
    CMD_DIGITAL_READ: _Command.ValueType  # 83
    CMD_ANALOG_READ: _Command.ValueType  # 84
    CMD_DIGITAL_READ_RESP: _Command.ValueType  # 85
    CMD_ANALOG_READ_RESP: _Command.ValueType  # 86
    CMD_CONSOLE_WRITE: _Command.ValueType  # 96
    """Console (0x60)"""
    CMD_DATASTORE_PUT: _Command.ValueType  # 112
    """Datastore (0x70)"""
    CMD_DATASTORE_GET: _Command.ValueType  # 113
    CMD_DATASTORE_GET_RESP: _Command.ValueType  # 114
    CMD_MAILBOX_READ: _Command.ValueType  # 128
    """Mailbox (0x80)"""
    CMD_MAILBOX_PROCESSED: _Command.ValueType  # 129
    CMD_MAILBOX_AVAILABLE: _Command.ValueType  # 130
    CMD_MAILBOX_PUSH: _Command.ValueType  # 131
    CMD_MAILBOX_READ_RESP: _Command.ValueType  # 132
    CMD_MAILBOX_AVAILABLE_RESP: _Command.ValueType  # 133
    CMD_FILE_WRITE: _Command.ValueType  # 144
    """Filesystem (0x90)"""
    CMD_FILE_READ: _Command.ValueType  # 145
    CMD_FILE_REMOVE: _Command.ValueType  # 146
    CMD_FILE_READ_RESP: _Command.ValueType  # 147
    CMD_PROCESS_RUN_ASYNC: _Command.ValueType  # 161
    """Process (0xA0)"""
    CMD_PROCESS_POLL: _Command.ValueType  # 162
    CMD_PROCESS_KILL: _Command.ValueType  # 163
    CMD_PROCESS_RUN_ASYNC_RESP: _Command.ValueType  # 165
    CMD_PROCESS_POLL_RESP: _Command.ValueType  # 166
    CMD_SPI_BEGIN: _Command.ValueType  # 176
    """SPI (0xB0)"""
    CMD_SPI_TRANSFER: _Command.ValueType  # 177
    CMD_SPI_TRANSFER_RESP: _Command.ValueType  # 178
    CMD_SPI_END: _Command.ValueType  # 179
    CMD_SPI_SET_CONFIG: _Command.ValueType  # 180

class Command(_Command, metaclass=_CommandEnumTypeWrapper): ...

CMD_INVALID: Command.ValueType  # 0
CMD_GET_VERSION: Command.ValueType  # 64
"""System Commands (0x40-0x4F)"""
CMD_GET_VERSION_RESP: Command.ValueType  # 65
CMD_GET_FREE_MEMORY: Command.ValueType  # 66
CMD_GET_FREE_MEMORY_RESP: Command.ValueType  # 67
CMD_LINK_SYNC: Command.ValueType  # 68
CMD_LINK_SYNC_RESP: Command.ValueType  # 69
CMD_LINK_RESET: Command.ValueType  # 70
CMD_LINK_RESET_RESP: Command.ValueType  # 71
CMD_GET_CAPABILITIES: Command.ValueType  # 72
CMD_GET_CAPABILITIES_RESP: Command.ValueType  # 73
CMD_SET_BAUDRATE: Command.ValueType  # 74
CMD_SET_BAUDRATE_RESP: Command.ValueType  # 75
CMD_ENTER_BOOTLOADER: Command.ValueType  # 76
CMD_XOFF: Command.ValueType  # 78
CMD_XON: Command.ValueType  # 79
CMD_SET_PIN_MODE: Command.ValueType  # 80
"""GPIO Commands (0x50-0x5F)"""
CMD_DIGITAL_WRITE: Command.ValueType  # 81
CMD_ANALOG_WRITE: Command.ValueType  # 82
CMD_DIGITAL_READ: Command.ValueType  # 83
CMD_ANALOG_READ: Command.ValueType  # 84
CMD_DIGITAL_READ_RESP: Command.ValueType  # 85
CMD_ANALOG_READ_RESP: Command.ValueType  # 86
CMD_CONSOLE_WRITE: Command.ValueType  # 96
"""Console (0x60)"""
CMD_DATASTORE_PUT: Command.ValueType  # 112
"""Datastore (0x70)"""
CMD_DATASTORE_GET: Command.ValueType  # 113
CMD_DATASTORE_GET_RESP: Command.ValueType  # 114
CMD_MAILBOX_READ: Command.ValueType  # 128
"""Mailbox (0x80)"""
CMD_MAILBOX_PROCESSED: Command.ValueType  # 129
CMD_MAILBOX_AVAILABLE: Command.ValueType  # 130
CMD_MAILBOX_PUSH: Command.ValueType  # 131
CMD_MAILBOX_READ_RESP: Command.ValueType  # 132
CMD_MAILBOX_AVAILABLE_RESP: Command.ValueType  # 133
CMD_FILE_WRITE: Command.ValueType  # 144
"""Filesystem (0x90)"""
CMD_FILE_READ: Command.ValueType  # 145
CMD_FILE_REMOVE: Command.ValueType  # 146
CMD_FILE_READ_RESP: Command.ValueType  # 147
CMD_PROCESS_RUN_ASYNC: Command.ValueType  # 161
"""Process (0xA0)"""
CMD_PROCESS_POLL: Command.ValueType  # 162
CMD_PROCESS_KILL: Command.ValueType  # 163
CMD_PROCESS_RUN_ASYNC_RESP: Command.ValueType  # 165
CMD_PROCESS_POLL_RESP: Command.ValueType  # 166
CMD_SPI_BEGIN: Command.ValueType  # 176
"""SPI (0xB0)"""
CMD_SPI_TRANSFER: Command.ValueType  # 177
CMD_SPI_TRANSFER_RESP: Command.ValueType  # 178
CMD_SPI_END: Command.ValueType  # 179
CMD_SPI_SET_CONFIG: Command.ValueType  # 180
Global___Command: _TypeAlias = Command  # noqa: Y015

class _Status:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Status.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    STATUS_INVALID: _Status.ValueType  # 0
    OK: _Status.ValueType  # 48
    ERROR: _Status.ValueType  # 49
    CMD_UNKNOWN: _Status.ValueType  # 50
    MALFORMED: _Status.ValueType  # 51
    OVERFLOW: _Status.ValueType  # 52
    CRC_MISMATCH: _Status.ValueType  # 53
    TIMEOUT: _Status.ValueType  # 54
    NOT_IMPLEMENTED: _Status.ValueType  # 55
    ACK: _Status.ValueType  # 56

class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...

STATUS_INVALID: Status.ValueType  # 0
OK: Status.ValueType  # 48
ERROR: Status.ValueType  # 49
CMD_UNKNOWN: Status.ValueType  # 50
MALFORMED: Status.ValueType  # 51
OVERFLOW: Status.ValueType  # 52
CRC_MISMATCH: Status.ValueType  # 53
TIMEOUT: Status.ValueType  # 54
NOT_IMPLEMENTED: Status.ValueType  # 55
ACK: Status.ValueType  # 56
Global___Status: _TypeAlias = Status  # noqa: Y015

@_typing.final
class VersionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MAJOR_FIELD_NUMBER: _builtins.int
    MINOR_FIELD_NUMBER: _builtins.int
    PATCH_FIELD_NUMBER: _builtins.int
    major: _builtins.int
    minor: _builtins.int
    patch: _builtins.int
    def __init__(
        self,
        *,
        major: _builtins.int = ...,
        minor: _builtins.int = ...,
        patch: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["major", b"major", "minor", b"minor", "patch", b"patch"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VersionResponse: _TypeAlias = VersionResponse  # noqa: Y015

@_typing.final
class FreeMemoryResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.int
    def __init__(
        self,
        *,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FreeMemoryResponse: _TypeAlias = FreeMemoryResponse  # noqa: Y015

@_typing.final
class Capabilities(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VER_FIELD_NUMBER: _builtins.int
    ARCH_FIELD_NUMBER: _builtins.int
    DIG_FIELD_NUMBER: _builtins.int
    ANA_FIELD_NUMBER: _builtins.int
    WATCHDOG_FIELD_NUMBER: _builtins.int
    RLE_FIELD_NUMBER: _builtins.int
    DEBUG_FRAMES_FIELD_NUMBER: _builtins.int
    DEBUG_IO_FIELD_NUMBER: _builtins.int
    EEPROM_FIELD_NUMBER: _builtins.int
    DAC_FIELD_NUMBER: _builtins.int
    HW_SERIAL1_FIELD_NUMBER: _builtins.int
    FPU_FIELD_NUMBER: _builtins.int
    LOGIC_3V3_FIELD_NUMBER: _builtins.int
    BIG_BUFFER_FIELD_NUMBER: _builtins.int
    I2C_FIELD_NUMBER: _builtins.int
    SPI_FIELD_NUMBER: _builtins.int
    SD_FIELD_NUMBER: _builtins.int
    ver: _builtins.int
    arch: _builtins.int
    dig: _builtins.int
    ana: _builtins.int
    watchdog: _builtins.bool
    rle: _builtins.bool
    debug_frames: _builtins.bool
    debug_io: _builtins.bool
    eeprom: _builtins.bool
    dac: _builtins.bool
    hw_serial1: _builtins.bool
    fpu: _builtins.bool
    logic_3v3: _builtins.bool
    big_buffer: _builtins.bool
    i2c: _builtins.bool
    spi: _builtins.bool
    sd: _builtins.bool
    def __init__(
        self,
        *,
        ver: _builtins.int = ...,
        arch: _builtins.int = ...,
        dig: _builtins.int = ...,
        ana: _builtins.int = ...,
        watchdog: _builtins.bool = ...,
        rle: _builtins.bool = ...,
        debug_frames: _builtins.bool = ...,
        debug_io: _builtins.bool = ...,
        eeprom: _builtins.bool = ...,
        dac: _builtins.bool = ...,
        hw_serial1: _builtins.bool = ...,
        fpu: _builtins.bool = ...,
        logic_3v3: _builtins.bool = ...,
        big_buffer: _builtins.bool = ...,
        i2c: _builtins.bool = ...,
        spi: _builtins.bool = ...,
        sd: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ana", b"ana", "arch", b"arch", "big_buffer", b"big_buffer", "dac", b"dac", "debug_frames", b"debug_frames", "debug_io", b"debug_io", "dig", b"dig", "eeprom", b"eeprom", "fpu", b"fpu", "hw_serial1", b"hw_serial1", "i2c", b"i2c", "logic_3v3", b"logic_3v3", "rle", b"rle", "sd", b"sd", "spi", b"spi", "ver", b"ver", "watchdog", b"watchdog"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Capabilities: _TypeAlias = Capabilities  # noqa: Y015

@_typing.final
class PinMode(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PIN_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    pin: _builtins.int
    mode: _builtins.int
    def __init__(
        self,
        *,
        pin: _builtins.int = ...,
        mode: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["mode", b"mode", "pin", b"pin"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PinMode: _TypeAlias = PinMode  # noqa: Y015

@_typing.final
class DigitalWrite(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PIN_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    pin: _builtins.int
    value: _builtins.int
    def __init__(
        self,
        *,
        pin: _builtins.int = ...,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pin", b"pin", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DigitalWrite: _TypeAlias = DigitalWrite  # noqa: Y015

@_typing.final
class AnalogWrite(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PIN_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    pin: _builtins.int
    value: _builtins.int
    def __init__(
        self,
        *,
        pin: _builtins.int = ...,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pin", b"pin", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AnalogWrite: _TypeAlias = AnalogWrite  # noqa: Y015

@_typing.final
class PinRead(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PIN_FIELD_NUMBER: _builtins.int
    pin: _builtins.int
    def __init__(
        self,
        *,
        pin: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pin", b"pin"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PinRead: _TypeAlias = PinRead  # noqa: Y015

@_typing.final
class DigitalReadResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.int
    def __init__(
        self,
        *,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DigitalReadResponse: _TypeAlias = DigitalReadResponse  # noqa: Y015

@_typing.final
class AnalogReadResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.int
    def __init__(
        self,
        *,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AnalogReadResponse: _TypeAlias = AnalogReadResponse  # noqa: Y015

@_typing.final
class ConsoleWrite(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ConsoleWrite: _TypeAlias = ConsoleWrite  # noqa: Y015

@_typing.final
class DatastorePut(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.bytes
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DatastorePut: _TypeAlias = DatastorePut  # noqa: Y015

@_typing.final
class DatastoreGet(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DatastoreGet: _TypeAlias = DatastoreGet  # noqa: Y015

@_typing.final
class DatastoreGetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.bytes
    def __init__(
        self,
        *,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DatastoreGetResponse: _TypeAlias = DatastoreGetResponse  # noqa: Y015

@_typing.final
class MailboxPush(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MailboxPush: _TypeAlias = MailboxPush  # noqa: Y015

@_typing.final
class MailboxProcessed(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_ID_FIELD_NUMBER: _builtins.int
    message_id: _builtins.int
    def __init__(
        self,
        *,
        message_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message_id", b"message_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MailboxProcessed: _TypeAlias = MailboxProcessed  # noqa: Y015

@_typing.final
class MailboxAvailableResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COUNT_FIELD_NUMBER: _builtins.int
    count: _builtins.int
    def __init__(
        self,
        *,
        count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MailboxAvailableResponse: _TypeAlias = MailboxAvailableResponse  # noqa: Y015

@_typing.final
class MailboxReadResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONTENT_FIELD_NUMBER: _builtins.int
    content: _builtins.bytes
    def __init__(
        self,
        *,
        content: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MailboxReadResponse: _TypeAlias = MailboxReadResponse  # noqa: Y015

@_typing.final
class FileWrite(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PATH_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    data: _builtins.bytes
    def __init__(
        self,
        *,
        path: _builtins.str = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "path", b"path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FileWrite: _TypeAlias = FileWrite  # noqa: Y015

@_typing.final
class FileRead(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PATH_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    def __init__(
        self,
        *,
        path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["path", b"path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FileRead: _TypeAlias = FileRead  # noqa: Y015

@_typing.final
class FileRemove(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PATH_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    def __init__(
        self,
        *,
        path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["path", b"path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FileRemove: _TypeAlias = FileRemove  # noqa: Y015

@_typing.final
class FileReadResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONTENT_FIELD_NUMBER: _builtins.int
    content: _builtins.bytes
    def __init__(
        self,
        *,
        content: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FileReadResponse: _TypeAlias = FileReadResponse  # noqa: Y015

@_typing.final
class ProcessRunAsync(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMMAND_FIELD_NUMBER: _builtins.int
    command: _builtins.str
    def __init__(
        self,
        *,
        command: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command", b"command"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProcessRunAsync: _TypeAlias = ProcessRunAsync  # noqa: Y015

@_typing.final
class ProcessRunAsyncResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PID_FIELD_NUMBER: _builtins.int
    pid: _builtins.int
    def __init__(
        self,
        *,
        pid: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pid", b"pid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProcessRunAsyncResponse: _TypeAlias = ProcessRunAsyncResponse  # noqa: Y015

@_typing.final
class ProcessPoll(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PID_FIELD_NUMBER: _builtins.int
    pid: _builtins.int
    def __init__(
        self,
        *,
        pid: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pid", b"pid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProcessPoll: _TypeAlias = ProcessPoll  # noqa: Y015

@_typing.final
class ProcessPollResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    EXIT_CODE_FIELD_NUMBER: _builtins.int
    STDOUT_DATA_FIELD_NUMBER: _builtins.int
    STDERR_DATA_FIELD_NUMBER: _builtins.int
    FINISHED_FIELD_NUMBER: _builtins.int
    STDOUT_TRUNCATED_FIELD_NUMBER: _builtins.int
    STDERR_TRUNCATED_FIELD_NUMBER: _builtins.int
    status: _builtins.int
    exit_code: _builtins.int
    stdout_data: _builtins.bytes
    stderr_data: _builtins.bytes
    finished: _builtins.bool
    stdout_truncated: _builtins.bool
    stderr_truncated: _builtins.bool
    def __init__(
        self,
        *,
        status: _builtins.int = ...,
        exit_code: _builtins.int = ...,
        stdout_data: _builtins.bytes = ...,
        stderr_data: _builtins.bytes = ...,
        finished: _builtins.bool = ...,
        stdout_truncated: _builtins.bool = ...,
        stderr_truncated: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["exit_code", b"exit_code", "finished", b"finished", "status", b"status", "stderr_data", b"stderr_data", "stderr_truncated", b"stderr_truncated", "stdout_data", b"stdout_data", "stdout_truncated", b"stdout_truncated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProcessPollResponse: _TypeAlias = ProcessPollResponse  # noqa: Y015

@_typing.final
class ProcessKill(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PID_FIELD_NUMBER: _builtins.int
    pid: _builtins.int
    def __init__(
        self,
        *,
        pid: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pid", b"pid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProcessKill: _TypeAlias = ProcessKill  # noqa: Y015

@_typing.final
class GenericResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    status: _builtins.str
    message: _builtins.str
    def __init__(
        self,
        *,
        status: _builtins.str = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GenericResponse: _TypeAlias = GenericResponse  # noqa: Y015

@_typing.final
class StructuredEntry(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    STRING_VALUE_FIELD_NUMBER: _builtins.int
    BYTES_VALUE_FIELD_NUMBER: _builtins.int
    BOOL_VALUE_FIELD_NUMBER: _builtins.int
    INT_VALUE_FIELD_NUMBER: _builtins.int
    FLOAT_VALUE_FIELD_NUMBER: _builtins.int
    NULL_VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    string_value: _builtins.str
    bytes_value: _builtins.bytes
    bool_value: _builtins.bool
    int_value: _builtins.int
    float_value: _builtins.float
    null_value: _builtins.bool
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        string_value: _builtins.str = ...,
        bytes_value: _builtins.bytes = ...,
        bool_value: _builtins.bool = ...,
        int_value: _builtins.int = ...,
        float_value: _builtins.float = ...,
        null_value: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "bytes_value", b"bytes_value", "float_value", b"float_value", "int_value", b"int_value", "null_value", b"null_value", "string_value", b"string_value", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "bytes_value", b"bytes_value", "float_value", b"float_value", "int_value", b"int_value", "key", b"key", "null_value", b"null_value", "string_value", b"string_value", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["string_value", "bytes_value", "bool_value", "int_value", "float_value", "null_value"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___StructuredEntry: _TypeAlias = StructuredEntry  # noqa: Y015

@_typing.final
class StructuredPayload(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___StructuredEntry]: ...
    def __init__(
        self,
        *,
        entries: _abc.Iterable[Global___StructuredEntry] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entries", b"entries"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StructuredPayload: _TypeAlias = StructuredPayload  # noqa: Y015

@_typing.final
class AckPacket(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMMAND_ID_FIELD_NUMBER: _builtins.int
    command_id: _builtins.int
    def __init__(
        self,
        *,
        command_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command_id", b"command_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AckPacket: _TypeAlias = AckPacket  # noqa: Y015

@_typing.final
class HandshakeConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ACK_TIMEOUT_MS_FIELD_NUMBER: _builtins.int
    ACK_RETRY_LIMIT_FIELD_NUMBER: _builtins.int
    RESPONSE_TIMEOUT_MS_FIELD_NUMBER: _builtins.int
    ack_timeout_ms: _builtins.int
    ack_retry_limit: _builtins.int
    response_timeout_ms: _builtins.int
    def __init__(
        self,
        *,
        ack_timeout_ms: _builtins.int = ...,
        ack_retry_limit: _builtins.int = ...,
        response_timeout_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ack_retry_limit", b"ack_retry_limit", "ack_timeout_ms", b"ack_timeout_ms", "response_timeout_ms", b"response_timeout_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HandshakeConfig: _TypeAlias = HandshakeConfig  # noqa: Y015

@_typing.final
class SetBaudratePacket(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BAUDRATE_FIELD_NUMBER: _builtins.int
    baudrate: _builtins.int
    def __init__(
        self,
        *,
        baudrate: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["baudrate", b"baudrate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetBaudratePacket: _TypeAlias = SetBaudratePacket  # noqa: Y015

@_typing.final
class LinkSync(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NONCE_FIELD_NUMBER: _builtins.int
    TAG_FIELD_NUMBER: _builtins.int
    nonce: _builtins.bytes
    tag: _builtins.bytes
    def __init__(
        self,
        *,
        nonce: _builtins.bytes = ...,
        tag: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["nonce", b"nonce", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LinkSync: _TypeAlias = LinkSync  # noqa: Y015

@_typing.final
class EnterBootloader(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MAGIC_FIELD_NUMBER: _builtins.int
    magic: _builtins.int
    def __init__(
        self,
        *,
        magic: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["magic", b"magic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EnterBootloader: _TypeAlias = EnterBootloader  # noqa: Y015

@_typing.final
class SpiTransfer(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SpiTransfer: _TypeAlias = SpiTransfer  # noqa: Y015

@_typing.final
class SpiTransferResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SpiTransferResponse: _TypeAlias = SpiTransferResponse  # noqa: Y015

@_typing.final
class SpiConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BIT_ORDER_FIELD_NUMBER: _builtins.int
    DATA_MODE_FIELD_NUMBER: _builtins.int
    FREQUENCY_FIELD_NUMBER: _builtins.int
    bit_order: _builtins.int
    data_mode: _builtins.int
    frequency: _builtins.int
    def __init__(
        self,
        *,
        bit_order: _builtins.int = ...,
        data_mode: _builtins.int = ...,
        frequency: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bit_order", b"bit_order", "data_mode", b"data_mode", "frequency", b"frequency"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SpiConfig: _TypeAlias = SpiConfig  # noqa: Y015

@_typing.final
class RpcEnvelope(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VERSION_FIELD_NUMBER: _builtins.int
    COMMAND_ID_FIELD_NUMBER: _builtins.int
    SEQUENCE_ID_FIELD_NUMBER: _builtins.int
    NONCE_FIELD_NUMBER: _builtins.int
    TAG_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    version: _builtins.int
    command_id: _builtins.int
    sequence_id: _builtins.int
    nonce: _builtins.bytes
    tag: _builtins.bytes
    payload: _builtins.bytes
    def __init__(
        self,
        *,
        version: _builtins.int = ...,
        command_id: _builtins.int = ...,
        sequence_id: _builtins.int = ...,
        nonce: _builtins.bytes = ...,
        tag: _builtins.bytes = ...,
        payload: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command_id", b"command_id", "nonce", b"nonce", "payload", b"payload", "sequence_id", b"sequence_id", "tag", b"tag", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RpcEnvelope: _TypeAlias = RpcEnvelope  # noqa: Y015
