"""Shared constants for Yun Bridge daemon components."""
from __future__ import annotations

from ssl import TLSVersion


SERIAL_TERMINATOR: bytes = b"\x00"
STATUS_FILE_PATH: str = "/tmp/yunbridge_status.json"
ALLOWED_COMMAND_WILDCARD: str = "*"
MQTT_TLS_MIN_VERSION: TLSVersion = TLSVersion.TLSv1_2

DEFAULT_SERIAL_PORT: str = "/dev/ttyATH0"
DEFAULT_SERIAL_BAUD: int = 115200
DEFAULT_MQTT_HOST: str = "127.0.0.1"
DEFAULT_MQTT_PORT: int = 8883
DEFAULT_MQTT_TOPIC: str = "br"
DEFAULT_MQTT_CAFILE: str = "/etc/ssl/certs/ca-certificates.crt"
DEFAULT_FILE_SYSTEM_ROOT: str = "/root/yun_files"
DEFAULT_PROCESS_TIMEOUT: int = 10
DEFAULT_MQTT_QUEUE_LIMIT: int = 256
DEFAULT_RECONNECT_DELAY: int = 5
DEFAULT_STATUS_INTERVAL: int = 5
DEFAULT_CONSOLE_QUEUE_LIMIT_BYTES: int = 16384
DEFAULT_MAILBOX_QUEUE_LIMIT: int = 64
DEFAULT_MAILBOX_QUEUE_BYTES_LIMIT: int = 65536
DEFAULT_SERIAL_RETRY_TIMEOUT: float = 0.75
DEFAULT_SERIAL_RESPONSE_TIMEOUT: float = 3.0
DEFAULT_SERIAL_RETRY_ATTEMPTS: int = 3
SERIAL_NONCE_LENGTH: int = 16
MIN_SERIAL_SHARED_SECRET_LEN: int = 8
DEFAULT_SERIAL_SHARED_SECRET: bytes = b"changeme123"

TOPIC_ANALOG: str = "a"
TOPIC_CONSOLE: str = "console"
TOPIC_DATASTORE: str = "datastore"
TOPIC_DIGITAL: str = "d"
TOPIC_FILE: str = "file"
TOPIC_MAILBOX: str = "mailbox"
TOPIC_MAILBOX_INCOMING_AVAILABLE: str = "mailbox/incoming_available"
TOPIC_MAILBOX_OUTGOING_AVAILABLE: str = "mailbox/outgoing_available"
TOPIC_SHELL: str = "sh"
TOPIC_STATUS: str = "status"
TOPIC_SYSTEM: str = "system"

WATCHDOG_TRIGGER_TOKEN: bytes = b"WATCHDOG=trigger\n"
DEFAULT_WATCHDOG_INTERVAL: float = 5.0

__all__ = [
    "SERIAL_TERMINATOR",
    "STATUS_FILE_PATH",
    "ALLOWED_COMMAND_WILDCARD",
    "MQTT_TLS_MIN_VERSION",
    "DEFAULT_SERIAL_PORT",
    "DEFAULT_SERIAL_BAUD",
    "DEFAULT_MQTT_HOST",
    "DEFAULT_MQTT_PORT",
    "DEFAULT_MQTT_TOPIC",
    "DEFAULT_MQTT_CAFILE",
    "DEFAULT_FILE_SYSTEM_ROOT",
    "DEFAULT_PROCESS_TIMEOUT",
    "DEFAULT_MQTT_QUEUE_LIMIT",
    "DEFAULT_RECONNECT_DELAY",
    "DEFAULT_STATUS_INTERVAL",
    "DEFAULT_CONSOLE_QUEUE_LIMIT_BYTES",
    "DEFAULT_MAILBOX_QUEUE_LIMIT",
    "DEFAULT_MAILBOX_QUEUE_BYTES_LIMIT",
    "DEFAULT_SERIAL_RETRY_TIMEOUT",
    "DEFAULT_SERIAL_RESPONSE_TIMEOUT",
    "DEFAULT_SERIAL_RETRY_ATTEMPTS",
    "SERIAL_NONCE_LENGTH",
    "MIN_SERIAL_SHARED_SECRET_LEN",
    "DEFAULT_SERIAL_SHARED_SECRET",
    "TOPIC_ANALOG",
    "TOPIC_CONSOLE",
    "TOPIC_DATASTORE",
    "TOPIC_DIGITAL",
    "TOPIC_FILE",
    "TOPIC_MAILBOX",
    "TOPIC_MAILBOX_INCOMING_AVAILABLE",
    "TOPIC_MAILBOX_OUTGOING_AVAILABLE",
    "TOPIC_SHELL",
    "TOPIC_STATUS",
    "TOPIC_SYSTEM",
    "WATCHDOG_TRIGGER_TOKEN",
    "DEFAULT_WATCHDOG_INTERVAL",
]
