"""Shared constants for Yun Bridge daemon components.

This file is the central registry for **application defaults** (paths, limits,
intervals) used when the OpenWrt UCI configuration is missing or incomplete.

Layers:
- `yunbridge.rpc.protocol`: Generated byte-level contract (source of truth).
- `yunbridge.const`: Application defaults.
- `yunbridge.config.settings`: Runtime configuration loaded from UCI/defaults.
"""

from __future__ import annotations

from ssl import TLSVersion

from .rpc.protocol import Status

# ==============================================================================
# SECTION 1: STATUS CODES (Application Logic)
# ==============================================================================

# -- Status Codes --
SERIAL_FAILURE_STATUS_CODES: frozenset[int] = frozenset(
    {
        Status.ERROR.value,
        Status.CMD_UNKNOWN.value,
        Status.MALFORMED.value,
        Status.CRC_MISMATCH.value,
        Status.TIMEOUT.value,
        Status.NOT_IMPLEMENTED.value,
    }
)
SERIAL_SUCCESS_STATUS_CODES: frozenset[int] = frozenset({Status.OK.value})


# ==============================================================================
# SECTION 2: APPLICATION DEFAULTS
# ==============================================================================
# These values define the default behavior of the Python daemon.
# They can usually be overridden by UCI configuration or Environment Variables.

# -- Serial Port Defaults --
DEFAULT_SERIAL_PORT: str = "/dev/ttyATH0"
# Initial wait for serial port availability (reconnect loop)
DEFAULT_RECONNECT_DELAY: int = 5
# Timeout for general serial operations (not strict RPC)
DEFAULT_SERIAL_RETRY_TIMEOUT: float = 0.75
DEFAULT_SERIAL_RESPONSE_TIMEOUT: float = 3.0
DEFAULT_SERIAL_HANDSHAKE_MIN_INTERVAL: float = 0.0
# How many fatal handshake failures before restarting the serial task
DEFAULT_SERIAL_HANDSHAKE_FATAL_FAILURES: int = 3
# Backoff strategy for handshake retries
SERIAL_HANDSHAKE_BACKOFF_BASE: float = 1.0
SERIAL_HANDSHAKE_BACKOFF_MAX: float = 60.0
SERIAL_MIN_ACK_TIMEOUT: float = 0.05

# -- MQTT Defaults --
DEFAULT_MQTT_HOST: str = "127.0.0.1"
DEFAULT_MQTT_PORT: int = 8883
DEFAULT_MQTT_TOPIC: str = "br"
DEFAULT_MQTT_CAFILE: str = "/etc/ssl/certs/ca-certificates.crt"
DEFAULT_MQTT_QUEUE_LIMIT: int = 256
MQTT_TLS_MIN_VERSION: TLSVersion = TLSVersion.TLSv1_2
# [CRITICAL] Spool directory in RAM to prevent Flash wear
DEFAULT_MQTT_SPOOL_DIR: str = "/tmp/yunbridge/spool"

# -- File System Defaults --
DEFAULT_FILE_SYSTEM_ROOT: str = "/tmp/yun_files"
DEFAULT_FILE_WRITE_MAX_BYTES: int = 262144
DEFAULT_FILE_STORAGE_QUOTA_BYTES: int = 4194304

# -- Component Limits --
DEFAULT_PROCESS_TIMEOUT: int = 10
DEFAULT_PROCESS_MAX_OUTPUT_BYTES: int = 65536
DEFAULT_PROCESS_MAX_CONCURRENT: int = 4
DEFAULT_CONSOLE_QUEUE_LIMIT_BYTES: int = 16384
DEFAULT_MAILBOX_QUEUE_LIMIT: int = 64
DEFAULT_MAILBOX_QUEUE_BYTES_LIMIT: int = 65536
DEFAULT_PENDING_PIN_REQUESTS: int = 32

# -- Telemetry & Status --
STATUS_FILE_PATH: str = "/tmp/yunbridge_status.json"
DEFAULT_STATUS_INTERVAL: int = 5
DEFAULT_BRIDGE_SUMMARY_INTERVAL: int = 60
DEFAULT_BRIDGE_HANDSHAKE_INTERVAL: int = 300
DEFAULT_METRICS_HOST: str = "127.0.0.1"
DEFAULT_METRICS_PORT: int = 9130

# -- Security --
MIN_SERIAL_SHARED_SECRET_LEN: int = 8
# SECURITY WARNING: This default secret is for initial setup only.
# It MUST be rotated using 'yunbridge-rotate-credentials' before production use.
DEFAULT_SERIAL_SHARED_SECRET: bytes | None = None
ALLOWED_COMMAND_WILDCARD: str = "*"
TOPIC_FORBIDDEN_REASON: str = "topic-action-forbidden"

# -- Watchdog --
WATCHDOG_TRIGGER_TOKEN: bytes = b"WATCHDOG=trigger\n"
DEFAULT_WATCHDOG_INTERVAL: float = 5.0

# -- Task Supervisor --
SUPERVISOR_DEFAULT_RESTART_INTERVAL: float = 60.0
SUPERVISOR_DEFAULT_MIN_BACKOFF: float = 1.0
SUPERVISOR_DEFAULT_MAX_BACKOFF: float = 30.0


__all__ = [
    "STATUS_FILE_PATH",
    "ALLOWED_COMMAND_WILDCARD",
    "MQTT_TLS_MIN_VERSION",
    "DEFAULT_SERIAL_PORT",
    "DEFAULT_MQTT_HOST",
    "DEFAULT_MQTT_PORT",
    "DEFAULT_MQTT_TOPIC",
    "DEFAULT_MQTT_CAFILE",
    "DEFAULT_FILE_SYSTEM_ROOT",
    "DEFAULT_FILE_WRITE_MAX_BYTES",
    "DEFAULT_FILE_STORAGE_QUOTA_BYTES",
    "DEFAULT_PROCESS_TIMEOUT",
    "DEFAULT_MQTT_QUEUE_LIMIT",
    "DEFAULT_RECONNECT_DELAY",
    "DEFAULT_STATUS_INTERVAL",
    "DEFAULT_CONSOLE_QUEUE_LIMIT_BYTES",
    "DEFAULT_MAILBOX_QUEUE_LIMIT",
    "DEFAULT_MAILBOX_QUEUE_BYTES_LIMIT",
    "DEFAULT_PENDING_PIN_REQUESTS",
    "DEFAULT_SERIAL_RETRY_TIMEOUT",
    "DEFAULT_SERIAL_RESPONSE_TIMEOUT",
    "DEFAULT_SERIAL_HANDSHAKE_MIN_INTERVAL",
    "SERIAL_HANDSHAKE_BACKOFF_BASE",
    "SERIAL_HANDSHAKE_BACKOFF_MAX",
    "MIN_SERIAL_SHARED_SECRET_LEN",
    "DEFAULT_SERIAL_SHARED_SECRET",
    "DEFAULT_SERIAL_HANDSHAKE_FATAL_FAILURES",
    "SERIAL_MIN_ACK_TIMEOUT",
    "SERIAL_FAILURE_STATUS_CODES",
    "SERIAL_SUCCESS_STATUS_CODES",
    "DEFAULT_MQTT_SPOOL_DIR",
    "DEFAULT_PROCESS_MAX_OUTPUT_BYTES",
    "DEFAULT_PROCESS_MAX_CONCURRENT",
    "DEFAULT_METRICS_HOST",
    "DEFAULT_METRICS_PORT",
    "DEFAULT_BRIDGE_SUMMARY_INTERVAL",
    "DEFAULT_BRIDGE_HANDSHAKE_INTERVAL",
    "WATCHDOG_TRIGGER_TOKEN",
    "DEFAULT_WATCHDOG_INTERVAL",
    "SUPERVISOR_DEFAULT_RESTART_INTERVAL",
    "SUPERVISOR_DEFAULT_MIN_BACKOFF",
    "SUPERVISOR_DEFAULT_MAX_BACKOFF",
    "TOPIC_FORBIDDEN_REASON",
]
