# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Set up Protoc
description: 'Install Google Protocol Buffers Compiler'
inputs:
  version:
    description: 'Protoc version'
    required: false
    default: '36.2'
runs:
  using: 'composite'
  steps:
    - name: Install protoc
      shell: bash
      run: |
        PROTOC_VERSION="${{ inputs.version }}"
        PROTOC_ZIP=protoc-${PROTOC_VERSION}-linux-x86_64.zip
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/${PROTOC_ZIP}
        sudo unzip -o ${PROTOC_ZIP} -d /usr/local
        rm -f ${PROTOC_ZIP}
        protoc --version