"""Manual stub for OpenWrt UCI."""
from __future__ import annotations
from typing import Any, Optional
from types import TracebackType

class Uci:
    def __init__(self) -> None: ...
    def __enter__(self) -> Uci: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> bool: ...
    def get_all(self, package: str) -> dict[str, dict[str, Any]]: ...
    def get(self, package: str, section: str, option: str) -> Any: ...
    def set(self, package: str, section: str, option: str, value: str) -> None: ...
    def commit(self, package: str) -> None: ...

class UciException(Exception): ...
