"""Manual stub for OpenWrt UCI."""

from __future__ import annotations

from types import TracebackType
from typing import Any, Dict, Optional, overload

class Uci:
    def __init__(self) -> None: ...
    def __enter__(self) -> Uci: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> bool: ...
    @overload
    def get_all(self, package: str) -> Dict[str, Dict[str, Any]]: ...
    @overload
    def get_all(self, package: str, section: str) -> Dict[str, Any]: ...
    def get(self, package: str, section: str, option: str) -> str: ...
    def set(self, package: str, section: str, option: str, value: str) -> None: ...
    def commit(self, package: str) -> None: ...

class UciException(Exception): ...
