from typing import Any, Iterable, Sequence

__all__ = ["Collector", "GaugeMetricFamily", "InfoMetricFamily"]

class Collector:
    def collect(self) -> Iterable[Any]: ...

class GaugeMetricFamily(Collector):
    def __init__(self, name: str, documentation: str, labels: Sequence[str] | None = ...) -> None: ...
    def add_metric(self, labels: Sequence[str], value: float) -> None: ...

class InfoMetricFamily(Collector):
    def __init__(self, name: str, documentation: str, labels: Sequence[str] | None = ...) -> None: ...
    def add_metric(self, labels: Sequence[str], value: dict[str, str]) -> None: ...
