from typing import Any
from .core import Collector as Collector

class CollectorRegistry:
    def __init__(self, auto_describe: bool = ...) -> None: ...
    def register(self, collector: Collector) -> None: ...
    def unregister(self, collector: Collector) -> None: ...
