"""Type stubs for google-re2 [SIL-2]."""

from typing import Any

class Pattern:
    pattern: str
    def match(self, text: str, pos: int = ..., endpos: int = ...) -> Any: ...
    def search(self, text: str, pos: int = ..., endpos: int = ...) -> Any: ...
    def findall(self, text: str, pos: int = ..., endpos: int = ...) -> list[Any]: ...
    def finditer(self, text: str, pos: int = ..., endpos: int = ...) -> Any: ...
    def split(self, text: str, maxsplit: int = ...) -> list[str]: ...
    def sub(self, repl: Any, text: str, count: int = ...) -> str: ...
    def subn(self, repl: Any, text: str, count: int = ...) -> tuple[str, int]: ...

class Match:
    def group(self, *groups: int | str) -> Any: ...
    def groups(self, default: Any = ...) -> tuple[Any, ...]: ...
    def groupdict(self, default: Any = ...) -> dict[str, Any]: ...
    def start(self, group: int | str = ...) -> int: ...
    def end(self, group: int | str = ...) -> int: ...
    def span(self, group: int | str = ...) -> tuple[int, int]: ...

def compile(pattern: str, flags: int = ...) -> Any: ...
def match(pattern: str, text: str, flags: int = ...) -> Any: ...
def search(pattern: str, text: str, flags: int = ...) -> Any: ...
def findall(pattern: str, text: str, flags: int = ...) -> list[Any]: ...
def split(pattern: str, text: str, maxsplit: int = ..., flags: int = ...) -> list[str]: ...
def sub(pattern: str, repl: Any, text: str, count: int = ..., flags: int = ...) -> str: ...
def subn(pattern: str, repl: Any, text: str, count: int = ..., flags: int = ...) -> tuple[str, int]: ...
def escape(pattern: str) -> str: ...

__all__ = ["compile", "match", "search", "findall", "split", "sub", "subn", "escape", "Pattern", "Match"]
