"""
This type stub file was generated by pyright.
"""

import asyncio
import contextlib
import logging
import js
from typing import Any, final
from typing_extensions import Buffer
from ...common import BaseSerial, BaseSerialTransport, ModemPins, Parity, PinState, SerialException, StopBits, UnsupportedSetting, register_uri_handler
from .types import DataBits, FlowControlType, JsSerialPort, JsStreamReader, JsStreamWriter, ParityType, SerialOutputSignals, StopBits as JsStopBits

"""Pyodide serial port implementation using the Web Serial API.

Under `Pyodide <https://pyodide.org/>`_ this module registers a transport for the
``pyodide://`` URI scheme (and for scheme-less ``device://`` fallbacks), backed by
the browser's `Web Serial API
<https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API>`_. Only the async
transport :class:`PyodideSerialTransport` is implemented; there is no synchronous
:class:`~serialx.common.BaseSerial` equivalent because Web Serial is promise-based.

Because ``navigator.serial.requestPort()`` must be called in response to a user
gesture from JavaScript, the JS ``SerialPort`` object cannot be obtained from Python.
Instead, the host page obtains a ``SerialPort`` and hands it to Python via
:func:`register_js_port`, associating it with a URI path. Subsequent calls to
:func:`serialx.open_serial_connection` (or the lower-level transport) look the path
up in the registry. A ``SerialPort`` may also be passed directly via the ``js_port``
keyword argument, bypassing the registry.

See :doc:`/how-to/pyodide` for a more complete example.
"""
_LOGGER = ...
_REGISTERED_JS_PORTS: dict[str, JsSerialPort] = ...
_SERIAL_PORT_CLOSING_TASKS: set[asyncio.Task[None]] = ...
def register_js_port(path: str, js_port: JsSerialPort) -> None:
    """Associate a URL with a JS `SerialPort` for later connection."""
    ...

def unregister_js_port(path: str) -> None:
    """Remove the entry for `path` from the JS port registry, if any."""
    ...

_PARITY_MAP: dict[Parity, ParityType] = ...
_STOPBITS_MAP: dict[StopBits, JsStopBits] = ...
@final
class ExitSentinel:
    """A sentinel object to signal writer loop exit."""
    ...


class PyodideSerial(BaseSerial):
    """Synchronous serial port implementation for Pyodide."""
    def num_unread_bytes(self) -> int:
        """Return the number of bytes in the read buffer."""
        ...
    
    def num_unwritten_bytes(self) -> int:
        """Return the number of bytes in the write buffer."""
        ...
    
    @property
    def is_open(self) -> bool:
        """Return whether the port is open."""
        ...
    


class PyodideSerialTransport(BaseSerialTransport):
    """Async serial transport for Pyodide using the Web Serial API."""
    transport_name = ...
    _serial: PyodideSerial
    def __init__(self, loop: asyncio.AbstractEventLoop, protocol: asyncio.Protocol) -> None:
        """Initialize the Pyodide serial transport.

        .. warning::
            The Web Serial API does not support software flow control (XON/XOFF).
            Passing ``xonxoff=True`` to :meth:`connect` is accepted for compatibility
            but is silently ignored; a warning is logged. Only hardware flow control
            (RTS/CTS) is honored.
        """
        ...
    
    def write(self, data: bytes | bytearray | memoryview) -> None:
        """Write data to the transport."""
        ...
    
    def get_write_buffer_size(self) -> int:
        """Return the number of bytes currently queued for writing."""
        ...
    
    def abort(self) -> None:
        """Close the transport immediately, discarding pending writes."""
        ...
    
    def __del__(self) -> None:
        """Clean up the transport if it was not properly closed."""
        ...
    
    def close(self) -> None:
        """Close the transport."""
        ...
    


