from __future__ import annotations
from collections.abc import Callable
from typing import Any

class Typer:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def command(self, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

def Option(*args: Any, **kwargs: Any) -> object: ...
def Argument(*args: Any, **kwargs: Any) -> object: ...
