"""Type stubs for openwrt_luci_rpc.exceptions."""

from __future__ import annotations

class InvalidLuciLoginError(Exception): ...
class InvalidLuciTokenError(Exception): ...
class LuciConfigError(Exception): ...
class LuciRpcMethodNotFoundError(Exception): ...
class LuciRpcUnknownError(Exception): ...
class PageNotFoundError(Exception): ...
