"""
This type stub file was generated by pyright.
"""

from construct import *
from construct.lib import *

"""
This type stub file was generated by pyright.
"""
def integer2bits(number, width, signed=...):
    r"""
    Converts an integer into its binary representation in a bit-string. Width is the amount of bits to generate. Each bit is represented as either \\x00 or \\x01. The most significant bit is first, big-endian. This is reverse to `bits2integer`.

    Examples:

        >>> integer2bits(19, 8)
        b'\x00\x00\x00\x01\x00\x00\x01\x01'
    """
    ...

def integer2bytes(number, width, signed=...):
    r"""
    Converts an integer into a byte-string. This is reverse to `bytes2integer`.

    Examples:

        >>> integer2bytes(19, 4)
        '\x00\x00\x00\x13'
    """
    ...

def bits2integer(data, signed=...):
    r"""
    Converts a bit-string into an integer. Set signed to interpret the number as a 2-s complement signed integer. This is reverse to `integer2bits`.

    Examples:

        >>> bits2integer(b"\x01\x00\x00\x01\x01")
        19
    """
    ...

def bytes2integer(data, signed=...):
    r"""
    Converts a byte-string into an integer. This is reverse to `integer2bytes`.

    Examples:

        >>> bytes2integer(b'\x00\x00\x00\x13')
        19
    """
    ...

BYTES2BITS_CACHE = ...
def bytes2bits(data):
    r""" 
    Converts between bit-string and byte-string representations, both as bytes type.

    Example:

        >>> bytes2bits(b'ab')
        b"\x00\x01\x01\x00\x00\x00\x00\x01\x00\x01\x01\x00\x00\x00\x01\x00"
    """
    ...

BITS2BYTES_CACHE = ...
def bits2bytes(data):
    r""" 
    Converts between bit-string and byte-string representations, both as bytes type. Its length must be multiple of 8.

    Example:

        >>> bits2bytes(b"\x00\x01\x01\x00\x00\x00\x00\x01\x00\x01\x01\x00\x00\x00\x01\x00")
        b'ab'
    """
    ...

def swapbytes(data):
    r"""
    Performs an endianness swap on byte-string.

    Example:

        >>> swapbytes(b'abcd')
        b'dcba'
    """
    ...

def swapbytesinbits(data):
    r"""
    Performs an byte-swap within a bit-string. Its length must be multiple of 8.

    Example:

        >>> swapbytesinbits(b'0000000011111111')
        b'1111111100000000'
    """
    ...

SWAPBITSINBYTES_CACHE = ...
def swapbitsinbytes(data):
    r"""
    Performs a bit-reversal on each byte within a byte-string.

    Example:

        >>> swapbitsinbytes(b"\xf0\x00")
        b"\x0f\x00"
    """
    ...

def hexlify(data):
    """Returns binascii.hexlify(data)."""
    ...

def unhexlify(data):
    """Returns binascii.unhexlify(data)."""
    ...

