"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class RestreamedBytesIO:
    def __init__(self, substream, decoder, decoderunit, encoder, encoderunit) -> None:
        ...
    
    def read(self, count=...):
        ...
    
    def write(self, data):
        ...
    
    def close(self):
        ...
    
    def seek(self, at, whence=...):
        ...
    
    def seekable(self):
        ...
    
    def tell(self):
        """WARNING: tell is correct only on read-only and write-only instances."""
        ...
    
    def tellable(self):
        ...
    


class RebufferedBytesIO:
    def __init__(self, substream, tailcutoff=...) -> None:
        ...
    
    def read(self, count=...):
        ...
    
    def write(self, data):
        ...
    
    def seek(self, at, whence=...):
        ...
    
    def seekable(self):
        ...
    
    def tell(self):
        ...
    
    def tellable(self):
        ...
    
    def cachedfrom(self):
        ...
    
    def cachedto(self):
        ...
    


