"""
This type stub file was generated by pyright.
"""

import sys
from construct.lib.py3compat import *

"""
This type stub file was generated by pyright.
"""
OrderedDict = dict
if sys.version_info < (3, 7):
    ...
globalPrintFullStrings = ...
globalPrintFalseFlags = ...
globalPrintPrivateEntries = ...
def setGlobalPrintFullStrings(enabled=...):
    r"""
    When enabled, Container __str__ produces full content of bytes and unicode strings, otherwise and by default, it produces truncated output (16 bytes and 32 characters).

    :param enabled: bool
    """
    ...

def setGlobalPrintFalseFlags(enabled=...):
    r"""
    When enabled, Container __str__ that was produced by FlagsEnum parsing prints all values, otherwise and by default, it prints only the values that are True.

    :param enabled: bool
    """
    ...

def setGlobalPrintPrivateEntries(enabled=...):
    r"""
    When enabled, Container __str__ shows keys like _ _index _etc, otherwise and by default, it hides those keys. __repr__ never shows private entries.

    :param enabled: bool
    """
    ...

def recursion_lock(retval=..., lock_name=...):
    """Used internally."""
    ...

class Container(OrderedDict):
    r"""
    Generic ordered dictionary that allows both key and attribute access, and preserves key order by insertion. Adding keys is preferred using \*\*entrieskw (requires Python 3.6). Equality does NOT check item order. Also provides regex searching.

    Note that not all parameters can be accessed via attribute access (dot operator). If the name of an item matches a method name of the Container, it can only be accessed via key acces (square brackets). This includes the following names: clear, copy, fromkeys, get, items, keys, move_to_end, pop, popitem, search, search_all, setdefault, update, values.

    Example::

        # empty dict
        >>> Container()
        # list of pairs, not recommended
        >>> Container([ ("name","anonymous"), ("age",21) ])
        # This syntax requires Python 3.6
        >>> Container(name="anonymous", age=21)
        # copies another dict
        >>> Container(dict2)
        >>> Container(container2)

    ::

        >>> print(repr(obj))
        Container(text='utf8 decoded string...', value=123)
        >>> print(obj)
        Container
            text = u'utf8 decoded string...' (total 22)
            value = 123
    """
    __slots__ = ...
    def __getattr__(self, name):
        ...
    
    def __setattr__(self, name, value):
        ...
    
    def __delattr__(self, name):
        ...
    
    def update(self, seqordict):
        """Appends items from another dict/Container or list-of-tuples."""
        ...
    
    def copy(self):
        ...
    
    __update__ = ...
    __copy__ = ...
    def __dir__(self):
        """For auto completion of attributes based on container values."""
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    @recursion_lock()
    def __repr__(self):
        ...
    
    @recursion_lock()
    def __str__(self) -> str:
        ...
    
    def search(self, pattern):
        """
        Searches a container (non-recursively) using regex.
        """
        ...
    
    def search_all(self, pattern):
        """
        Searches a container (recursively) using regex.
        """
        ...
    
    def __getstate__(self):
        """
        Used by pickle to serialize an instance to a dict.
        """
        ...
    
    def __setstate__(self, state):
        """
        Used by pickle to de-serialize from a dict.
        """
        ...
    


class ListContainer(list):
    r"""
    Generic container like list. Provides pretty-printing. Also provides regex searching.

    Example::

        >>> ListContainer()
        >>> ListContainer([1, 2, 3])

    ::

        >>> print(repr(obj))
        [1, 2, 3]
        >>> print(obj)
        ListContainer
            1
            2
            3
    """
    @recursion_lock()
    def __repr__(self):
        ...
    
    @recursion_lock()
    def __str__(self) -> str:
        ...
    
    def search(self, pattern):
        """
        Searches a container (non-recursively) using regex.
        """
        ...
    
    def search_all(self, pattern):
        """
        Searches a container (recursively) using regex.
        """
        ...
    


