"""
This type stub file was generated by pyright.
"""

from construct.lib.py3compat import *

"""
This type stub file was generated by pyright.
"""
class HexDisplayedInteger(integertypes[0]):
    """Used internally."""
    def __str__(self) -> str:
        ...
    
    @staticmethod
    def new(intvalue, fmtstr):
        ...
    


class HexDisplayedBytes(bytestringtype):
    """Used internally."""
    def __str__(self) -> str:
        ...
    


class HexDisplayedDict(dict):
    """Used internally."""
    def __str__(self) -> str:
        ...
    


class HexDumpDisplayedBytes(bytestringtype):
    """Used internally."""
    def __str__(self) -> str:
        ...
    


class HexDumpDisplayedDict(dict):
    """Used internally."""
    def __str__(self) -> str:
        ...
    


PRINTABLE = ...
HEXPRINT = ...
def hexdump(data, linesize):
    r"""
    Turns bytes into a unicode string of the format:

    ::

        >>>print(hexdump(b'0' * 100, 16))
        hexundump(\"\"\"
        0000   30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000
        0010   30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000
        0020   30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000
        0030   30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000
        0040   30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000
        0050   30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000
        0060   30 30 30 30                                       0000
        \"\"\")
    """
    ...

def hexundump(data, linesize):
    r"""
    Reverse of `hexdump`.
    """
    ...

