"""
This type stub file was generated by pyright.
"""

from .core import Cache, DEFAULT_SETTINGS, Disk, ENOVAL, EVICTION_POLICY, EmptyDirWarning, JSONDisk, Timeout, UNKNOWN, UnknownFileWarning
from .fanout import FanoutCache
from .persistent import Deque, Index
from .recipes import Averager, BoundedSemaphore, Lock, RLock, barrier, memoize_stampede, throttle
from .djangocache import DjangoCache

"""
This type stub file was generated by pyright.
"""
__all__ = ['Averager', 'BoundedSemaphore', 'Cache', 'DEFAULT_SETTINGS', 'Deque', 'Disk', 'ENOVAL', 'EVICTION_POLICY', 'EmptyDirWarning', 'FanoutCache', 'Index', 'JSONDisk', 'Lock', 'RLock', 'Timeout', 'UNKNOWN', 'UnknownFileWarning', 'barrier', 'memoize_stampede', 'throttle']
__title__ = ...
__version__ = ...
__build__ = ...
__author__ = ...
__license__ = ...
__copyright__ = ...
