#!/usr/bin/env python3
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def audit_python_files() -> list[str]:
    findings: list[str] = []
    print("Auditing Python files...")
    # Patterns
    pokemon_pattern = re.compile(r"except\s*:\s*pass|except\s+Exception\s*:\s*pass|errors\s*=\s*['\"]ignore['\"]")
    passthrough_pattern = re.compile(
        r"def\s+(\w+)\(self,\s*\*args,\s*\*\*kwargs\):\s*return\s+self\.\w+\(\*args,\s*\*\*kwargs\)"
    )

    for root, _, files in os.walk(os.path.join(ROOT, "mcubridge")):
        for f in files:
            if f.endswith(".py"):
                path = os.path.join(root, f)
                content = open(path, "r", encoding="utf-8").read()

                # Check pokemon / suppressions
                for i, line in enumerate(content.splitlines(), 1):
                    if pokemon_pattern.search(line):
                        findings.append(f"Python Suppression: {f}:{i} - '{line.strip()}'")
                    if passthrough_pattern.search(line):
                        findings.append(f"Python Passthrough Shim: {f}:{i} - '{line.strip()}'")
    return findings


def audit_cpp_files() -> list[str]:
    findings: list[str] = []
    print("Auditing C++ files...")
    # Patterns
    loop_pattern = re.compile(r"\b(for|while)\s*\(.*?\)")
    non_template_wrapper_pattern = re.compile(r"class\s+\w+Wrapper\b(?!.*template)")

    for root, _, files in os.walk(os.path.join(ROOT, "mcubridge-library-arduino/src")):
        for f in files:
            if f.endswith((".h", ".cpp")):
                # Skip external / autogenerated code if any
                if "mcubridge.pb" in f or "pb_encode" in f or "pb_decode" in f or "pb_common" in f:
                    continue
                path = os.path.join(root, f)
                content = open(path, "r", encoding="utf-8").read()

                # Check loops
                for i, line in enumerate(content.splitlines(), 1):
                    # Simple filter to avoid comments
                    if line.strip().startswith(("//", "/*", "*")):
                        continue
                    if loop_pattern.search(line):
                        findings.append(f"C++ Loop Found: {f}:{i} - '{line.strip()}'")
                    if non_template_wrapper_pattern.search(line):
                        findings.append(f"C++ Non-Template Wrapper Found: {f}:{i} - '{line.strip()}'")
    return findings


if __name__ == "__main__":
    py_findings = audit_python_files()
    cpp_findings = audit_cpp_files()

    print("\n--- RESULTS ---")
    if not py_findings and not cpp_findings:
        print("No violations or shims found! The codebase is 100% clean and compliant.")
    else:
        for f in py_findings + cpp_findings:
            print(f)
