"""Shared constants for MCU Bridge daemon components.

This file is the central registry for **application defaults** (paths, limits,
intervals) used when the OpenWrt UCI configuration is missing or incomplete.

[SIL-2 COMPLIANCE - IEC 61508]
Default values are chosen with safety margins:
- Timeouts prevent indefinite blocking
- Queue limits prevent memory exhaustion
- File paths default to /tmp (RAM) to protect flash storage
- All limits are validated in config/settings.py before use

Architecture Layers:
- `mcubridge.protocol.protocol`: Generated byte-level contract (source of truth).
- `mcubridge.const`: Application defaults (this file).
- `mcubridge.config.settings`: Runtime configuration loaded from UCI/defaults.

Configuration Flow:
    spec.toml -> generate.py -> protocol.py (constants)
    UCI/defaults -> settings.py -> RuntimeConfig (validated)
"""

from __future__ import annotations

from ssl import TLSVersion

from ..protocol import protocol

# ==============================================================================
# SECTION 1: STATUS CODES (Application Logic)
# ==============================================================================

# -- Status Codes --
SERIAL_FAILURE_STATUS_CODES: frozenset[int] = frozenset(
    {
        protocol.Status.ERROR.value,
        protocol.Status.CMD_UNKNOWN.value,
        protocol.Status.MALFORMED.value,
        protocol.Status.CRC_MISMATCH.value,
        protocol.Status.TIMEOUT.value,
        protocol.Status.NOT_IMPLEMENTED.value,
    }
)
SERIAL_SUCCESS_STATUS_CODES: frozenset[int] = frozenset({protocol.Status.OK.value})


# ==============================================================================
# SECTION 2: APPLICATION DEFAULTS
# ==============================================================================
# These values define the default behavior of the Python daemon.
# They can usually be overridden by UCI configuration or Environment Variables.

# -- Serial Port Defaults --
DEFAULT_SERIAL_PORT: str = "/dev/ttyATH0"
# Initial wait for serial port availability (reconnect loop)
DEFAULT_RECONNECT_DELAY: int = 5
# Timeout for general serial operations (not strict RPC)
DEFAULT_SERIAL_RETRY_TIMEOUT: float = 10.0
DEFAULT_SERIAL_RESPONSE_TIMEOUT: float = 15.0
# Baudrate negotiation timeout
SERIAL_BAUDRATE_NEGOTIATION_TIMEOUT: float = 2.0
DEFAULT_SERIAL_HANDSHAKE_MIN_INTERVAL: float = 0.0
# How many fatal handshake failures before restarting the serial task
DEFAULT_SERIAL_HANDSHAKE_FATAL_FAILURES: int = 15
# Backoff strategy for handshake retries
SERIAL_HANDSHAKE_BACKOFF_BASE: float = 1.0
SERIAL_HANDSHAKE_BACKOFF_MAX: float = 60.0
SERIAL_MIN_ACK_TIMEOUT: float = 0.5

# -- MQTT Defaults --
DEFAULT_MQTT_HOST: str = "127.0.0.1"
DEFAULT_MQTT_PORT: int = 8883
DEFAULT_MQTT_CAFILE: str = "/etc/ssl/certs/ca-certificates.crt"
DEFAULT_MQTT_QUEUE_LIMIT: int = 256
MQTT_TLS_MIN_VERSION: TLSVersion = TLSVersion.TLSv1_2
# [CRITICAL] Spool directory in RAM to prevent Flash wear
DEFAULT_MQTT_SPOOL_DIR: str = "/tmp/mcubridge/spool"
MQTT_USER_PROP_FILE_PATH: str = "bridge-file-path"

# -- MQTT Message Expiry Intervals (seconds) --
MQTT_EXPIRY_PIN: int = 5
MQTT_EXPIRY_CONSOLE: int = 5
MQTT_EXPIRY_DATASTORE: int = 60
MQTT_EXPIRY_SHELL: int = 30
MQTT_EXPIRY_DEFAULT: int = 10

# -- MQTT Spool Backoff Strategy --
SPOOL_BACKOFF_MULTIPLIER: float = 5.0
SPOOL_BACKOFF_MIN_SECONDS: float = 5.0
SPOOL_BACKOFF_MAX_SECONDS: float = 60.0

# -- File System Defaults --
DEFAULT_FILE_SYSTEM_ROOT: str = "/tmp/yun_files"
DEFAULT_FILE_WRITE_MAX_BYTES: int = 262144
DEFAULT_FILE_STORAGE_QUOTA_BYTES: int = 4194304
# Warning threshold for files growing large in RAM (1MB)
FILE_LARGE_WARNING_BYTES: int = 1048576
# Paths considered safe (volatile/RAM) for writing to avoid flash wear
VOLATILE_STORAGE_PATHS: frozenset[str] = frozenset({"/tmp", "/mnt", "/var/run", "/run"})
SYSTEMD_PRIVATE_PREFIX: str = "systemd-private-"

# -- Component Limits --
DEFAULT_PROCESS_TIMEOUT: int = 10
DEFAULT_PROCESS_MAX_OUTPUT_BYTES: int = 65536
DEFAULT_PROCESS_MAX_CONCURRENT: int = 4
# [SIL-2] Process kill timeouts (seconds)
# Timeout to wait for process termination after SIGKILL
PROCESS_KILL_WAIT_TIMEOUT: float = 0.5
# Timeout to wait for sync process termination after kill
PROCESS_SYNC_KILL_WAIT_TIMEOUT: float = 1.0
DEFAULT_CONSOLE_QUEUE_LIMIT_BYTES: int = 16384
DEFAULT_MAILBOX_QUEUE_LIMIT: int = 64
DEFAULT_MAILBOX_QUEUE_BYTES_LIMIT: int = 65536
DEFAULT_PENDING_PIN_REQUESTS: int = 32

# -- Telemetry & Status --
STATUS_FILE_PATH: str = "/tmp/mcubridge_status.json"
DEFAULT_STATUS_INTERVAL: int = 5
DEFAULT_BRIDGE_SUMMARY_INTERVAL: int = 60
DEFAULT_BRIDGE_HANDSHAKE_INTERVAL: int = 300
DEFAULT_METRICS_HOST: str = "127.0.0.1"
DEFAULT_METRICS_PORT: int = 9130
DEFAULT_METRICS_ENABLED: bool = False

# -- Logging --
DEFAULT_DEBUG_LOGGING: bool = False

# -- Security --
MIN_SERIAL_SHARED_SECRET_LEN: int = 8
# SECURITY WARNING: This default secret is for initial setup only.
# It MUST be rotated using 'mcubridge-rotate-credentials' before production use.
DEFAULT_SERIAL_SHARED_SECRET: bytes = b"failsafe_secret_mode"
ALLOWED_COMMAND_WILDCARD: str = "*"
TOPIC_FORBIDDEN_REASON: str = "topic-action-forbidden"

# -- Watchdog --
WATCHDOG_TRIGGER_TOKEN: bytes = b"WATCHDOG=trigger\n"
DEFAULT_WATCHDOG_ENABLED: bool = False
DEFAULT_WATCHDOG_INTERVAL: float = 10.0
WATCHDOG_MIN_INTERVAL: float = 0.5

# -- Task Supervisor --
SUPERVISOR_DEFAULT_RESTART_INTERVAL: float = 60.0
SUPERVISOR_DEFAULT_MIN_BACKOFF: float = 1.0
SUPERVISOR_DEFAULT_MAX_BACKOFF: float = 30.0
# Specific intervals for non-critical tasks (status-writer, metrics, snapshots)
SUPERVISOR_STATUS_RESTART_INTERVAL: float = 120.0
SUPERVISOR_PROMETHEUS_RESTART_INTERVAL: float = 300.0
SUPERVISOR_STATUS_MAX_BACKOFF: float = 10.0
SUPERVISOR_MIN_RESTART_WINDOW: float = 1.0

# -- Feature Flags --
DEFAULT_MQTT_TLS_INSECURE: bool = False
DEFAULT_ALLOW_NON_TMP_PATHS: bool = False


__all__ = [
    "STATUS_FILE_PATH",
    "ALLOWED_COMMAND_WILDCARD",
    "MQTT_TLS_MIN_VERSION",
    "DEFAULT_SERIAL_PORT",
    "DEFAULT_MQTT_HOST",
    "DEFAULT_MQTT_PORT",
    "DEFAULT_MQTT_CAFILE",
    "DEFAULT_FILE_SYSTEM_ROOT",
    "DEFAULT_FILE_WRITE_MAX_BYTES",
    "DEFAULT_FILE_STORAGE_QUOTA_BYTES",
    "FILE_LARGE_WARNING_BYTES",
    "DEFAULT_PROCESS_TIMEOUT",
    "DEFAULT_MQTT_QUEUE_LIMIT",
    "DEFAULT_RECONNECT_DELAY",
    "DEFAULT_STATUS_INTERVAL",
    "DEFAULT_CONSOLE_QUEUE_LIMIT_BYTES",
    "DEFAULT_MAILBOX_QUEUE_LIMIT",
    "DEFAULT_MAILBOX_QUEUE_BYTES_LIMIT",
    "DEFAULT_PENDING_PIN_REQUESTS",
    "DEFAULT_SERIAL_RETRY_TIMEOUT",
    "DEFAULT_SERIAL_RESPONSE_TIMEOUT",
    "DEFAULT_SERIAL_HANDSHAKE_MIN_INTERVAL",
    "SERIAL_HANDSHAKE_BACKOFF_BASE",
    "SERIAL_HANDSHAKE_BACKOFF_MAX",
    "MIN_SERIAL_SHARED_SECRET_LEN",
    "DEFAULT_SERIAL_SHARED_SECRET",
    "DEFAULT_SERIAL_HANDSHAKE_FATAL_FAILURES",
    "SERIAL_MIN_ACK_TIMEOUT",
    "SERIAL_FAILURE_STATUS_CODES",
    "SERIAL_SUCCESS_STATUS_CODES",
    "DEFAULT_MQTT_SPOOL_DIR",
    "MQTT_USER_PROP_FILE_PATH",
    "MQTT_EXPIRY_PIN",
    "MQTT_EXPIRY_CONSOLE",
    "MQTT_EXPIRY_DATASTORE",
    "MQTT_EXPIRY_SHELL",
    "MQTT_EXPIRY_DEFAULT",
    "DEFAULT_PROCESS_MAX_OUTPUT_BYTES",
    "DEFAULT_PROCESS_MAX_CONCURRENT",
    "DEFAULT_METRICS_HOST",
    "DEFAULT_METRICS_PORT",
    "DEFAULT_METRICS_ENABLED",
    "DEFAULT_BRIDGE_SUMMARY_INTERVAL",
    "DEFAULT_BRIDGE_HANDSHAKE_INTERVAL",
    "DEFAULT_DEBUG_LOGGING",
    "WATCHDOG_TRIGGER_TOKEN",
    "DEFAULT_WATCHDOG_ENABLED",
    "DEFAULT_WATCHDOG_INTERVAL",
    "SUPERVISOR_DEFAULT_RESTART_INTERVAL",
    "SUPERVISOR_DEFAULT_MIN_BACKOFF",
    "SUPERVISOR_DEFAULT_MAX_BACKOFF",
    "SUPERVISOR_STATUS_RESTART_INTERVAL",
    "SUPERVISOR_PROMETHEUS_RESTART_INTERVAL",
    "SUPERVISOR_STATUS_MAX_BACKOFF",
    "SUPERVISOR_MIN_RESTART_WINDOW",
    "WATCHDOG_MIN_INTERVAL",
    "SERIAL_BAUDRATE_NEGOTIATION_TIMEOUT",
    "SPOOL_BACKOFF_MULTIPLIER",
    "SPOOL_BACKOFF_MIN_SECONDS",
    "SPOOL_BACKOFF_MAX_SECONDS",
    "TOPIC_FORBIDDEN_REASON",
    "DEFAULT_MQTT_TLS_INSECURE",
    "DEFAULT_ALLOW_NON_TMP_PATHS",
    "VOLATILE_STORAGE_PATHS",
    "SYSTEMD_PRIVATE_PREFIX",
]
