"""Type stub for hypothesis.stateful submodule [SIL-2]."""

from collections.abc import Callable
from typing import Any, TypeVar

_F = TypeVar("_F", bound=Callable[..., Any])

class RuleBasedStateMachine:
    def __init__(self) -> None: ...
    def teardown(self) -> None: ...

def rule(*args: Any, **kwargs: Any) -> Callable[[_F], _F]: ...
def invariant(*args: Any, **kwargs: Any) -> Callable[[_F], _F]: ...
def run_state_machine_as_test(state_machine_factory: type[RuleBasedStateMachine], *args: Any, **kwargs: Any) -> None: ...
