"""Type stub for hypothesis.strategies submodule [SIL-2]."""

from typing import Any

class SearchStrategy: ...

def binary(min_size: int = ..., max_size: int | None = ...) -> SearchStrategy: ...
def integers(min_value: int | None = ..., max_value: int | None = ...) -> SearchStrategy: ...
def one_of(*args: Any, **kwargs: Any) -> SearchStrategy: ...
